import type { AffiliateItem } from './types'

// ─────────────────────────────────────────────────────────────────────────────
// 에디터 추천 개별 상품 — 실존 검증된 대표 상품 (2026-07 웹 리서치)
//
// 숙소: Booking.com 상세 페이지 직결 (aid=7854081, rel=sponsored 수익 추적)
// 체험: KKday 실제 상품 페이지 (파트너 딥링크 수령 시 href 교체 → active_affiliate)
//
// ⚠️ 상품 추가/교체 시: 반드시 실존 확인(검색) 후 등록. localize.ts에 EN/JP도 추가.
// ─────────────────────────────────────────────────────────────────────────────

const B = (path: string) => `https://www.booking.com/hotel/${path}?aid=7854081`

export const FEATURED_STAYS: AffiliateItem[] = [
  {
    id: 'stay-millennials-shibuya',
    rating: '9.0',
    ratingAsOf: '2026-08-06',
    reviews: '2,235',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏨',
    productTitle: '더 밀레니얼스 시부야',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '3층 코워킹 .andwork(100Mbps+·무료 폰부스)와 4층 라운지. 시부야역 도보 6분, 무료 커피와 해피아워까지.',
    cta: '실시간 요금 확인',
    href: B('jp/the-millennials-shibuya-shibuya-ku.html'),
    badge: '코워킹 내장',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/accommodation-urban-studio-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-lively-osaka',
    rating: '8.7',
    ratingAsOf: '2026-08-06',
    reviews: '3,327',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏨',
    productTitle: '더 라이블리 오사카 혼마치',
    destination: '오사카 · 일본',
    country: '일본',
    desc: '작업 가능한 공용 라운지 7곳, 코워킹 투숙객 무료. 사카이스지혼마치역 도보 1분, 평점 8.7 (2,600+ 리뷰).',
    cta: '실시간 요금 확인',
    href: B('jp/the-lively-osaka.html'),
    badge: '라운지 워크',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/japanese-ryokan-work-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-webase-hakata',
    rating: '8.7',
    ratingAsOf: '2026-08-06',
    reviews: '1,176',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏨',
    productTitle: '위베이스 하카타',
    destination: '후쿠오카 · 일본',
    country: '일본',
    desc: '9층 라운지 코워킹(투숙객 무료), Wi-Fi 최대 150Mbps. 나카스카와바타역 도보 3분, 평점 8.6.',
    cta: '실시간 요금 확인',
    href: B('jp/webase-hakata-hostel.html'),
    badge: '무료 코워킹',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/social-stay-lounge-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-tribal-bali',
    rating: '9.1',
    ratingAsOf: '2026-08-06',
    reviews: '646',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🌴',
    productTitle: '트라이벌 코워킹 발리',
    destination: '발리 짱구 · 인도네시아',
    country: '인도네시아',
    desc: '발리 최초 코워킹 전용 설계 숙소. 스탠딩 데스크·부스 갖춘 코워킹(투숙객 무료)과 노마드 커뮤니티.',
    cta: '실시간 요금 확인',
    href: B('id/tribal-bali-mengwi.html'),
    badge: '노마드 성지',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/tropical-coliving-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-chicland-danang',
    rating: '8.7',
    ratingAsOf: '2026-08-06',
    reviews: '630',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏖',
    productTitle: '시클랜드 다낭 비치 호텔',
    destination: '다낭 · 베트남',
    country: '베트남',
    desc: '미케비치 바로 앞, 전 객실 워크데스크와 고층 인피니티 풀. 노마드 거점 안트엉 인근, 평점 8.6.',
    cta: '실시간 요금 확인',
    href: B('vn/chicland-da-nang.html'),
    badge: '비치 워크',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/coastal-residence-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-playce-jeju',
    rating: '8.7',
    ratingAsOf: '2026-08-06',
    reviews: '328',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🍊',
    productTitle: '플레이스캠프 제주',
    destination: '제주 성산 · 국내',
    country: '국내',
    desc: '침실과 업무 데스크 분리형 객실, 워케이션 전용 패키지 운영. 성산 일출봉 인근.',
    cta: '실시간 요금 확인',
    href: B('kr/playce-camp-jeju.html'),
    badge: '워케이션 특화',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/hanok-stay-work-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-kantary-chiangmai',
    rating: '9.0',
    ratingAsOf: '2026-08-06',
    reviews: '195',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏙',
    productTitle: '칸타리 힐스 치앙마이',
    destination: '치앙마이 님만 · 태국',
    country: '태국',
    desc: '키치넷 스위트(46㎡+) 서비스드 아파트, 장기 체류 특화. 님만해민 소이 12, 마야몰 도보권.',
    cta: '실시간 요금 확인',
    href: B('th/kantary-hills-chiang-mai.html'),
    badge: '장기체류',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/forest-cabin-desk-editorial-v1.webp', illustrative: true,
  },
]

export const FEATURED_ACTIVITIES: AffiliateItem[] = [
  {
    id: 'act-tokyo-disney',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🎡',
    productTitle: '도쿄 디즈니랜드·디즈니씨 티켓',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '모바일 QR로 즉시 입장하는 1일권. 워케이션 주말을 특별하게.',
    cta: '상품 보기',
    priceFrom: '₩80,187~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/19252?cid=25833',
    badge: '테마파크',
    trackingId: 'cid=25833',
    coverPhoto: '/media/destinations/tokyo-editorial-v1.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-osaka-usj',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🎢',
    productTitle: '유니버설 스튜디오 재팬 입장권',
    destination: '오사카 · 일본',
    country: '일본',
    desc: 'USJ 1일권 + 익스프레스 패스 옵션. 줄 서지 않는 오사카 주말.',
    cta: '상품 보기',
    priceFrom: '₩88,296~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/20944?cid=25833',
    badge: '익스프레스',
    trackingId: 'cid=25833',
    coverPhoto: '/media/destinations/osaka-editorial-v1.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-fukuoka-bustour',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🚌',
    productTitle: '후쿠오카 근교 버스투어 (한국어)',
    destination: '후쿠오카 · 일본',
    country: '일본',
    desc: '다자이후·유후인·벳부 일일투어. 하카타역 출발, 한국인 가이드 동행.',
    cta: '상품 보기',
    priceFrom: '₩39,000~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/134297?cid=25833',
    badge: '한국어 가이드',
    trackingId: 'cid=25833',
    coverPhoto: '/media/destinations/fukuoka-editorial-v1.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-bali-ubud',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🌾',
    productTitle: '발리 우붓 프라이빗 투어 (한국어)',
    destination: '발리 · 인도네시아',
    country: '인도네시아',
    desc: '사원·라이스테라스 반나절 맞춤 프라이빗. 원하는 코스로 자유롭게.',
    cta: '상품 보기',
    priceFrom: '₩11,256~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/141520?cid=25833',
    badge: '프라이빗',
    trackingId: 'cid=25833',
    coverPhoto: '/media/destinations/bali-editorial-v1.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-danang-banahills',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🌉',
    productTitle: '다낭 바나힐 단독투어 (한국어)',
    destination: '다낭 · 베트남',
    country: '베트남',
    desc: '골든브릿지 포함, 입장권·중식·픽업까지. 단독 차량 일일투어.',
    cta: '상품 보기',
    priceFrom: '₩85,000~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/129472?cid=25833',
    badge: '올인클루시브',
    trackingId: 'cid=25833',
    coverPhoto: '/media/destinations/danang-editorial-v1.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },

  // ── Klook 6종 (2026-07-15) — aid=126848 부착
  // 상품 실존: klook.com 자체 검색 인덱스로 확인. aid 파라미터 형식: 실제 유통 중인
  // Klook 어필리에이트 URL 2건(aid=15027, aid=11271)에서 실물 확인
  // ⚠️ 대시보드에서 계정 승인·클릭 집계 확인 필요 (미승인이면 링크는 열리되 커미션 미집계)
  {
    id: 'act-klook-teamlab-tokyo',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🪐',
    productTitle: '팀랩 플래닛 도쿄 티켓',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '도요스의 몰입형 미디어아트. 물에 발을 담그고 걷는 전시 — 저녁 시간대 추천.',
    cta: 'Klook에서 현재 조건 확인',
    rating: '4.7',
    ratingAsOf: '2026-08-06',
    reviews: '20,941',
    priceFrom: 'JPY 3,600~',
    priceAsOf: '2026-08-10',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F25300-teamlab-planets-toyosu-tokyo-ticket%2F',
    deepLinks: {
      KO: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F25300-teamlab-planets-toyosu-tokyo-ticket%2F',
      EN: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fen-US%2Factivity%2F25300-teamlab-planets-toyosu-tokyo-ticket%2F',
      JP: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fja%2Factivity%2F25300-teamlab-planets-toyosu-tokyo-ticket%2F',
    },
    badge: '몰입형 전시',
    trackingId: 'aid=126848',
    coverPhoto: '/media/destinations/tokyo-editorial-v1.webp', illustrative: true,
    operatorAction: 'Klook 공식 리다이렉트 3개 로케일 적용 완료 (aid=126848, 2026-08-10)',
    sourceNote: 'Klook 상품 평점·후기 실측(2026-08-06), 공식 teamLab 티켓 스토어 성인 입장권 JPY 3,600~ 재확인(2026-08-10)',
  },
  {
    id: 'act-klook-osaka-pass',
    name: 'Klook',
    category: 'activity',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '🎫',
    productTitle: '오사카 주유패스',
    destination: '오사카 · 일본',
    country: '일본',
    desc: '지하철·버스 무제한 + 우메다 공중정원 등 40여 곳 입장. 오사카 워케이션 주말 필수템.',
    cta: '패스 보기',
    rating: '4.7',
    ratingAsOf: '2026-08-06',
    reviews: '21,088',
    priceFrom: '₩33,100~',
    priceAsOf: '2026-08-06',
    href: 'https://www.klook.com/ko/activity/82312-amazing-pass-osaka/?aid=126848',
    badge: '교통+입장',
    trackingId: 'aid=126848',
    coverPhoto: '/media/destinations/osaka-editorial-v1.webp', illustrative: true,
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
    sourceNote: 'Klook 상품 JSON-LD 평점·리뷰 실측 (기준 2026-08-06) — 평점·리뷰수·가격',
  },
  {
    id: 'act-klook-taipei-tour',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏮',
    productTitle: '예류·지우펀·스펀 일일투어 (한국어 가이드)',
    destination: '타이베이 · 대만',
    country: '대만',
    desc: '타이베이 근교 3대 명소를 하루에. 스펀 천등 날리기 포함, 한국어 가이드 동행.',
    cta: '투어 보기',
    rating: '4.9',
    ratingAsOf: '2026-08-06',
    reviews: '3,855',
    priceFrom: '₩15,100~',
    priceAsOf: '2026-08-06',
    href: 'https://www.klook.com/ko/activity/3521-jiufen-full-day-tour-taipei/?aid=126848',
    badge: '한국어 가이드',
    trackingId: 'aid=126848',
    coverPhoto: '/media/verified/unsplash/1470004914212-05527e49370b.webp', illustrative: true,
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
    sourceNote: 'Klook 상품 JSON-LD 평점·리뷰 실측 (기준 2026-08-06) — 평점·리뷰수·가격',
  },
  {
    id: 'act-klook-uss-singapore',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🎢',
    productTitle: '유니버설 스튜디오 싱가포르 티켓',
    destination: '싱가포르',
    country: '싱가포르',
    desc: '센토사의 7개 테마존. 싱가포르 워케이션 주말을 채우는 정석 코스.',
    cta: '티켓 보기',
    rating: '4.8',
    ratingAsOf: '2026-08-06',
    reviews: '107,986',
    priceFrom: '₩75,600~',
    priceAsOf: '2026-08-06',
    href: 'https://www.klook.com/ko/activity/117-universal-studios-singapore/?aid=126848',
    badge: '테마파크',
    trackingId: 'aid=126848',
    coverPhoto: '/media/verified/unsplash/1525625293386-3f8f99389edd.webp', illustrative: true,
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
    sourceNote: 'Klook 상품 JSON-LD 평점·리뷰 실측 (기준 2026-08-06) — 평점·리뷰수·가격',
  },
  {
    id: 'act-klook-nusapenida-bali',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏝',
    productTitle: '발리 누사페니다 일일투어',
    destination: '발리 · 인도네시아',
    country: '인도네시아',
    desc: '켈링킹 절벽·브로큰 비치·크리스탈 베이. 발리에서 꼭 한 번은 가는 섬.',
    cta: '투어 보기',
    rating: '4.6',
    ratingAsOf: '2026-08-06',
    reviews: '15,849',
    priceFrom: '₩22,000~',
    priceAsOf: '2026-08-06',
    href: 'https://www.klook.com/ko/activity/15758-nusa-penida-full-day-trip-bali/?aid=126848',
    badge: '일일 투어',
    trackingId: 'aid=126848',
    coverPhoto: '/media/destinations/bali-editorial-v1.webp', illustrative: true,
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
    sourceNote: 'Klook 상품 JSON-LD 평점·리뷰 실측 (기준 2026-08-06) — 평점·리뷰수·가격',
  },
  {
    id: 'act-klook-elephant-chiangmai',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🐘',
    productTitle: '치앙마이 코끼리 정글 생추어리',
    destination: '치앙마이 · 태국',
    country: '태국',
    desc: '타지 않고 먹이 주며 돌보는 생추어리형 코끼리 체험. 오전 반나절 코스.',
    cta: '체험 보기',
    rating: '4.8',
    ratingAsOf: '2026-08-06',
    reviews: '3,060',
    priceFrom: '₩29,800~',
    priceAsOf: '2026-08-06',
    href: 'https://www.klook.com/ko/activity/3631-elephant-jungle-sanctuary-chiang-mai/?aid=126848',
    badge: '윤리적 체험',
    trackingId: 'aid=126848',
    coverPhoto: '/media/destinations/chiangmai-editorial-v1.webp', illustrative: true,
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
    sourceNote: 'Klook 상품 JSON-LD 평점·리뷰 실측 (기준 2026-08-06) — 평점·리뷰수·가격',
  },
  // ── 2026-08-17 Klook 파트너 Product Explorer 피드 확충 8종 ──────────────────
  // 링크·가격(US$)·'즉시확정' 태그 전부 공식 피드 CSV 실측(기준 2026-08-17).
  // 피드 원본 링크의 _currency=USD 파라미터는 표시 통화 강제라 제거(aid·k_site 추적 무변).
  {
    id: 'act-klook-gardens-singapore',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '🌿', productTitle: '가든스 바이 더 베이 입장권', destination: '싱가포르', country: '싱가포르',
    desc: '슈퍼트리와 플라워 돔의 도심 정원 — 일 마친 저녁 산책 코스로 좋습니다.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$18.79~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F127-gardens-by-the-bay-singapore%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-gardens-dome-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-emerald-900 via-teal-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
  {
    id: 'act-klook-umeda-osaka',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '🌆', productTitle: '우메다 스카이빌딩 공중정원 전망대', destination: '오사카 · 일본', country: '일본',
    desc: '오사카 야경을 옥상 데크에서 — 블루아워에 오르면 도시가 물들어 갑니다.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$11.25~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F35861-umeda-sky-building-kuchu-teien-observatory-ticket%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-umeda-dusk-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-indigo-900 via-slate-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
  {
    id: 'act-klook-taipei101',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '🗼', productTitle: '타이베이 101 전망대 입장권', destination: '타이베이 · 대만', country: '대만',
    desc: '타이베이를 한눈에 담는 랜드마크 전망대 — 흐린 날은 피해서 방문하세요.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$17.85~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F1659-taipei-101-taipei%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-taipei-observatory-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-sky-900 via-slate-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
  {
    id: 'act-klook-mahanakhon-bangkok',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '🏙', productTitle: '킹파워 마하나콘 스카이워크', destination: '방콕 · 태국', country: '태국',
    desc: '유리 바닥 스카이워크에서 방콕 전경을 — 노을 시간대가 압권입니다.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$10.59~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F16870-king-power-mahanakhon-skywalk-ticket-bangkok%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-mahanakhon-skywalk-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-amber-900 via-slate-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
  {
    id: 'act-klook-ngongping-hongkong',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '🚠', productTitle: '옹핑 360 케이블카 티켓', destination: '홍콩', country: '홍콩',
    desc: '란타우섬 산과 바다 위를 가르는 케이블카 — 크리스탈 캐빈은 바닥까지 유리.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$21.05~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F45-ngong-ping-360-hong-kong%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-ngongping-cablecar-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-teal-900 via-slate-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
  {
    id: 'act-klook-landmark81-hcmc',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '🌃', productTitle: '랜드마크 81 사이공 스카이뷰', destination: '호치민 · 베트남', country: '베트남',
    desc: '베트남 최고층에서 사이공강과 도심을 — 저녁 야경 타임 추천.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$9.55~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F27021-saigon-skyview-ticket-ho-chi-minh-city%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-landmark81-skyline-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-purple-900 via-slate-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
  {
    id: 'act-klook-teamlab-fukuoka',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '✨', productTitle: '팀랩 포레스트 후쿠오카 입장권', destination: '후쿠오카 · 일본', country: '일본',
    desc: '숲을 걷듯 빠져드는 몰입형 미디어아트 — 보스 E·ZO 후쿠오카 내 위치.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$5.69~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F51227-teamlab-forest-fukuoka%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-immersive-art-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-fuchsia-900 via-slate-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
  {
    id: 'act-klook-hanbok-seoul',
    name: 'Klook', category: 'activity', productType: 'activity', status: 'active_affiliate',
    emoji: '👘', productTitle: '경복궁 한복 대여 체험', destination: '서울 · 국내', country: '국내',
    desc: '한복 입고 고궁 산책 — 대여 시간 안에 경복궁·북촌까지 돌아보기 좋아요.',
    cta: 'Klook에서 현재 조건 확인', priceFrom: 'US$14.19~', priceAsOf: '2026-08-17',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F901-hanbok-rental-experience-seoul%2F',
    badge: '즉시확정', coverPhoto: '/media/product-editorial/act-hanbok-palace-editorial-v1.webp', illustrative: true,
    coverGradient: 'from-rose-900 via-slate-950 to-[#0d0d0d]',
    sourceNote: 'Klook 파트너 상품 피드 실측 — 가격·즉시확정 태그 (기준 2026-08-17)',
  },
]

// eSIM 실상품 — Klook (2026-07-15, 검색 인덱스 실존 확인 + aid=126848)
// Airalo(Impact)와 병행 — 사용자에게 선택지, 우리에겐 이중 수익 채널
export const FEATURED_ESIM: AffiliateItem[] = [
  {
    id: 'esim-klook-japan',
    name: 'Klook',
    category: 'esim',
    productType: 'esim',
    status: 'active_affiliate',
    emoji: '🇯🇵',
    productTitle: '일본 eSIM (DOCOMO·Softbank)',
    destination: '일본',
    country: '일본',
    desc: 'QR 코드로 5분 개통. 무제한·일별 플랜, 현지 통신사 회선이라 속도가 안정적.',
    cta: 'eSIM 보기',
    href: 'https://www.klook.com/ko/activity/109393-japan-esim-high-speed-internet-qr-code-voucher/?aid=126848',
    badge: '일본 특화',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/esim-japan-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-red-900 via-rose-950 to-[#0d0d0d]',
  },
  {
    id: 'esim-klook-asia',
    name: 'Klook',
    category: 'esim',
    productType: 'esim',
    status: 'active_affiliate',
    emoji: '🌏',
    productTitle: '아시아 30+개국 eSIM',
    destination: '아시아 멀티국',
    country: '아시아 30+개국',
    desc: '일본·태국·베트남·대만을 eSIM 하나로. 여러 나라를 도는 워케이션 루트에.',
    cta: 'eSIM 보기',
    href: 'https://www.klook.com/ko/activity/121525-asia-pacific-esim-high-speed-internet-qr-code-in-the-voucher/?aid=126848',
    badge: '멀티국',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/esim-asia-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-sky-900 via-blue-950 to-[#0d0d0d]',
  },
  // ── 포켓와이파이 3종 (2026-07-26 확충) — 보류 해제: 실브라우저 상품페이지+검색 리스팅 이중검증.
  //    ⚠️ 구 예비 ID(3830·3587·16507·16508)는 meta price 공란+검색 미노출=판매 실데이터 부재 → 폐기.
  //    판정법: 판매 중 상품은 meta[product:price:amount]가 채워짐(109393=500으로 보정 확인)
  {
    id: 'wifi-klook-japan',
    name: 'Klook',
    category: 'esim',
    productType: 'esim',
    status: 'active_affiliate',
    emoji: '📶',
    productTitle: '일본 무제한 포켓 와이파이 (NINJA WiFi)',
    destination: '일본 공항 수령',
    country: '일본',
    desc: '노트북·폰 동시 연결, 무제한 데이터에 보조배터리 포함. 일본 공항에서 수령·반납.',
    cta: '와이파이 보기',
    priceFrom: '1일 ₩3,200~',
    priceAsOf: '2026-07-26',
    rating: '4.7',
    ratingAsOf: '2026-07-26',
    reviews: '11,544',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F16399-unlimited-4g-lte-wifi-japan-airport-pickup-ninja-wifi%2F',
    badge: '포켓와이파이',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/wifi-japan-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-red-900 via-rose-950 to-[#0d0d0d]',
    sourceNote: 'Klook 16399 실브라우저 이중검증 2026-07-26 — 상품페이지 og:title+meta price 3200, 검색 리스팅 ★4.7(11,544)·200K+ 선택·1일 ₩3,200부터·무료취소·즉시확정',
  },
  {
    id: 'wifi-klook-taiwan',
    name: 'Klook',
    category: 'esim',
    productType: 'esim',
    status: 'active_affiliate',
    emoji: '📶',
    productTitle: '대만 4G 휴대용 와이파이',
    destination: '대만 공항 수령',
    country: '대만',
    desc: '타이베이 워케이션의 안정 회선. 대만 공항 수령, 다중 기기 동시 연결.',
    cta: '와이파이 보기',
    priceFrom: '1일 ₩4,500~',
    priceAsOf: '2026-07-26',
    rating: '4.7',
    ratingAsOf: '2026-07-26',
    reviews: '22,937',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F16960-4g-wifi-taiwan%2F',
    badge: '포켓와이파이',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/wifi-taiwan-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-teal-900 via-cyan-950 to-[#0d0d0d]',
    sourceNote: 'Klook 16960 실브라우저 이중검증 2026-07-26 — 상품페이지 meta price 4500, 검색 리스팅 ★4.7(22,937)·1M+ 선택·1일 ₩4,500부터·무료취소·즉시확정',
  },
  {
    id: 'wifi-klook-thailand',
    name: 'Klook',
    category: 'esim',
    productType: 'esim',
    status: 'active_affiliate',
    emoji: '📶',
    productTitle: '태국 무제한 포켓 와이파이',
    destination: '태국 · Klook 카운터 수령',
    country: '태국',
    desc: '방콕·치앙마이 장기 체류의 백업 회선. 무제한 데이터, 카운터 픽업.',
    cta: '와이파이 보기',
    priceFrom: '1일 ₩6,600~',
    priceAsOf: '2026-07-26',
    rating: '4.3',
    ratingAsOf: '2026-07-26',
    reviews: '588',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F81348-thailand-4g-unlimited-pocket-wifi%2F',
    badge: '포켓와이파이',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/wifi-thailand-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-emerald-900 via-teal-950 to-[#0d0d0d]',
    sourceNote: 'Klook 81348 실브라우저 이중검증 2026-07-26 — 상품페이지 meta price 6600, 검색 리스팅 ★4.3(588)·7K+ 선택·1일 ₩6,600부터·무료취소·즉시확정',
  },
]

export const FEATURED_CRUISES: AffiliateItem[] = [
  {
    // 2026-07-18 신설 — 크루즈 카테고리 첫 Klook 제휴 (기존 팬스타 직링크는 제휴 불가였음)
    id: 'cruise-panstar-miracle',
    name: 'Klook',
    category: 'transport',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '⛴',
    productTitle: '팬스타 미라클호 · 부산-오사카 크루즈페리',
    destination: '부산 ↔ 오사카 · 17시간',
    country: '한국 출발',
    desc: '뷔페 2식 포함 승선권으로 하룻밤 만에 오사카. 위성 와이파이·사우나를 갖춘 국내 첫 럭셔리 크루즈페리.',
    cta: '승선권 보기',
    priceFrom: '₩120,000~',
    priceAsOf: '2026-07-26',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F150798-busan-osaka-ferry-ticket%2F',
    deepLinks: {
      KO: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F150798-busan-osaka-ferry-ticket%2F',
      EN: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fen-US%2Factivity%2F150798-busan-osaka-ferry-ticket%2F',
      JP: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fja%2Factivity%2F150798-busan-osaka-ferry-ticket%2F',
    },
    badge: '뷔페 2식 포함',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/cruise-panstar-real-v2.jpeg', illustrative: true,
    coverGradient: 'from-sky-900 via-blue-950 to-[#0d0d0d]',
    sourceNote:
      'Klook activity/150798(403=생존)·KKday 284256 병행 확인 2026-07-18. 취항 2025-04-13·사우나·야외수영장·저궤도 위성 와이파이=팬스타 공식 보도자료. 뷔페 2식(조·석식) 포함=판매처 3사(Klook·KKday·NOL) 상품 구성 일치. 가격 ₩120,000~=KKday 상세 price 위젯 실브라우저 실측(기준 2026-07-26 재검, 정가 ₩200,000 병기 표시·유류할증료 등 별도) — Klook 상세는 옵션 선택 전 가격 미노출 구조',
  },
  {
    id: 'cruise-rci-singapore',
    name: 'Trip.com',
    category: 'transport',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '🚢',
    productTitle: '로얄캐리비안 내비게이터 · 싱가포르 3박4일',
    destination: '싱가포르 → 페낭',
    country: '싱가포르',
    desc: '싱가포르 출항, 페낭 기항 3박4일. 선상 Wi-Fi로 일하며 이동하는 크루즈 워케이션 입문 코스.',
    cta: '요금 보기',
    priceFrom: '₩372,750~',
    priceAsOf: '2026-08-06',
    href: 'https://kr.trip.com/cruises/line-140351-singapore-greater-china-3night-navigator-of-the-seas-rci/?departure=2027-02-01&locale=ko-KR&Allianceid=9024807',
    badge: '싱가포르 출항',
    trackingId: 'Allianceid=9024807',
    coverPhoto: '/media/verified/unsplash/1548574505-5e239809ee19.webp', illustrative: true,
    sourceNote: 'Trip.com 페이지 내장 JSON 실측 ₩362,503 (기준 2026-08-06) — /api/prices 일일 자동 갱신 대상',
  },
  {
    id: 'cruise-msc-world-europa',
    name: 'Trip.com',
    category: 'transport',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '🌍',
    productTitle: 'MSC 월드 유로파 · 카리브해 8일',
    destination: '포르드프랑스 → 카리브 섬들',
    country: '카리브해',
    desc: 'MSC 초대형 플래그십으로 도는 카리브해 일주 8일. 선상에서 일하고 섬에서 쉬는 빅트립.',
    cta: '요금 보기',
    priceFrom: '₩1,170,759~',
    priceAsOf: '2026-07-28',
    // 운영자 제공 링크의 aid=7434330/sid=293744445는 출처 미확인 → 검증된 Allianceid로 교체 (2026-07-13 운영자 "맞는 링크인지 모르겠다")
    href: 'https://kr.trip.com/cruises/ship-msc-cruises-msc-world-europa-944?curr=KRW&Allianceid=9024807',
    badge: '카리브 일주',
    trackingId: 'Allianceid=9024807',
    coverPhoto: '/covers/cruise-caribbean-editorial-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-blue-900 via-indigo-950 to-[#0d0d0d]',
    sourceNote: 'Trip.com 선박 페이지 실측 2026-07-28 — 카리브해 8일 일정(2026-12~2027-02 출항 다수), 최저 ₩1,170,759(2027-02-27 포르드프랑스발) 확인',
  },
  {
    id: 'cruise-msc-bellissima',
    name: 'Trip.com',
    category: 'transport',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '🛳',
    productTitle: 'MSC 벨리시마 · 한국 출발 (부산·인천)',
    destination: '부산·인천 출발 → 제주·규슈·기륭',
    country: '한국 출발',
    desc: '2026 부산 승선(상하이·서귀포 기항), 2027년 6월부터 인천 연중 모항. 스타링크 와이파이의 MSC 초대형선.',
    cta: '일정·요금 보기',
    priceFrom: '₩341,523~',
    priceAsOf: '2026-07-26',
    href: 'https://kr.trip.com/cruises/ship-msc-mscbellissima-496?curr=KRW&Allianceid=9024807',
    badge: '한국 출발',
    trackingId: 'Allianceid=9024807',
    coverPhoto: '/media/verified/unsplash/1599640842225-85d111c60e6b.webp', illustrative: true,
    sourceNote: 'Trip.com 선박 페이지 실측 2026-07-26 — 인천 3박4일(기륭, 2027-06-20) ₩341,523·부산 5일(상하이·서귀포, 2026-09-14) ₩786,671. 인천 모항 2027-06-14부터(롯데관광개발 3년 전세선, CruiseMapper·노컷·한경 교차). 스타링크=MSC 공식 보도자료 2024',
  },
  {
    id: 'cruise-costa-serena',
    name: 'Trip.com',
    category: 'transport',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '🌏',
    productTitle: '코스타 세레나 · 남미-유럽 그랜드 보야지',
    destination: '리우·부에노스아이레스 → 스페인·포르투갈',
    country: '장기 항해',
    desc: '대서양을 건너는 19~23일 장기 항해. 한 달 살기를 배 위에서 하는 리포지셔닝 크루즈.',
    cta: '일정·요금 보기',
    priceFrom: '₩1,553,197~',
    priceAsOf: '2026-07-28',
    href: 'https://kr.trip.com/cruises/ship-costa-costaserena-35?curr=KRW&Allianceid=9024807',
    badge: '장기 항해',
    trackingId: 'Allianceid=9024807',
    coverPhoto: '/covers/cruise-transatlantic-editorial-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-amber-900 via-orange-950 to-[#0d0d0d]',
    sourceNote: 'Trip.com 선박 페이지 실측 2026-07-28 — 리우(4/8발 19일 ₩1,553,197)·부에노스아이레스(4/5발 22~23일) 2027-04 출항 4개 일정, 최저가 확인',
  },
  // 팬스타(페리)·msccruises.co.kr 게시판·마이크루즈북 비제휴 카드는 2026-07-13 운영자 지시로 제거
  // — 크루즈 카드는 전부 Trip.com 실상품 + Allianceid 추적으로 통일
]

export const FEATURED_COURSES: AffiliateItem[] = [
  {
    id: 'course-gpts-automation',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '🤖',
    productTitle: '직장인을 위한 GPTs 업무 자동화',
    destination: 'AI · 자동화',
    desc: '반복 업무를 GPTs로 자동화. 워케이션 중 업무 시간을 줄여주는 실전 강의.',
    cta: '강의 보기',
    priceFrom: '₩33,000',
    priceAsOf: '2026-08-06',
    href: 'https://inf.run/zXusL',
    badge: '실무 AI',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: '/media/verified/unsplash/1677442135703-1787eea5ce01.webp', illustrative: true,
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-15 리다이렉트 실물검증)',
  },
  {
    id: 'course-chatgpt-work',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '⚡',
    productTitle: 'ChatGPT 실무 100% 활용',
    destination: 'AI · 생산성',
    desc: '업무 속도를 10배 올리는 ChatGPT 활용법. 이동 시간에 듣기 좋은 구성.',
    cta: '강의 보기',
    priceFrom: '₩49,500',
    priceAsOf: '2026-08-06',
    href: 'https://inf.run/4j6xb',
    badge: 'AI 생산성',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: '/media/verified/unsplash/1552581234-26160f608093.webp', illustrative: true,
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-15 리다이렉트 실물검증)',
  },
  // 노션·비즈영어·피그마(어필리에이트 미지원, public_external_link)는 2026-07-13 운영자 지시로 제거
  // — 강의 카드는 파트너스 홍보링크 있는 활성 5종만 진열. 새 강의는 운영자 링크 생성 후 추가
  {
    id: 'course-instagram-marketing',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '📢',
    productTitle: '매출을 높이는 인스타그램 마케팅',
    destination: '마케팅 · SNS',
    desc: '1인 비즈니스의 매출을 만드는 인스타 실전 운영. 현지 콘텐츠로 바로 실습.',
    cta: '강의 보기',
    priceFrom: '₩55,000',
    priceAsOf: '2026-08-06',
    href: 'https://inf.run/xTxcg',
    badge: '마케팅',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: '/media/verified/unsplash/1511632765486-a01980e01a18.webp', illustrative: true,
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-15 리다이렉트 실물검증)',
  },
  // ── 2026-07-16 재선정 (1차 3종은 수강제한/제휴불가/부재로 폐기 — 운영자 확인) ──
  // URL은 인프런 검색 인덱스 결과 그대로 사용 (슬러그 조합 금지)
  {
    id: 'course-midjourney-class',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '🎨',
    productTitle: '미드저니 비법 클래스 — AI 이미지 프롬프트 실무',
    destination: 'AI · 디자인',
    desc: '현직 AI 디자인 전문가의 미드저니 프롬프트 엔지니어링. 콘텐츠·상세페이지 이미지를 직접 만드는 실무 강의.',
    cta: '강의 보기',
    priceFrom: '₩79,200',
    priceAsOf: '2026-08-06',
    href: 'https://inf.run/F6yGE',
    badge: 'AI 디자인',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: '/covers/course-midjourney-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-violet-900 via-purple-950 to-[#0d0d0d]',
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-16 리다이렉트 실물검증). 가격 JSON-LD 실측 ₩79,200 (기준 2026-08-06 — 재실측에서 ₩59,400→₩79,200 인상 확인)',
  },
  {
    id: 'course-smartstore-keyword',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '🛒',
    productTitle: '[키워드 완성형] 스마트스토어로 취업부터 부업까지',
    destination: '셀링 · 부업',
    desc: '빅파워 스토어 13개 운영자의 키워드·상품 SEO 실무. 온라인 셀러 워케이셔너의 기본기.',
    cta: '강의 보기',
    priceFrom: '₩53,900',
    priceAsOf: '2026-08-06',
    href: 'https://inf.run/QhWQH',
    badge: '스마트스토어',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: '/covers/course-smartstore-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-emerald-900 via-teal-950 to-[#0d0d0d]',
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-16 리다이렉트 실물검증). 가격 JSON-LD 실측 ₩53,900 (기준 2026-07-13)',
  },
  // ── 2026-07-16 신규 (운영자 전달) ──────────────────────────────────────────
  {
    id: 'course-claude-vibecoding',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '🤖',
    productTitle: '기업을 위한 클로드 코드·바이브코딩 AX 전환',
    destination: 'AI · 바이브코딩',
    desc: '클로드 코드와 바이브코딩으로 업무를 자동화·전환. 노마드·1인 개발자에게 유용한 실전.',
    cta: '강의 보기',
    href: 'https://inf.run/Ec82F',
    badge: '실무 AI',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: '/covers/course-claude-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-violet-900 via-indigo-950 to-[#0d0d0d]',
    sourceNote: '인프런 파트너스 홍보링크 inf.run/Ec82F (2026-07-16 리다이렉트 실물검증, 이종범). 가격 미검증이라 미표기',
  },
  // 무료 추천 강의 3종 — 추적 없음(무료라 커미션 0), 콘텐츠 큐레이션. status=placeholder("외부 링크")
  {
    // 2026-08-17 교체: 제휴 불가 placeholder(노션 무료) → 운영자 생성 파트너 링크 강의
    id: 'course-n8n-automation',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '🤖',
    productTitle: '코딩 없이 AI 자동화 — n8n 완벽 가이드',
    destination: 'AI · 자동화',
    desc: 'GPT·클로드를 n8n에 연결해 반복 업무를 자동화. 코딩 없이 워크플로를 만드는 실무 가이드.',
    cta: '강의 보기',
    priceFrom: '₩68,200',
    priceAsOf: '2026-08-17',
    href: 'https://inf.run/YoJp4',
    badge: '자동화 실무',
    coverPhoto: '/covers/course-notion-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-slate-800 via-slate-900 to-[#0d0d0d]',
    sourceNote: '인프런 강의 페이지 JSON-LD 가격 실측 (기준 2026-08-17) · 파트너 링크 운영자 생성 2026-08-17',
  },
  {
    // 2026-08-17 교체: 제휴 불가 placeholder(파이썬 무료) → 운영자 생성 파트너 링크 강의.
    // 엑셀 무료 카드는 운영자 지시로 제거(2026-08-17)
    id: 'course-react-onebite',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '⚛️',
    productTitle: '한 입 크기로 잘라 먹는 리액트(React.js)',
    destination: '개발 · 프론트엔드',
    desc: '자바스크립트 기초부터 리액트 실전 프로젝트까지 한 번에 — 17시간 올인원 입문.',
    cta: '강의 보기',
    priceFrom: '₩48,400',
    priceAsOf: '2026-08-17',
    href: 'https://inf.run/4xawE',
    badge: '입문~실전',
    coverPhoto: '/covers/course-python-photo-v2.webp',
    illustrative: true,
    coverGradient: 'from-sky-900 via-blue-950 to-[#0d0d0d]',
    sourceNote: '인프런 강의 페이지 JSON-LD 가격 실측 (기준 2026-08-17) · 파트너 링크 운영자 생성 2026-08-17',
  },
]

// 신규 지역 추천 숙소 (2026-07 리서치 검증)
export const FEATURED_STAYS_V2: AffiliateItem[] = [
  {
    id: 'stay-adina-sydney',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🎭',
    productTitle: '아디나 아파트먼트 호텔 시드니 타운홀',
    destination: '시드니 · 호주',
    country: '호주',
    desc: 'CBD 중심 풀키친 아파트호텔. Town Hall역 도보 2분, 회의실 5개(최대 100명)와 온수 수영장.',
    cta: '실시간 요금 확인',
    rating: '9.3',
    ratingAsOf: '2026-08-06',
    reviews: '960',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.booking.com/hotel/au/adina-sydney.html?aid=7854081',
    badge: '풀키친',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/city-highrise-apartment-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-nomadshub-cebu',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏝',
    productTitle: '노마즈 허브 코리빙 세부',
    destination: '세부 · 필리핀',
    country: '필리핀',
    desc: '세부 시티 중심 코워킹+코리빙. 폰부스·컨퍼런스룸, 노마드 커뮤니티의 거점.',
    cta: '실시간 요금 확인',
    rating: '7.0',
    ratingAsOf: '2026-08-06',
    reviews: '117',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.booking.com/hotel/ph/nomad-39-s-hub.html?aid=7854081',
    badge: '코리빙',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/social-stay-lounge-editorial-v1.webp', illustrative: true,
  },
  // ── 2026-07-15 MD 확충 — 웹검색으로 Booking 슬러그 실존 검증 완료 ──
  {
    id: 'stay-lyf-sukhumvit-bangkok',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🛋',
    productTitle: '라이프 수쿰빗 8 방콕',
    destination: '방콕 · 태국',
    country: '태국',
    desc: '나나역 도보 3분 코리빙. 코워킹 스페이스·간이주방·루프탑 — 노마드 특화 설계.',
    cta: '실시간 요금 확인',
    rating: '8.3',
    ratingAsOf: '2026-08-06',
    reviews: '1,920',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.booking.com/hotel/th/lyf-sukhumvit-8-bangkok.html?aid=7854081',
    badge: '코리빙',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/design-hotel-lobby-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-citizenm-taipei',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🚪',
    productTitle: '시티즌엠 타이베이 노스게이트',
    destination: '타이베이 · 대만',
    country: '대만',
    desc: '시먼딩 도보권 스마트 호텔. 위치 평점 9.3, 24시간 라운지에서 밤 작업까지.',
    cta: '실시간 요금 확인',
    rating: '8.7',
    ratingAsOf: '2026-08-06',
    reviews: '2,458',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.booking.com/hotel/tw/citizenm-taipei-north-gate.html?aid=7854081',
    badge: '스마트 호텔',
    trackingId: 'aid=7854081',
    coverPhoto: '/media/product-editorial/city-highrise-apartment-editorial-v1.webp', illustrative: true,
  },
]

// ── 지역별 에디터픽 보강 (17종) ──
// Booking 슬러그 실존 확인 + aid=7854081 추적. 자체 제작 커버의 출처와 사용 범위는
// 미디어 자산 매니페스트에서 관리하며 실제 숙소 사진으로 단정하지 않는다.

export const FEATURED_STAYS_V3: AffiliateItem[] = [
  // 일본 (+1)
  {
    id: 'stay-mimaru-tokyo', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '미마루 도쿄 우에노 이스트', destination: '도쿄 · 일본', country: '일본',
    desc: '주방·업무 데스크 완비 아파트형 객실. 우에노역 도보권, 장기체류 최적.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/jp/mimaru-tokyo-ueno-east.html?aid=7854081',
    rating: '8.8',
    ratingAsOf: '2026-08-06',
    reviews: '1,086',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '주방·데스크', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/japanese-apartment-editorial-v1.webp', illustrative: true,
  },
  // 한국 (+3)
  {
    id: 'stay-fraser-seoul', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '프레이저 플레이스 센트럴 서울', destination: '서울 · 국내', country: '국내',
    desc: '주방·세탁 갖춘 서비스드 레지던스. 헬스장·수영장 완비 도심 장기체류.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/kr/fraser-place-central-seoul.html?aid=7854081',
    rating: '8.9',
    ratingAsOf: '2026-08-06',
    reviews: '3,452',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '서비스드 레지던스', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/bright-loft-workspace-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-uh-busan', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🌊', productTitle: '유에이치 스위트 더 해운대', destination: '부산 해운대 · 국내', country: '국내',
    desc: '해운대 해변 도보 2분, 주방·발코니 갖춘 오션뷰 레지던스.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/kr/uh-suite-the-haeundae-busan.html?aid=7854081',
    rating: '7.8',
    ratingAsOf: '2026-08-06',
    reviews: '423',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '오션뷰', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/oceanview-balcony-desk-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-skybay-gangneung', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏖', productTitle: '스카이베이 호텔 경포', destination: '강릉 경포 · 국내', country: '국내',
    desc: '경포해변·경포호 인근, 전 객실 발코니 오션·레이크뷰. 20층 인피니티풀.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/kr/golden-tulip-skybay-gyeongpo.html?aid=7854081',
    rating: '8.2',
    ratingAsOf: '2026-08-06',
    reviews: '2,200',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '오션뷰 풀', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/coastal-apartment-editorial-v1.webp', illustrative: true,
  },
  // 태국 (+2)
  {
    id: 'stay-shama-bangkok', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '샤마 수쿰빗 방콕', destination: '방콕 수쿰빗 · 태국', country: '태국',
    desc: '주방 완비 서비스드 아파트. 인피니티풀·헬스장, BTS 접근 좋은 장기체류.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/th/shama-sukhumvit-serviced-apartment.html?aid=7854081',
    rating: '8.8',
    ratingAsOf: '2026-08-06',
    reviews: '604',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '서비스드 아파트', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/serviced-apartment-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-naka-phuket', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏝', productTitle: '나카 레지던스', destination: '푸켓 타운 · 태국', country: '태국',
    desc: '푸켓 타운 넓은 아파트형 객실. 무료 와이파이·주차, 장기체류 가성비.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/th/naka-residence.html?aid=7854081',
    rating: '8.7',
    ratingAsOf: '2026-08-06',
    reviews: '128',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '장기체류', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/tropical-boutique-room-editorial-v1.webp', illustrative: true,
  },
  // 베트남 (+3)
  {
    id: 'stay-sanouva-danang', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '사노우바 다낭 호텔', destination: '다낭 하이쩌우 · 베트남', country: '베트남',
    desc: '하이쩌우 도심 비즈니스 호텔. 무료 와이파이·피트니스로 업무 여행 편리.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/vn/sanouva-da-nang.html?aid=7854081',
    rating: '8.8',
    ratingAsOf: '2026-08-06',
    reviews: '718',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '도심 비즈니스', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/tropical-pool-villa-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-seaside-nhatrang', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🌊', productTitle: '씨사이드 부티크 호텔 나트랑 비치', destination: '나트랑 · 베트남', country: '베트남',
    desc: '나트랑 해변 앞 부티크 호텔. 루프탑 수영장·오션뷰로 워케이션 무드.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/vn/seaside-nha-trang.html?aid=7854081',
    rating: '9.0',
    ratingAsOf: '2026-08-06',
    reviews: '550',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '오션뷰', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/coastal-residence-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-dhts-hcmc', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: 'DHTS 비즈니스 호텔 앤 아파트먼트', destination: '호치민 · 베트남', country: '베트남',
    desc: '루프탑 수영장 갖춘 아파트형 비즈니스 호텔. 무료 와이파이·피트니스.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/vn/dhts-business-apartment.html?aid=7854081',
    rating: '9.2',
    ratingAsOf: '2026-08-06',
    reviews: '529',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '아파트형', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/serviced-apartment-editorial-v1.webp', illustrative: true,
  },
  // 인도네시아 (+3)
  {
    id: 'stay-thenomad-canggu', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🌴', productTitle: '더노마드 짱구', destination: '발리 짱구 · 인도네시아', country: '인도네시아',
    desc: '디지털 노마드 콘셉트 코리빙. 짱구 중심가에서 일과 휴식을 동시에.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/id/thenomad-canggu.html?aid=7854081',
    rating: '9.2',
    ratingAsOf: '2026-08-06',
    reviews: '32',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '노마드 코리빙', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/tropical-coliving-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-ubud-village', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🌾', productTitle: '더 우붓 빌리지 리조트 앤 스파', destination: '발리 우붓 · 인도네시아', country: '인도네시아',
    desc: '라이스필드에 둘러싸인 프라이빗 풀 빌라. 장기 체류형 힐링 워케이션.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/id/the-ubud-village-resort.html?aid=7854081',
    rating: '9.2',
    ratingAsOf: '2026-08-06',
    reviews: '560',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '풀 빌라', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/tropical-boutique-room-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-fields-seminyak', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏝', productTitle: '더 필즈 호텔 앤 아파트먼트', destination: '발리 스미냑 · 인도네시아', country: '인도네시아',
    desc: '주방·데스크 갖춘 아파트형 객실. 조용한 스미냑에서 장기 워케이션.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/id/the-fields-apartment.html?aid=7854081',
    rating: '8.9',
    ratingAsOf: '2026-08-06',
    reviews: '36',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '아파트형', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/mediterranean-room-editorial-v1.webp', illustrative: true,
  },
  // 아시아 (+2)
  {
    id: 'stay-lyf-funan-singapore', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '리프 후난 싱가포르', destination: '싱가포르 시티홀', country: '싱가포르',
    desc: '아시아 최대 코리빙. 코워킹 라운지·공용주방 갖춘 시티홀 도심 입지.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/sg/lyf-funan.html?aid=7854081',
    rating: '8.4',
    ratingAsOf: '2026-08-06',
    reviews: '8,529',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '코워킹 내장', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/coliving-work-lounge-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-gloria-taipei', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '글로리아 레지던스', destination: '타이베이 · 대만', country: '대만',
    desc: '키치넷 갖춘 넓은 서비스드 아파트. 실내수영장, 타이베이역 접근 장기체류.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/tw/gloria-residence.html?aid=7854081',
    rating: '9.0',
    ratingAsOf: '2026-08-06',
    reviews: '370',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '서비스드 아파트', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/city-dusk-lounge-editorial-v1.webp', illustrative: true,
  },
  // 오세아니아 (+3)
  {
    id: 'stay-meriton-kent-sydney', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '메리톤 스위트 켄트 스트리트', destination: '시드니 CBD · 호주', country: '호주',
    desc: 'CBD 중심 풀키친 서비스드 아파트. 실내수영장·헬스장 갖춘 장기체류.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/au/meriton-serviced-apartment-kent-street.html?aid=7854081',
    rating: '8.4',
    ratingAsOf: '2026-08-06',
    reviews: '5,635',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '풀키친 아파트', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/bright-loft-workspace-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-adina-melbourne', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏙', productTitle: '아디나 아파트먼트 호텔 멜버른', destination: '멜버른 CBD · 호주', country: '호주',
    desc: 'CBD 자급형 아파트. 주방·세탁·무료 와이파이에 수영장·헬스장 완비.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/au/medina-grand-melbourne.html?aid=7854081',
    rating: '8.2',
    ratingAsOf: '2026-08-06',
    reviews: '2,164',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '아파트 호텔', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/accommodation-urban-studio-editorial-v1.webp', illustrative: true,
  },
  {
    id: 'stay-meriton-surfers-goldcoast', name: 'Booking.com', category: 'hotel', productType: 'stay', status: 'active_affiliate',
    emoji: '🏖', productTitle: '메리톤 스위트 서퍼스 파라다이스', destination: '골드코스트 · 호주', country: '호주',
    desc: '서퍼스 파라다이스 해변 앞 풀키친 스위트. 오션뷰 비치 워케이션.',
    cta: '실시간 요금 확인', href: 'https://www.booking.com/hotel/au/meriton-suites-surfers-paradise.html?aid=7854081',
    rating: '8.8',
    ratingAsOf: '2026-08-06',
    reviews: '9,873',
    sourceNote: 'Booking.com 게스트 평점·리뷰수 실브라우저 실측 (기준 2026-08-06)',
    badge: '오션뷰 스위트', trackingId: 'aid=7854081', coverPhoto: '/media/product-editorial/coastal-apartment-editorial-v1.webp', illustrative: true,
  },
]

// 테마 페이지용 체험 상품 (2026-07 리서치 검증 — KKday 실상품)
export const THEME_EXPERIENCES: AffiliateItem[] = [
  {
    id: 'theme-golf-montgomerie',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '⛳',
    productTitle: '다낭 몽고메리 링크스 티타임 예약',
    destination: '다낭 · 베트남',
    country: '베트남',
    desc: '베트남 대표 링크스 코스 라운딩. 워케이션 중 주말 골프의 정석.',
    cta: '티타임 보기',
    priceFrom: '₩174,500~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/162518?cid=25833',
    badge: '골프',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1535131749006-b7f58c99034b.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-golf-hoiana',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏌️',
    productTitle: '호이아나 골프 쇼어스 라운딩',
    destination: '호이안 · 베트남',
    country: '베트남',
    desc: '해안 절경의 호이아나 골프 쇼어스. 골프+휴양 워케이션 조합.',
    cta: '라운딩 예약',
    priceFrom: '₩14,891~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/136700?cid=25833',
    badge: '골프',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1587174486073-ae5e5cff23aa.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-heal-spa-ubud',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '💆',
    productTitle: '우붓 발리 전통 스파·마사지 예약',
    destination: '우붓 · 발리',
    country: '인도네시아',
    desc: '우붓 스파 전문점 "스까르 즈뿐"의 발리니즈 마사지. KKday에서 시간대를 골라 예약하고 방문하는 현지 스파 체험입니다.',
    cta: '스파 예약',
    priceFrom: '₩49,752~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/147558?cid=25833',
    badge: '힐링',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1544367567-0f2fcb009e0b.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    // 소멸한 KKday 발리 요가(162648)의 대체 — Klook 동일 성격 상품으로 교체 (2026-08-06)
    id: 'theme-heal-yoga-ubud',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🧘',
    productTitle: '우붓 요가 센터 요가 강습',
    destination: '우붓 · 발리',
    country: '인도네시아',
    desc: '우붓 요가 센터의 원데이 요가 강습. 업무 시작 전 아침 루틴으로 — Klook에서 날짜를 골라 예약합니다.',
    cta: '클래스 보기',
    rating: '4.7',
    ratingAsOf: '2026-08-06',
    reviews: '68',
    priceFrom: '₩14,200~',
    priceAsOf: '2026-08-06',
    sourceNote: 'Klook 검색 리스팅 실브라우저 실측 (기준 2026-08-06) — 평점·리뷰수·가격. 상품 상세는 봇 차단으로 직접 판독 불가',
    href: 'https://affiliate.klook.com/redirect?aid=126848&k_site=https%3A%2F%2Fwww.klook.com%2Fko%2Factivity%2F23956-yoga-class-ubud-centre-bali%2F',
    badge: '요가',
    trackingId: 'aid=126848',
    coverPhoto: '/media/verified/unsplash/1506126613408-eca07ce68773.webp', illustrative: true,
    operatorAction: 'Klook aid=126848 공식 리다이렉트 적용 (2026-08-06)',
  },
  {
    id: 'theme-heal-yoga-bali',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    // ⚠️ 2026-08-06 재실측: KKday 상품 162648이 소멸(404 — 상품 페이지 대신 추천 목록 렌더).
    // 죽은 링크를 노출하지 않도록 coming_soon으로 자동 미노출 처리하고, 근거 없는
    // 가격(₩21,332)은 제거했다. 힐링 테마가 4→3장이 되므로 대체 상품 등재 필요
    // (KKday 검색 결과는 대부분 숙소라 '힐링 체험' 성격에 부적합 — 운영자 판단 대기)
    status: 'coming_soon',
    emoji: '🧘',
    productTitle: '발리 아침 요가 원데이 클래스',
    destination: '발리 · 인도네시아',
    country: '인도네시아',
    desc: '발리 현지 요가 스튜디오의 아침 클래스 예약. 업무 시작 전 명상·스트레칭 루틴으로 — KKday에서 날짜 선택.',
    cta: '클래스 보기',
    sourceNote: 'KKday 상품 소멸 확인 (2026-08-06 재실측) — 대체 상품 등재 전까지 미노출',
    href: 'https://www.kkday.com/ko/product/162648?cid=25833',
    badge: '요가',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1506126613408-eca07ce68773.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-sports-tokyodome',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '⚾',
    productTitle: '도쿄돔 요미우리 자이언츠 티켓',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '일본 야구의 성지 도쿄돔 홈경기. 퇴근 후 직관하는 워케이션 저녁.',
    cta: '티켓 보기',
    priceFrom: '₩130,643~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/21633?cid=25833',
    badge: '야구 직관',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1459865264687-595d652de67e.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  // ── 2026-07-16 확충: 전 테마 4장 이상 (검색 인덱스 실존 확인, KKday cid / Klook aid) ──
  {
    id: 'theme-golf-alpine-chiangmai',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '⛳',
    productTitle: '치앙마이 알파인 골프 리조트 티타임',
    destination: '치앙마이 · 태국',
    country: '태국',
    desc: '치앙마이 대표 명문 알파인 GC 티타임 간편예약. 오전 라운딩 후 오후 업무 루틴에.',
    cta: '티타임 보기',
    priceFrom: '₩172,300~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/155736?cid=25833',
    badge: '골프',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1512553353614-82a7370096dc.webp', illustrative: true,
  },
  {
    id: 'theme-golf-pattaya-cc',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏌️',
    productTitle: '파타야 컨트리클럽 티타임 예약',
    destination: '파타야 · 태국',
    country: '태국',
    desc: '방콕 근교 파타야 CC 티타임 간편예약. 방콕 워케이션의 주말 골프 코스.',
    cta: '티타임 보기',
    priceFrom: '₩111,200~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/155844?cid=25833',
    badge: '골프',
    trackingId: 'cid=25833',
    coverPhoto: '/covers/golf-pattaya-real-v2.jpeg', illustrative: true,
    coverGradient: 'from-emerald-900 via-green-950 to-[#0d0d0d]',
  },
  {
    id: 'theme-heal-oasis-chiangmai',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🌿',
    productTitle: '치앙마이 오아시스 스파 마사지',
    destination: '치앙마이 · 태국',
    country: '태국',
    desc: '치앙마이의 대표 럭셔리 스파 브랜드 오아시스. 타이 마사지로 업무 후 회복 — KKday 예약.',
    cta: '스파 예약',
    priceFrom: '₩29,606~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/123986?cid=25833',
    badge: '힐링',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1512553353614-82a7370096dc.webp', illustrative: true,
  },
  {
    id: 'theme-heal-forest-danang',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🌳',
    productTitle: '다낭 포레스트 스파 마사지',
    destination: '다낭 · 베트남',
    country: '베트남',
    desc: '다낭 시내 스파 마사지 예약(직접 예약 시 무료 픽업 옵션). 노마드의 저녁 회복 코스.',
    cta: '스파 예약',
    href: 'https://www.kkday.com/ko/product/154790?cid=25833',
    badge: '힐링',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1559592413-7cec4d0cae2b.webp', illustrative: true,
  },
  {
    id: 'theme-sports-seoul-baseball',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '⚾',
    productTitle: '서울 야구 직관 — 현지인과 관람+경기 전 식사',
    destination: '서울 · 한국',
    country: '한국',
    desc: '잠실 야구장에서 가이드와 함께하는 직관 패키지. 국내 워케이션의 저녁 이벤트로.',
    cta: '티켓 보기',
    priceFrom: '₩97,777~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/576749?cid=25833',
    badge: '야구 직관',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1517154421773-0529f29ea451.webp', illustrative: true,
  },
  {
    id: 'theme-sports-tottenham',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '⚽',
    productTitle: '토트넘 홋스퍼 프리미어리그 경기 티켓',
    destination: '런던 · 영국',
    country: '영국',
    desc: '토트넘 홈구장 PL 직관 티켓. 유럽 워케이션의 버킷리스트 — Klook 예약.',
    cta: '티켓 보기',
    rating: '4.2',
    ratingAsOf: '2026-08-06',
    reviews: '183',
    priceFrom: '₩172,400~',
    priceAsOf: '2026-08-06',
    sourceNote: 'Klook 상품 JSON-LD 평점·리뷰 실측 (기준 2026-08-06) — 평점·리뷰수·가격',
    href: 'https://www.klook.com/ko/activity/81238-tottenham-hotspur-premier-league-football-ticket-london/?aid=126848',
    badge: '축구 직관',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/sports-tottenham-real-v2.jpeg', illustrative: true,
    coverGradient: 'from-indigo-900 via-blue-950 to-[#0d0d0d]',
  },
  {
    id: 'theme-local-izakaya-kyoto',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏮',
    productTitle: '교토 이자카야 먹거리 프라이빗 반나절 투어',
    destination: '교토 · 일본',
    country: '일본',
    desc: '현지인처럼 먹고 마시는 교토 이자카야 프라이빗 투어. 니시키 시장부터 골목 술집까지.',
    cta: '투어 보기',
    priceFrom: '₩366,300~',
    priceAsOf: '2026-08-06',
    sourceNote: 'Klook 검색 리스팅 실브라우저 실측 (기준 2026-08-06) — 가격 (리뷰 표본 과소로 평점 미표기)',
    href: 'https://www.klook.com/ko/activity/45658-kyoto-eat-drink-like-a-local-izakaya-experience/?aid=126848',
    badge: '미식',
    trackingId: 'aid=126848',
    coverPhoto: '/covers/local-izakaya-kyoto-real-v2.jpeg', illustrative: true,
    coverGradient: 'from-amber-900 via-orange-950 to-[#0d0d0d]',
  },

  // ── 2026-07-15 확충: 1장짜리 섹션 해소 (Klook 검색 인덱스 실존 확인 + aid=126848) ──
  {
    id: 'theme-local-nishiki',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🐟',
    productTitle: '교토 니시키 시장 도보 푸드투어 (3시간)',
    destination: '교토 · 일본',
    country: '일본',
    desc: '"교토의 부엌" 니시키 시장을 가이드와 함께 3시간 시식하며 걷는 조인 투어 — Klook 예약.',
    cta: '투어 보기',
    href: 'https://www.klook.com/ko/activity/102480-nishiki-market-join-3-hr-walking-tour-kyoto-food-tour/?aid=126848',
    badge: '미식',
    trackingId: 'aid=126848',
    coverPhoto: '/media/verified/unsplash/1545569341-9eb8b30979d9.webp', illustrative: true,
  },
  {
    id: 'theme-local-gion-food',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🍢',
    rating: '4.9',
    ratingAsOf: '2026-08-06',
    reviews: '139',
    productTitle: '교토 기온 맛집 투어 — 4곳 13가지 요리',
    destination: '교토 · 일본',
    country: '일본',
    desc: '기온의 식당 4곳을 돌며 13가지 요리를 맛보는 저녁 미식 투어. 퇴근 후 로컬의 밤 — Klook 예약.',
    cta: '투어 보기',
    priceFrom: '₩85,800~',
    priceAsOf: '2026-08-06',
    sourceNote: 'Klook 상품 페이지 meta(product:price) 실측 (기준 2026-08-06) — 리뷰 없어 평점 미표기',
    href: 'https://www.klook.com/ko/activity/159777-kyoto-gion-food-tour-with-13-dishes-at-4-eateries/?aid=126848',
    badge: '미식',
    trackingId: 'aid=126848',
    coverPhoto: '/media/verified/unsplash/1493780474015-ba834fd0ce2f.webp', illustrative: true,
  },
  {
    id: 'theme-sports-sumo-osaka',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🤼',
    productTitle: '오사카 그랜드 스모 토너먼트 관람 (티켓 포함)',
    destination: '오사카 · 일본',
    country: '일본',
    desc: '스모 대회 관람석 티켓 + 가이드 워킹투어가 묶인 반나절 상품. 일본에서만 가능한 직관 — Klook 예약.',
    cta: '티켓 보기',
    href: 'https://www.klook.com/ko/activity/105524-osaka-city-osaka-grand-sumo-tournament-viewing-half-day-walking-tour/?aid=126848',
    badge: '직관',
    trackingId: 'aid=126848',
    coverPhoto: '/media/verified/unsplash/1590559899731-a382839e5549.webp', illustrative: true,
  },
  {
    id: 'theme-local-kuromon',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🍜',
    productTitle: '오사카 구로몬 시장 푸드투어',
    destination: '오사카 · 일본',
    country: '일본',
    desc: '오사카의 부엌 구로몬 시장을 미식가처럼. 점심시간 1시간 로컬 탐방.',
    cta: '투어 보기',
    priceFrom: '₩88,296~',
    priceAsOf: '2026-08-06',
    sourceNote: 'KKday 상품 페이지 가격 실브라우저 실측 (기준 2026-08-06)',
    href: 'https://www.kkday.com/ko/product/266918?cid=25833',
    badge: '미식',
    trackingId: 'cid=25833',
    coverPhoto: '/media/verified/unsplash/1414235077428-338989a2e8c0.webp', illustrative: true,
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
]

