import type { AffiliateItem } from './types'

// ─────────────────────────────────────────────────────────────────────────────
// 에디터 추천 개별 상품 — 실존 검증된 대표 상품 (2026-07 웹 리서치)
//
// 숙소: Booking.com 상세 페이지 직결 (aid=7854081, rel=sponsored 수익 추적)
// 체험: KKday 실제 상품 페이지 (파트너 딥링크 수령 시 href 교체 → active_affiliate)
//
// ⚠️ 상품 추가/교체 시: 반드시 실존 확인(검색) 후 등록. localize.ts에 EN/JP도 추가.
// ─────────────────────────────────────────────────────────────────────────────

const B = (path: string) => `https://www.booking.com/hotel/${path}?aid=7854081`

export const FEATURED_STAYS: AffiliateItem[] = [
  {
    id: 'stay-millennials-shibuya',
    rating: '8.7',
    reviews: '2,005',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏨',
    productTitle: '더 밀레니얼스 시부야',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '호텔 안에 코워킹 .andwork 2개 층. 시부야역 도보 6분, 무료 커피와 해피아워까지.',
    cta: '실시간 요금 확인',
    href: B('jp/the-millennials-shibuya-shibuya-ku.html'),
    badge: '코워킹 내장',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-lively-osaka',
    rating: '8.7',
    reviews: '2,657',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏨',
    productTitle: '더 라이블리 오사카 혼마치',
    destination: '오사카 · 일본',
    country: '일본',
    desc: '작업 가능한 공용 라운지 7곳. 혼마치 비즈니스 지구, 평점 8.7 (2,600+ 리뷰).',
    cta: '실시간 요금 확인',
    href: B('jp/the-lively-osaka.html'),
    badge: '라운지 워크',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-webase-hakata',
    rating: '8.6',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏨',
    productTitle: '위베이스 하카타',
    destination: '후쿠오카 · 일본',
    country: '일본',
    desc: '9층 전용 코워킹(투숙객 무료) + 테라스. 나카스카와바타역 도보 3분, 평점 8.6.',
    cta: '실시간 요금 확인',
    href: B('jp/webase-hakata-hostel.html'),
    badge: '무료 코워킹',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-tribal-bali',
    rating: '8.9',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🌴',
    productTitle: '트라이벌 코워킹 발리',
    destination: '발리 짱구 · 인도네시아',
    country: '인도네시아',
    desc: '발리 최초 코워킹 전용 설계 숙소. 풀사이드 워크스페이스와 노마드 커뮤니티.',
    cta: '실시간 요금 확인',
    href: B('id/tribal-bali-mengwi.html'),
    badge: '노마드 성지',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-chicland-danang',
    rating: '8.6',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏖',
    productTitle: '시클랜드 다낭 비치 호텔',
    destination: '다낭 · 베트남',
    country: '베트남',
    desc: '미케비치 도보 2분, 카페형 라운지와 루프탑 풀. 노마드 거점 안트엉 인근, 평점 8.6.',
    cta: '실시간 요금 확인',
    href: B('vn/chicland-da-nang.html'),
    badge: '비치 워크',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-playce-jeju',
    rating: '8.1',
    reviews: '246',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🍊',
    productTitle: '플레이스캠프 제주',
    destination: '제주 성산 · 국내',
    country: '국내',
    desc: '침실과 업무 데스크 분리형 객실, 워케이션 전용 패키지 운영. 성산 일출봉 인근.',
    cta: '실시간 요금 확인',
    href: B('kr/playce-camp-jeju.html'),
    badge: '워케이션 특화',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-kantary-chiangmai',
    rating: '8.9',
    reviews: '207',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏙',
    productTitle: '칸타리 힐스 치앙마이',
    destination: '치앙마이 님만 · 태국',
    country: '태국',
    desc: '키치넷 딸린 서비스드 아파트, 장기 체류 특화. 마야몰·원님만 도보권.',
    cta: '실시간 요금 확인',
    href: B('th/kantary-hills-chiang-mai.html'),
    badge: '장기체류',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1512553353614-82a7370096dc?auto=format&fit=crop&w=700&q=80',
  },
]

export const FEATURED_ACTIVITIES: AffiliateItem[] = [
  {
    id: 'act-tokyo-disney',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🎡',
    productTitle: '도쿄 디즈니랜드·디즈니씨 티켓',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '모바일 QR로 즉시 입장하는 1일권. 워케이션 주말을 특별하게.',
    cta: '상품 보기',
    href: 'https://www.kkday.com/ko/product/19252?cid=25833',
    badge: '인기 체험',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-osaka-usj',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🎢',
    productTitle: '유니버설 스튜디오 재팬 입장권',
    destination: '오사카 · 일본',
    country: '일본',
    desc: 'USJ 1일권 + 익스프레스 패스 옵션. 줄 서지 않는 오사카 주말.',
    cta: '상품 보기',
    href: 'https://www.kkday.com/ko/product/20944?cid=25833',
    badge: '익스프레스',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-fukuoka-bustour',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🚌',
    productTitle: '후쿠오카 근교 버스투어 (한국어)',
    destination: '후쿠오카 · 일본',
    country: '일본',
    desc: '다자이후·유후인·벳부 일일투어. 하카타역 출발, 한국인 가이드 동행.',
    cta: '상품 보기',
    href: 'https://www.kkday.com/ko/product/134297?cid=25833',
    badge: '한국어 가이드',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-bali-ubud',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🌾',
    productTitle: '발리 우붓 프라이빗 투어 (한국어)',
    destination: '발리 · 인도네시아',
    country: '인도네시아',
    desc: '사원·라이스테라스 반나절 맞춤 프라이빗. 원하는 코스로 자유롭게.',
    cta: '상품 보기',
    href: 'https://www.kkday.com/ko/product/141520?cid=25833',
    badge: '프라이빗',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'act-danang-banahills',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🌉',
    productTitle: '다낭 바나힐 단독투어 (한국어)',
    destination: '다낭 · 베트남',
    country: '베트남',
    desc: '골든브릿지 포함, 입장권·중식·픽업까지. 단독 차량 일일투어.',
    cta: '상품 보기',
    href: 'https://www.kkday.com/ko/product/129472?cid=25833',
    badge: '올인클루시브',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },

  // ── Klook 6종 (2026-07-15) — aid=126848 부착
  // 상품 실존: klook.com 자체 검색 인덱스로 확인. aid 파라미터 형식: 실제 유통 중인
  // Klook 어필리에이트 URL 2건(aid=15027, aid=11271)에서 실물 확인
  // ⚠️ 대시보드에서 계정 승인·클릭 집계 확인 필요 (미승인이면 링크는 열리되 커미션 미집계)
  {
    id: 'act-klook-teamlab-tokyo',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🪐',
    productTitle: '팀랩 플래닛 도쿄 티켓',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '도요스의 몰입형 미디어아트. 물에 발을 담그고 걷는 전시 — 저녁 시간대 추천.',
    cta: '상품 보기',
    href: 'https://www.klook.com/ko/activity/25300-teamlab-planets-toyosu-tokyo-ticket/?aid=126848',
    badge: '인기 체험',
    trackingId: 'aid=126848',
    coverPhoto: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
  },
  {
    id: 'act-klook-osaka-pass',
    name: 'Klook',
    category: 'activity',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '🎫',
    productTitle: '오사카 주유패스',
    destination: '오사카 · 일본',
    country: '일본',
    desc: '지하철·버스 무제한 + 우메다 공중정원 등 40여 곳 입장. 오사카 워케이션 주말 필수템.',
    cta: '패스 보기',
    href: 'https://www.klook.com/ko/activity/82312-amazing-pass-osaka/?aid=126848',
    badge: '교통+입장',
    trackingId: 'aid=126848',
    coverPhoto: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
  },
  {
    id: 'act-klook-taipei-tour',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏮',
    productTitle: '예류·지우펀·스펀 일일투어 (한국어 가이드)',
    destination: '타이베이 · 대만',
    country: '대만',
    desc: '타이베이 근교 3대 명소를 하루에. 스펀 천등 날리기 포함, 한국어 가이드 동행.',
    cta: '투어 보기',
    href: 'https://www.klook.com/ko/activity/3521-jiufen-full-day-tour-taipei/?aid=126848',
    badge: '한국어 가이드',
    trackingId: 'aid=126848',
    coverPhoto: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
  },
  {
    id: 'act-klook-uss-singapore',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🎢',
    productTitle: '유니버설 스튜디오 싱가포르 티켓',
    destination: '싱가포르',
    country: '싱가포르',
    desc: '센토사의 7개 테마존. 싱가포르 워케이션 주말을 채우는 정석 코스.',
    cta: '티켓 보기',
    href: 'https://www.klook.com/ko/activity/117-universal-studios-singapore/?aid=126848',
    badge: '인기 체험',
    trackingId: 'aid=126848',
    coverPhoto: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
  },
  {
    id: 'act-klook-nusapenida-bali',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏝',
    productTitle: '발리 누사페니다 일일투어',
    destination: '발리 · 인도네시아',
    country: '인도네시아',
    desc: '켈링킹 절벽·브로큰 비치·크리스탈 베이. 발리에서 꼭 한 번은 가는 섬.',
    cta: '투어 보기',
    href: 'https://www.klook.com/ko/activity/15758-nusa-penida-full-day-trip-bali/?aid=126848',
    badge: '베스트 투어',
    trackingId: 'aid=126848',
    coverPhoto: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
  },
  {
    id: 'act-klook-elephant-chiangmai',
    name: 'Klook',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🐘',
    productTitle: '치앙마이 코끼리 정글 생추어리',
    destination: '치앙마이 · 태국',
    country: '태국',
    desc: '타지 않고 돌보는 윤리적 코끼리 체험 — Klook 동물복지 심사 통과 상품.',
    cta: '체험 보기',
    href: 'https://www.klook.com/ko/activity/3631-elephant-jungle-sanctuary-chiang-mai/?aid=126848',
    badge: '동물복지 인증',
    trackingId: 'aid=126848',
    coverPhoto: 'https://images.unsplash.com/photo-1512553353614-82a7370096dc?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'Klook 대시보드에서 승인 상태·클릭 집계 확인',
  },
]

// eSIM 실상품 — Klook (2026-07-15, 검색 인덱스 실존 확인 + aid=126848)
// Airalo(Impact)와 병행 — 사용자에게 선택지, 우리에겐 이중 수익 채널
export const FEATURED_ESIM: AffiliateItem[] = [
  {
    id: 'esim-klook-japan',
    name: 'Klook',
    category: 'esim',
    productType: 'esim',
    status: 'active_affiliate',
    emoji: '🇯🇵',
    productTitle: '일본 eSIM (DOCOMO·Softbank)',
    destination: '일본',
    country: '일본',
    desc: 'QR 코드로 5분 개통. 무제한·일별 플랜, 현지 통신사 회선이라 속도가 안정적.',
    cta: 'eSIM 보기',
    href: 'https://www.klook.com/ko/activity/109393-japan-esim-high-speed-internet-qr-code-voucher/?aid=126848',
    badge: '일본 특화',
    trackingId: 'aid=126848',
    coverGradient: 'from-red-900 via-rose-950 to-[#0d0d0d]',
  },
  {
    id: 'esim-klook-asia',
    name: 'Klook',
    category: 'esim',
    productType: 'esim',
    status: 'active_affiliate',
    emoji: '🌏',
    productTitle: '아시아 30+개국 eSIM',
    destination: '아시아 멀티국',
    country: '200개국',
    desc: '일본·태국·베트남·대만을 eSIM 하나로. 여러 나라를 도는 워케이션 루트에.',
    cta: 'eSIM 보기',
    href: 'https://www.klook.com/ko/activity/121525-asia-pacific-esim-high-speed-internet-qr-code-in-the-voucher/?aid=126848',
    badge: '멀티국',
    trackingId: 'aid=126848',
    coverGradient: 'from-sky-900 via-blue-950 to-[#0d0d0d]',
  },
]

export const FEATURED_CRUISES: AffiliateItem[] = [
  {
    id: 'cruise-rci-singapore',
    name: 'Trip.com',
    category: 'transport',
    productType: 'transport',
    status: 'active_affiliate',
    emoji: '🚢',
    productTitle: '로얄캐리비안 내비게이터 · 싱가포르 3박4일',
    destination: '싱가포르 → 페낭',
    country: '싱가포르',
    desc: '싱가포르 출항, 페낭 기항 3박4일. 선상 Wi-Fi로 일하며 이동하는 크루즈 워케이션 입문 코스.',
    cta: '요금 보기',
    href: 'https://kr.trip.com/cruises/line-140351-singapore-greater-china-3night-navigator-of-the-seas-rci/?departure=2027-02-01&locale=ko-KR&Allianceid=9024807',
    badge: '수익 추적',
    trackingId: 'Allianceid=9024807',
    coverPhoto: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'cruise-msc-bellissima-busan',
    name: 'MSC크루즈',
    category: 'transport',
    productType: 'transport',
    status: 'public_external_link',
    emoji: '🛳',
    productTitle: 'MSC 벨리시마 · 부산 출도착 한일 크루즈',
    destination: '부산 → 후쿠오카·사세보',
    country: '국내 출발',
    desc: '부산에서 타고 부산으로 돌아오는 4박5일. 비행기 없이 시작하는 크루즈 워케이션.',
    cta: '일정 보기',
    href: 'https://www.msccruises.co.kr/bbs/board.php?bo_table=p1&wr_id=68',
    badge: '부산 출항',
    trackingId: '',
    coverPhoto: 'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'MSC 제휴 프로그램 검토 → 제휴 시 tracking URL 교체',
  },
  {
    id: 'cruise-panstar-osaka',
    name: '팬스타크루즈',
    category: 'transport',
    productType: 'transport',
    status: 'public_external_link',
    emoji: '⛴',
    productTitle: '팬스타크루즈 · 부산-오사카 4박5일',
    destination: '부산 ↔ 오사카',
    country: '국내 출발',
    desc: '크루즈+오사카 호텔+선내식 포함 패키지. 가장 부담 없는 첫 크루즈 워케이션.',
    cta: '팬스타 홈에서 보기',
    // 기존 상품 상세 URL이 외부 사이트로 리다이렉트되어 사망(2026-07-15 확인) → 공식 메인으로 교체
    href: 'https://panstar-cruise.com/web/html/00_main/',
    badge: '가성비',
    trackingId: '',
    coverPhoto: 'https://images.unsplash.com/photo-1617653202545-931490e8d7e7?auto=format&fit=crop&w=700&q=80',
    operatorAction: '팬스타 제휴 문의 → 제휴 시 tracking URL 교체 (상품 상세 URL은 시즌마다 변동 — 메인 링크 유지 권장)',
  },
  {
    id: 'cruise-costa-serena-busan',
    name: '마이크루즈북',
    category: 'transport',
    productType: 'transport',
    status: 'public_external_link',
    emoji: '🌏',
    productTitle: '코스타 세레나 · 부산발 대만·일본 5박6일',
    destination: '부산 → 나가사키·기륭',
    country: '국내 출발',
    desc: '부산 출항, 나가사키·대만 기륭 기항. 8월 말 출항하는 본격 국제 크루즈.',
    cta: '일정 보기',
    href: 'https://www.mycruisebook.com/shop_view/?idx=224',
    badge: '8월 출항',
    trackingId: '',
    coverPhoto: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=700&q=80',
    operatorAction: '판매처 제휴 문의 → 제휴 시 tracking URL 교체',
  },
]

export const FEATURED_COURSES: AffiliateItem[] = [
  {
    id: 'course-gpts-automation',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '🤖',
    productTitle: '직장인을 위한 GPTs 업무 자동화',
    destination: 'AI · 자동화',
    desc: '반복 업무를 GPTs로 자동화. 워케이션 중 업무 시간을 줄여주는 실전 강의.',
    cta: '강의 보기',
    priceFrom: '₩33,000',
    href: 'https://inf.run/zXusL',
    badge: '실무 AI',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&w=700&q=80',
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-15 리다이렉트 실물검증)',
  },
  {
    id: 'course-chatgpt-work',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '⚡',
    productTitle: 'ChatGPT 실무 100% 활용',
    destination: 'AI · 생산성',
    desc: '업무 속도를 10배 올리는 ChatGPT 활용법. 이동 시간에 듣기 좋은 구성.',
    cta: '강의 보기',
    priceFrom: '₩49,500',
    href: 'https://inf.run/4j6xb',
    badge: '베스트',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: 'https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=700&q=80',
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-15 리다이렉트 실물검증)',
  },
  {
    id: 'course-notion-master',
    name: '인프런',
    category: 'education',
    productType: 'education',
    // 파트너스 홍보링크 생성 불가 확인(2026-07-15) — 어필리에이트 미지원 강의, 공개 링크 유지
    status: 'public_external_link',
    emoji: '📝',
    productTitle: '노션(Notion) 완벽 활용법',
    destination: '생산성 · 노션',
    desc: '평점 4.8, 4만 명이 들은 무료 강의. 워케이션 업무 시스템의 시작점.',
    cta: '무료 수강',
    href: 'https://www.inflearn.com/course/%EB%85%B8%EC%85%98-notion-%ED%99%9C%EC%9A%A9',
    badge: '무료',
    trackingId: '',
    coverPhoto: 'https://images.unsplash.com/photo-1522199755839-a2bacb67c546?auto=format&fit=crop&w=700&q=80',
    operatorAction: '인프런 파트너스 링크 생성 → href 교체',
  },
  {
    id: 'course-instagram-marketing',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'active_affiliate',
    emoji: '📢',
    productTitle: '매출을 높이는 인스타그램 마케팅',
    destination: '마케팅 · SNS',
    desc: '1인 비즈니스의 매출을 만드는 인스타 실전 운영. 현지 콘텐츠로 바로 실습.',
    cta: '강의 보기',
    priceFrom: '₩55,000',
    href: 'https://inf.run/xTxcg',
    badge: '마케팅',
    trackingId: 'partners(utm_campaign=1771445)',
    coverPhoto: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=700&q=80',
    sourceNote: '인프런 파트너스 홍보 링크 적용 (2026-07-15 리다이렉트 실물검증)',
  },
  {
    id: 'course-biz-english-email',
    name: '인프런',
    category: 'education',
    productType: 'education',
    // 파트너스 홍보링크 생성 불가 확인(2026-07-15) — 어필리에이트 미지원 강의, 공개 링크 유지
    status: 'public_external_link',
    emoji: '✉️',
    productTitle: '통역사와 같이 쓰는 비즈니스 영어 이메일',
    destination: '언어 · 비즈니스',
    desc: '해외 파트너·클라이언트와 일하는 워케이셔너를 위한 영어 이메일 실전.',
    cta: '강의 보기',
    priceFrom: '₩138,600',
    href: 'https://www.inflearn.com/course/%ED%86%B5%EC%97%AD%EC%82%AC%EC%99%80-%EA%B0%99%EC%9D%B4%EC%93%B0%EB%8A%94-%EB%B9%84%EC%A6%88%EB%8B%88%EC%8A%A4-%EC%98%81%EC%96%B4-%EC%9D%B4%EB%A9%94%EC%9D%BC',
    badge: '비즈 영어',
    trackingId: '',
    coverPhoto: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=700&q=80',
  },

  // ── 2026-07-15 인기 강의 확충 (인프런 검색 인덱스로 실존 확인) ──
  // 운영자: 파트너스에서 홍보링크 생성 시도 → 되면 href 교체, 안 되면 public 전환
  {
    id: 'course-excel-python-auto',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'approved_needs_course_links',
    emoji: '📊',
    productTitle: '김대리님 이게 바로 업무 자동화입니다 (엑셀+파이썬)',
    destination: '자동화 · 엑셀',
    desc: '반복되는 엑셀 업무를 파이썬으로 자동화. 워케이션 업무 시간을 줄이는 대표 강의.',
    cta: '강의 보기',
    href: 'https://www.inflearn.com/course/%EA%B9%80%EB%8C%80%EB%A6%AC%EB%8B%98-%EC%97%85%EB%AC%B4-%EC%9E%90%EB%8F%99%ED%99%94-%EC%97%91%EC%85%80-%ED%8C%8C%EC%9D%B4%EC%8D%AC',
    badge: '업무 자동화',
    trackingId: '',
    coverGradient: 'from-emerald-900 via-teal-950 to-[#0d0d0d]',
    operatorAction: '인프런 파트너스에서 홍보 링크 생성 시도',
  },
  {
    id: 'course-chatgpt-python-part1',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'approved_needs_course_links',
    emoji: '🐍',
    productTitle: '모두를 위한 ChatGPT Part 1 — 업무자동화·파이썬 입문',
    destination: 'AI · 파이썬',
    desc: 'ChatGPT로 엑셀·PPT·크롤링을 자동화하며 파이썬을 시작하는 입문 강의.',
    cta: '강의 보기',
    href: 'https://www.inflearn.com/course/chatgpt-%EC%97%85%EB%AC%B4%EC%9E%90%EB%8F%99%ED%99%94-part1',
    badge: '입문 추천',
    trackingId: '',
    coverGradient: 'from-violet-900 via-purple-950 to-[#0d0d0d]',
    operatorAction: '인프런 파트너스에서 홍보 링크 생성 시도',
  },
  {
    id: 'course-premiere-basic',
    name: '인프런',
    category: 'education',
    productType: 'education',
    status: 'approved_needs_course_links',
    emoji: '🎬',
    productTitle: '왕초보도 하는 영상 편집 with 프리미어 프로',
    destination: '영상 · 콘텐츠',
    desc: '여행지 영상을 콘텐츠로. 워케이션 브이로그·쇼츠 제작의 첫걸음.',
    cta: '강의 보기',
    href: 'https://www.inflearn.com/course/%EC%99%95%EC%B4%88%EB%B3%B4-%EC%98%81%EC%83%81-%ED%8E%B8%EC%A7%91-%ED%94%84%EB%A1%9C%EB%AF%B8%EC%96%B4-%ED%94%84%EB%A1%9C',
    badge: '크리에이터',
    trackingId: '',
    coverGradient: 'from-rose-900 via-red-950 to-[#0d0d0d]',
    operatorAction: '인프런 파트너스에서 홍보 링크 생성 시도',
  },
]

// 신규 지역 추천 숙소 (2026-07 리서치 검증)
export const FEATURED_STAYS_V2: AffiliateItem[] = [
  {
    id: 'stay-adina-sydney',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🎭',
    productTitle: '아디나 아파트먼트 호텔 시드니 타운홀',
    destination: '시드니 · 호주',
    country: '호주',
    desc: 'CBD 중심 풀키친 아파트호텔. Town Hall역 도보 2분, 실내 수영장까지.',
    cta: '실시간 요금 확인',
    href: 'https://www.booking.com/hotel/au/adina-sydney.html?aid=7854081',
    badge: '풀키친',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-nomadshub-cebu',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🏝',
    productTitle: '노마즈 허브 코리빙 세부',
    destination: '세부 · 필리핀',
    country: '필리핀',
    desc: '세부 시티 중심 코워킹+코리빙. 핫데스크 포함, 노마드 커뮤니티의 거점.',
    cta: '실시간 요금 확인',
    href: 'https://www.booking.com/hotel/ph/nomad-39-s-hub.html?aid=7854081',
    badge: '코리빙',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1573790387438-4da905039392?auto=format&fit=crop&w=700&q=80',
  },
  // ── 2026-07-15 MD 확충 — 웹검색으로 Booking 슬러그 실존 검증 완료 ──
  {
    id: 'stay-lyf-sukhumvit-bangkok',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🛋',
    productTitle: '라이프 수쿰빗 8 방콕',
    destination: '방콕 · 태국',
    country: '태국',
    desc: '나나역 도보 3분 코리빙. 코워킹 스페이스·간이주방·루프탑 — 노마드 특화 설계.',
    cta: '실시간 요금 확인',
    href: 'https://www.booking.com/hotel/th/lyf-sukhumvit-8-bangkok.html?aid=7854081',
    badge: '코리빙',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'stay-citizenm-taipei',
    name: 'Booking.com',
    category: 'hotel',
    productType: 'stay',
    status: 'active_affiliate',
    emoji: '🚪',
    productTitle: '시티즌엠 타이베이 노스게이트',
    destination: '타이베이 · 대만',
    country: '대만',
    desc: '시먼딩 도보권 스마트 호텔. 위치 평점 9.3, 24시간 라운지에서 밤 작업까지.',
    cta: '실시간 요금 확인',
    href: 'https://www.booking.com/hotel/tw/citizenm-taipei-north-gate.html?aid=7854081',
    badge: '스마트 호텔',
    trackingId: 'aid=7854081',
    coverPhoto: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?auto=format&fit=crop&w=700&q=80',
  },
]

// 테마 페이지용 체험 상품 (2026-07 리서치 검증 — KKday 실상품)
export const THEME_EXPERIENCES: AffiliateItem[] = [
  {
    id: 'theme-golf-montgomerie',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '⛳',
    productTitle: '다낭 몽고메리 링크스 티타임 예약',
    destination: '다낭 · 베트남',
    country: '베트남',
    desc: '베트남 대표 링크스 코스 라운딩. 워케이션 중 주말 골프의 정석.',
    cta: '티타임 보기',
    href: 'https://www.kkday.com/ko/product/162518?cid=25833',
    badge: '골프',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-golf-hoiana',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🏌️',
    productTitle: '호이아나 골프 쇼어스 라운딩',
    destination: '호이안 · 베트남',
    country: '베트남',
    desc: '해안 절경의 호이아나 골프 쇼어스. 골프+휴양 워케이션 조합.',
    cta: '라운딩 예약',
    href: 'https://www.kkday.com/ko/product/136700?cid=25833',
    badge: '골프',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-heal-spa-ubud',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '💆',
    productTitle: '우붓 발리 전통 스파·마사지 예약',
    destination: '우붓 · 발리',
    country: '인도네시아',
    desc: '우붓 스파 전문점 "스까르 즈뿐"의 발리니즈 마사지. KKday에서 시간대를 골라 예약하고 방문하는 현지 스파 체험입니다.',
    cta: '스파 예약',
    href: 'https://www.kkday.com/ko/product/147558?cid=25833',
    badge: '힐링',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-heal-yoga-bali',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🧘',
    productTitle: '발리 아침 요가 원데이 클래스',
    destination: '발리 · 인도네시아',
    country: '인도네시아',
    desc: '발리 현지 요가 스튜디오의 아침 클래스 예약. 업무 시작 전 명상·스트레칭 루틴으로 — KKday에서 날짜 선택.',
    cta: '클래스 보기',
    href: 'https://www.kkday.com/ko/product/162648?cid=25833',
    badge: '요가',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-sports-tokyodome',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '⚾',
    productTitle: '도쿄돔 요미우리 자이언츠 티켓',
    destination: '도쿄 · 일본',
    country: '일본',
    desc: '일본 야구의 성지 도쿄돔 홈경기. 퇴근 후 직관하는 워케이션 저녁.',
    cta: '티켓 보기',
    href: 'https://www.kkday.com/ko/product/21633?cid=25833',
    badge: '야구 직관',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
  {
    id: 'theme-local-kuromon',
    name: 'KKday',
    category: 'activity',
    productType: 'activity',
    status: 'active_affiliate',
    emoji: '🍜',
    productTitle: '오사카 구로몬 시장 푸드투어',
    destination: '오사카 · 일본',
    country: '일본',
    desc: '오사카의 부엌 구로몬 시장을 미식가처럼. 점심시간 1시간 로컬 탐방.',
    cta: '투어 보기',
    href: 'https://www.kkday.com/ko/product/266918?cid=25833',
    badge: '미식',
    trackingId: 'cid=25833',
    coverPhoto: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=700&q=80',
    operatorAction: 'KKpartners cid=25833 적용 완료 (2026-07-09)',
  },
]

