import type { AffiliateItem } from './types'
import type { Lang } from '@/lib/i18n'

// ─────────────────────────────────────────────────────────────────────────────
// 제휴 상품 EN/JP 오버레이 — items.ts(KO 원본)를 건드리지 않고 표시 필드만 덮어씀
// 새 홈 피처드 상품 추가 시 여기에 EN/JP 항목도 함께 추가할 것
// ─────────────────────────────────────────────────────────────────────────────

type Overlay = Partial<Pick<AffiliateItem, 'name' | 'displayTitle' | 'productTitle' | 'destination' | 'desc' | 'cta' | 'badge'>>

const EN: Record<string, Overlay> = {
  'hotel-booking': {
    desc: 'Book stays worldwide — great for long stays, apartments and serviced residences.',
    cta: 'Book a stay',
    badge: 'Long stay',
  },
  'hotel-tripcom': {
    desc: 'Stays, flights and tours in one place. Search long-stay hotels by destination.',
    cta: 'Find stays',
    badge: 'Stay · Flight',
  },
  'activity-kkday': {
    desc: 'Local tours, activities, tickets and transit passes across Japan, Taiwan and SEA.',
    cta: 'Book activities',
    badge: 'Experiences',
  },
  'esim-airalo': {
    desc: 'Instant eSIM for 200+ countries. Install before you land — skip the SIM queue.',
    cta: 'Get an eSIM',
    badge: 'eSIM',
  },
  'edu-inflearn': {
    name: 'Inflearn',
    desc: 'IT, dev, design and business courses. Learn on the move, apply on arrival.',
    cta: 'Browse courses',
    badge: 'Online courses',
  },
  'insurance-safetywing': {
    desc: 'Monthly travel insurance for digital nomads and long-stayers — 188 countries covered.',
    cta: 'Explore coverage',
    badge: 'Travel insurance',
  },
  'hotel-booking-visa': {
    displayTitle: 'Flight & stay booking',
    desc: 'Get the flight and stay confirmations you need for visa applications.',
    cta: 'Book flight & stay',
    badge: 'Flight · Stay',
  },
  'esim-airalo-visa': {
    desc: 'Install before your visa arrives — data connects the moment you land. 200+ countries.',
    cta: 'Get an eSIM',
    badge: 'eSIM',
  },
  'hotel-booking-market': {
    desc: 'Local hotels and apartments — long-stay options for research trips.',
    cta: 'Book a stay',
    badge: 'Long stay',
  },
  'hotel-booking-domestic': {
    desc: 'Find stays in Yangyang, Gangneung, Jeju and more — before or after your program dates.',
    cta: 'Search Korea stays',
    badge: 'Korea stays',
  },
  'activity-kkday-domestic': {
    desc: 'Local tours and tickets across Gangwon, Busan and Jeju — fill your workation evenings and weekends.',
    cta: 'See Korea experiences',
    badge: 'Korea experiences',
  },
  'feat-flight-tripcom': {
    productTitle: 'Compare & book flights',
    destination: 'All routes from Seoul',
    desc: 'Compare fares by airline for workation destinations. One-way, round-trip and multi-city.',
    cta: 'Compare flights',
    badge: 'Flights',
  },
  'stay-millennials-shibuya': {
    productTitle: 'The Millennials Shibuya',
    destination: 'Tokyo · Japan',
    desc: 'Two floors of .andwork coworking inside the hotel. 6 min from Shibuya station, free coffee and happy hour.',
    cta: 'See rooms', badge: 'Built-in coworking',
  },
  'stay-lively-osaka': {
    productTitle: 'The Lively Osaka Honmachi',
    destination: 'Osaka · Japan',
    desc: 'Seven work-friendly lounges in the Honmachi business district. Rated 8.7 by 2,600+ guests.',
    cta: 'See rooms', badge: 'Lounge work',
  },
  'stay-webase-hakata': {
    productTitle: 'WeBase Hakata',
    destination: 'Fukuoka · Japan',
    desc: 'Free 9th-floor coworking space with terrace. 3 min from Nakasu-Kawabata station, rated 8.6.',
    cta: 'See rooms', badge: 'Free coworking',
  },
  'stay-tribal-bali': {
    productTitle: 'TRIBAL Coworking Bali',
    destination: 'Canggu, Bali · Indonesia',
    desc: "Bali's first purpose-built coworking stay. Poolside workspace and a real nomad community.",
    cta: 'See rooms', badge: 'Nomad favorite',
  },
  'stay-chicland-danang': {
    productTitle: 'Chicland Danang Beach Hotel',
    destination: 'Da Nang · Vietnam',
    desc: '2 min to My Khe beach, café-style lounge and rooftop pool. Near the An Thuong nomad area, rated 8.6.',
    cta: 'See rooms', badge: 'Beach work',
  },
  'stay-playce-jeju': {
    productTitle: 'Playce Camp Jeju',
    destination: 'Seongsan, Jeju · Korea',
    desc: 'Rooms with separate work desks and dedicated workation packages. Near Seongsan Ilchulbong.',
    cta: 'See rooms', badge: 'Workation-ready',
  },
  'stay-kantary-chiangmai': {
    productTitle: 'Kantary Hills Chiang Mai',
    destination: 'Nimman, Chiang Mai · Thailand',
    desc: 'Serviced apartments with kitchenettes, built for long stays. Walk to Maya Mall and One Nimman.',
    cta: 'See rooms', badge: 'Long stay',
  },
  'stay-lyf-sukhumvit-bangkok': {
    productTitle: 'lyf Sukhumvit 8 Bangkok',
    destination: 'Bangkok · Thailand',
    desc: 'Co-living 3 min from Nana BTS. Coworking space, kitchenettes and a rooftop — built for nomads.',
    cta: 'See rooms', badge: 'Co-living',
  },
  'stay-citizenm-taipei': {
    productTitle: 'citizenM Taipei North Gate',
    destination: 'Taipei · Taiwan',
    desc: 'Smart hotel a walk from Ximending. Location rated 9.3, 24/7 lounge for late-night work.',
    cta: 'See rooms', badge: 'Smart hotel',
  },
  'act-tokyo-disney': {
    productTitle: 'Tokyo Disneyland · DisneySea ticket',
    destination: 'Tokyo · Japan',
    desc: '1-day pass with instant mobile QR entry. Make a workation weekend special.',
    cta: 'View product', badge: 'Best seller',
  },
  'act-osaka-usj': {
    productTitle: 'Universal Studios Japan ticket',
    destination: 'Osaka · Japan',
    desc: '1-day pass with Express Pass options. Skip the lines on your Osaka weekend.',
    cta: 'View product', badge: 'Express',
  },
  'act-fukuoka-bustour': {
    productTitle: 'Fukuoka day bus tour (KR guide)',
    destination: 'Fukuoka · Japan',
    desc: 'Dazaifu, Yufuin and Beppu in one day. Departs Hakata station with a Korean-speaking guide.',
    cta: 'View product', badge: 'Guided',
  },
  'act-bali-ubud': {
    productTitle: 'Bali Ubud private tour (KR guide)',
    destination: 'Bali · Indonesia',
    desc: 'Half-day customizable private tour — temples and rice terraces, your route.',
    cta: 'View product', badge: 'Private',
  },
  'act-danang-banahills': {
    productTitle: 'Da Nang Ba Na Hills private tour',
    destination: 'Da Nang · Vietnam',
    desc: 'Golden Bridge, tickets, lunch and pickup included. Private-vehicle day tour.',
    cta: 'View product', badge: 'All-inclusive',
  },
  'act-klook-teamlab-tokyo': {
    productTitle: 'teamLab Planets TOKYO ticket',
    destination: 'Tokyo · Japan',
    desc: 'Immersive digital art in Toyosu — walk barefoot through water. Best in the evening.',
    cta: 'View product', badge: 'Top pick',
  },
  'act-klook-osaka-pass': {
    productTitle: 'Osaka Amazing Pass',
    destination: 'Osaka · Japan',
    desc: 'Unlimited subway and buses plus entry to 40+ spots — the Osaka weekend essential.',
    cta: 'View pass', badge: 'Transit + entry',
  },
  'act-klook-taipei-tour': {
    productTitle: 'Yehliu · Jiufen · Shifen day tour',
    destination: 'Taipei · Taiwan',
    desc: 'Three Taipei-area icons in one day, sky lantern release included.',
    cta: 'View tour', badge: 'Guided day tour',
  },
  'act-klook-uss-singapore': {
    productTitle: 'Universal Studios Singapore ticket',
    destination: 'Singapore',
    desc: 'Seven themed zones on Sentosa — the classic Singapore workation weekend.',
    cta: 'View ticket', badge: 'Top pick',
  },
  'act-klook-nusapenida-bali': {
    productTitle: 'Nusa Penida day tour from Bali',
    destination: 'Bali · Indonesia',
    desc: 'Kelingking cliff, Broken Beach and Crystal Bay — the island everyone goes for.',
    cta: 'View tour', badge: 'Best tour',
  },
  'act-klook-elephant-chiangmai': {
    productTitle: 'Elephant Jungle Sanctuary Chiang Mai',
    destination: 'Chiang Mai · Thailand',
    desc: 'Ethical, no-riding elephant care — passed Klook’s animal-welfare assessment.',
    cta: 'View experience', badge: 'Welfare assessed',
  },
  'theme-golf-alpine-chiangmai': {
    productTitle: 'Alpine Golf Resort Chiang Mai tee time', destination: 'Chiang Mai · Thailand',
    desc: 'Easy tee-time booking at Chiang Mai’s signature Alpine GC. Morning round, afternoon work.',
    cta: 'View tee times', badge: 'Golf',
  },
  'theme-golf-pattaya-cc': {
    productTitle: 'Pattaya Country Club tee time', destination: 'Pattaya · Thailand',
    desc: 'Tee times near Bangkok — the weekend golf run for a Bangkok workation.',
    cta: 'View tee times', badge: 'Golf',
  },
  'theme-heal-oasis-chiangmai': {
    productTitle: 'Oasis Spa Chiang Mai massage', destination: 'Chiang Mai · Thailand',
    desc: 'Chiang Mai’s signature luxury spa brand. Thai massage recovery after work — book via KKday.',
    cta: 'Book spa', badge: 'Wellness',
  },
  'theme-heal-forest-danang': {
    productTitle: 'Forest Spa Da Nang massage', destination: 'Da Nang · Vietnam',
    desc: 'City-center spa booking (free pickup option). An evening recovery routine for nomads.',
    cta: 'Book spa', badge: 'Wellness',
  },
  'theme-sports-seoul-baseball': {
    productTitle: 'Seoul baseball with a local — game + pre-game meal', destination: 'Seoul · Korea',
    desc: 'A guided night at Jamsil stadium. The evening event of a Korea workation.',
    cta: 'View ticket', badge: 'Live baseball',
  },
  'theme-sports-tottenham': {
    productTitle: 'Tottenham Hotspur Premier League ticket', destination: 'London · UK',
    desc: 'PL match day at Spurs’ home ground — a Europe-workation bucket-list item.',
    cta: 'View ticket', badge: 'Live football',
  },
  'theme-local-izakaya-kyoto': {
    productTitle: 'Kyoto izakaya private half-day tour', destination: 'Kyoto · Japan',
    desc: 'Eat and drink like a local — from Nishiki Market to backstreet izakayas.',
    cta: 'View tour', badge: 'Food',
  },
  'theme-local-nishiki': {
    productTitle: 'Nishiki Market walking food tour (3h)',
    destination: 'Kyoto · Japan',
    desc: 'A guided 3-hour tasting walk through "Kyoto’s kitchen" — join tour via Klook.',
    cta: 'View tour', badge: 'Food',
  },
  'theme-local-gion-food': {
    productTitle: 'Gion food tour — 13 dishes at 4 eateries',
    destination: 'Kyoto · Japan',
    desc: 'An evening tasting tour through four Gion eateries. A local night out after work.',
    cta: 'View tour', badge: 'Food',
  },
  'theme-sports-sumo-osaka': {
    productTitle: 'Osaka Grand Sumo Tournament viewing (ticket incl.)',
    destination: 'Osaka · Japan',
    desc: 'Tournament seat plus a guided half-day walk — a Japan-only spectator experience.',
    cta: 'View ticket', badge: 'Live sports',
  },
  'esim-klook-japan': {
    productTitle: 'Japan eSIM (DOCOMO · Softbank)',
    destination: 'Japan',
    desc: 'Activate in 5 minutes via QR. Unlimited or daily plans on local carrier networks.',
    cta: 'View eSIM', badge: 'Japan-ready',
  },
  'esim-klook-asia': {
    productTitle: 'Asia 30+ countries eSIM',
    destination: 'Multi-country Asia',
    desc: 'Japan, Thailand, Vietnam and Taiwan on one eSIM — for multi-stop workation routes.',
    cta: 'View eSIM', badge: 'Multi-country',
  },
  'cruise-rci-singapore': {
    productTitle: 'Royal Caribbean Navigator · Singapore 4D',
    destination: 'Singapore → Penang',
    desc: 'Departs Singapore with a Penang call — 3 nights. Ship Wi-Fi makes it a starter cruise workation.',
    cta: 'See fares', badge: 'Tracked',
  },
  'cruise-msc-bellissima-busan': {
    productTitle: 'MSC Bellissima · Busan round-trip',
    destination: 'Busan → Fukuoka · Sasebo',
    desc: 'Sail from Busan and return to Busan — 4 nights, no flights needed.',
    cta: 'See dates', badge: 'From Busan',
  },
  'cruise-panstar-osaka': {
    productTitle: 'Panstar Cruise · Busan–Osaka 5D',
    destination: 'Busan ↔ Osaka',
    desc: 'Cruise + Osaka hotel + onboard meals in one package. The easiest first cruise workation.',
    cta: 'View product', badge: 'Best value',
  },
  'cruise-costa-serena-busan': {
    productTitle: 'Costa Serena · Busan → Taiwan · Japan 6D',
    destination: 'Busan → Nagasaki · Keelung',
    desc: 'Departs Busan late August, calling at Nagasaki and Keelung — a full international cruise.',
    cta: 'See dates', badge: 'Aug departure',
  },
  'course-gpts-automation': {
    productTitle: 'GPTs work automation for professionals',
    destination: 'AI · Automation',
    desc: 'Automate repetitive work with GPTs — win back hours on your workation.',
    cta: 'View course', badge: 'Practical AI',
  },
  'course-chatgpt-work': {
    productTitle: 'ChatGPT for real work',
    destination: 'AI · Productivity',
    desc: '10x your work speed with ChatGPT. Great listening for transit time.',
    cta: 'View course', badge: 'Best seller',
  },
  'course-notion-master': {
    productTitle: 'Notion complete guide',
    destination: 'Productivity · Notion',
    desc: 'Free course rated 4.8 by 40,000+ learners. The starting point of a workation work system.',
    cta: 'Start free', badge: 'Free',
  },
  'course-instagram-marketing': {
    productTitle: 'Instagram marketing that sells',
    destination: 'Marketing · Social',
    desc: 'Hands-on Instagram growth for solo businesses — practice with content from your destination.',
    cta: 'View course', badge: 'Marketing',
  },
  'course-biz-english-email': {
    productTitle: 'Business English email with an interpreter',
    destination: 'Language · Business',
    desc: 'Real-world English email for workationers working with global partners.',
    cta: 'View course', badge: 'Biz English',
  },
  'stay-adina-sydney': {
    productTitle: 'Adina Apartment Hotel Sydney Town Hall',
    destination: 'Sydney · Australia',
    desc: 'Full-kitchen aparthotel in the CBD. 2 min from Town Hall station, indoor pool.',
    cta: 'See rooms', badge: 'Full kitchen',
  },
  'stay-nomadshub-cebu': {
    productTitle: "Nomad's Hub Co-living Cebu",
    destination: 'Cebu · Philippines',
    desc: 'Coworking + co-living in central Cebu City. Hot desks included — a real nomad base.',
    cta: 'See rooms', badge: 'Co-living',
  },
  'theme-golf-montgomerie': {
    productTitle: 'Montgomerie Links Da Nang tee time',
    destination: 'Da Nang · Vietnam',
    desc: "Vietnam's signature links course. The classic weekend round on a workation.",
    cta: 'See tee times', badge: 'Golf',
  },
  'theme-golf-hoiana': {
    productTitle: 'Hoiana Shores Golf Club round',
    destination: 'Hoi An · Vietnam',
    desc: 'Coastal-view round at Hoiana Shores — golf plus resort workation.',
    cta: 'Book a round', badge: 'Golf',
  },
  'theme-heal-spa-ubud': {
    productTitle: 'Ubud Balinese spa session',
    destination: 'Ubud · Bali',
    desc: 'Balinese spa in the Ubud jungle — your after-work recovery routine.',
    cta: 'Book spa', badge: 'Wellness',
  },
  'theme-heal-yoga-bali': {
    productTitle: 'Bali sunrise yoga class',
    destination: 'Bali · Indonesia',
    desc: 'Start with sunrise yoga — the nomad morning routine, on location.',
    cta: 'See classes', badge: 'Yoga',
  },
  'theme-sports-tokyodome': {
    productTitle: 'Tokyo Dome Giants game ticket',
    destination: 'Tokyo · Japan',
    desc: 'Yomiuri Giants home game at Tokyo Dome — a workation evening at the ballpark.',
    cta: 'See tickets', badge: 'Baseball',
  },
  'theme-local-kuromon': {
    productTitle: 'Osaka Kuromon Market food tour',
    destination: 'Osaka · Japan',
    desc: "Eat through Osaka's kitchen like a local — a one-hour lunchtime food tour.",
    cta: 'See tour', badge: 'Food',
  },
  'feat-tokyo-hotel': {
    productTitle: 'Tokyo long-stay hotels',
    destination: 'Tokyo · Japan',
    desc: 'Apartments, serviced residences and business hotels — picked for workations.',
    cta: 'Search Tokyo stays',
    badge: 'Long stay',
  },
  'feat-osaka-hotel': {
    productTitle: 'Osaka hotels & apartments',
    destination: 'Osaka · Japan',
    desc: 'Stays, flights and tours in one place. Find long-stay Osaka hotels on Trip.com.',
    cta: 'Search Osaka stays',
    badge: 'Stay · Flight',
  },
  'feat-fukuoka-hotel': {
    productTitle: 'Fukuoka workation stays',
    destination: 'Fukuoka · Japan',
    desc: 'Tenjin & Hakata business hotels and serviced apartments — the closest overseas base.',
    cta: 'Search Fukuoka stays',
    badge: 'Long stay',
  },
  'feat-bali-hotel': {
    productTitle: 'Bali villas & resorts',
    destination: 'Bali · Indonesia',
    desc: 'Ubud, Kuta and Seminyak villas, coliving stays and resorts for longer trips.',
    cta: 'Search Bali stays',
    badge: 'Long stay',
  },
  'feat-japan-activity': {
    productTitle: 'Japan tours & activities',
    destination: 'All Japan',
    desc: 'Local tours, transit passes and tickets across Tokyo, Osaka and Fukuoka.',
    cta: 'Browse activities',
    badge: 'Experiences',
  },
  'feat-japan-esim': {
    productTitle: 'Japan eSIM — instant',
    destination: 'Japan',
    desc: 'Install before you land. Unlimited or daily data plans, 200+ countries covered.',
    cta: 'Get an eSIM',
    badge: 'eSIM',
  },
  'feat-vietnam-hotel': {
    productTitle: 'Hoi An & Da Nang stays',
    destination: 'Da Nang · Vietnam',
    desc: 'Long-stay hotels in Hoi An, Da Nang and Hanoi — an affordable workation base.',
    cta: 'Search Vietnam stays',
    badge: 'Long stay',
  },
  'feat-bali-activity': {
    productTitle: 'Bali tours & experiences',
    destination: 'Bali · Indonesia',
    desc: 'Ubud rice terraces, surf lessons and temple tours — things only Bali can offer.',
    cta: 'See Bali experiences',
    badge: 'Experiences',
  },
}

const JP: Record<string, Overlay> = {
  'hotel-booking': {
    desc: '世界中の宿泊予約。長期滞在・アパートメント・サービスレジデンスに最適。',
    cta: '宿を予約',
    badge: '長期滞在',
  },
  'hotel-tripcom': {
    desc: '宿・航空券・ツアーをひとつに。目的地別の長期滞在ホテルを検索。',
    cta: '宿を探す',
    badge: '宿 · 航空',
  },
  'activity-kkday': {
    desc: '現地ツアー・アクティビティ・入場券・交通パス。日本・台湾・東南アジアが充実。',
    cta: '体験を予約',
    badge: '現地体験',
  },
  'esim-airalo': {
    desc: '200カ国対応のeSIMを即時購入。到着前にインストールして並ばず接続。',
    cta: 'eSIMを購入',
    badge: 'eSIM',
  },
  'edu-inflearn': {
    name: 'Inflearn',
    desc: 'IT・開発・デザイン・ビジネス講座。移動中に学び、到着後すぐ実践。',
    cta: '講座を見る',
    badge: 'オンライン講座',
  },
  'insurance-safetywing': {
    desc: 'ノマド・長期滞在者向けの月単位トラベル保険。188カ国をカバー。',
    cta: '保険を見る',
    badge: '旅行保険',
  },
  'hotel-booking-visa': {
    displayTitle: '航空券・宿の予約',
    desc: 'ビザ申請に必要な航空券・宿泊の予約確認書を取得できます。',
    cta: '航空券・宿を予約',
    badge: '航空 · 宿',
  },
  'esim-airalo-visa': {
    desc: 'ビザ受領前にインストールしておけば入国後すぐ接続。200カ国対応。',
    cta: 'eSIMを購入',
    badge: 'eSIM',
  },
  'hotel-booking-market': {
    desc: '現地のホテル・アパートメント。市場調査の長期滞在に適した宿を。',
    cta: '宿を予約',
    badge: '長期滞在',
  },
  'hotel-booking-domestic': {
    desc: '襄陽・江陵・済州など、プログラム前後に泊まる韓国国内の宿を検索。',
    cta: '韓国の宿を検索',
    badge: '国内の宿',
  },
  'activity-kkday-domestic': {
    desc: '江原・釜山・済州のローカルツアーと入場券。ワーケーションの夜と週末に。',
    cta: '韓国の体験を見る',
    badge: '国内体験',
  },
  'feat-flight-tripcom': {
    productTitle: '航空券の料金比較・予約',
    destination: 'ソウル発 全路線',
    desc: 'ワーケーション目的地行きの航空券を航空会社別に比較。片道・往復・周遊に対応。',
    cta: '航空券を比較',
    badge: '航空券',
  },
  'stay-millennials-shibuya': {
    productTitle: 'ザ・ミレニアルズ渋谷',
    destination: '東京 · 日本',
    desc: 'ホテル内にコワーキング「.andwork」2フロア。渋谷駅徒歩6分、無料コーヒーとハッピーアワーも。',
    cta: '客室を見る', badge: 'コワーキング内蔵',
  },
  'stay-lively-osaka': {
    productTitle: 'ザ・ライブリー大阪本町',
    destination: '大阪 · 日本',
    desc: '作業できる共用ラウンジが7カ所。本町ビジネス地区、評価8.7（2,600件以上）。',
    cta: '客室を見る', badge: 'ラウンジワーク',
  },
  'stay-webase-hakata': {
    productTitle: 'WeBase 博多',
    destination: '福岡 · 日本',
    desc: '9階の宿泊者無料コワーキング＋テラス。中洲川端駅徒歩3分、評価8.6。',
    cta: '客室を見る', badge: '無料コワーキング',
  },
  'stay-tribal-bali': {
    productTitle: 'トライバル・コワーキング・バリ',
    destination: 'チャングー、バリ · インドネシア',
    desc: 'バリ初のコワーキング特化型ステイ。プールサイドのワークスペースとノマドコミュニティ。',
    cta: '客室を見る', badge: 'ノマドの聖地',
  },
  'stay-chicland-danang': {
    productTitle: 'チックランド・ダナン・ビーチホテル',
    destination: 'ダナン · ベトナム',
    desc: 'ミーケビーチ徒歩2分、カフェ風ラウンジとルーフトッププール。評価8.6。',
    cta: '客室を見る', badge: 'ビーチワーク',
  },
  'stay-playce-jeju': {
    productTitle: 'プレイスキャンプ済州',
    destination: '済州 城山 · 韓国',
    desc: '寝室とワークデスクを分けた客室、ワーケーション専用パッケージも。城山日出峰近く。',
    cta: '客室を見る', badge: 'ワーケーション特化',
  },
  'stay-lyf-sukhumvit-bangkok': {
    productTitle: 'lyf スクンビット8 バンコク',
    destination: 'バンコク · タイ',
    desc: 'ナナ駅徒歩3分のコリビング。コワーキング・簡易キッチン・ルーフトップ完備。',
    cta: '客室を見る', badge: 'コリビング',
  },
  'stay-citizenm-taipei': {
    productTitle: 'シチズンM 台北ノースゲート',
    destination: '台北 · 台湾',
    desc: '西門町徒歩圏のスマートホテル。立地評価9.3、24時間ラウンジで夜作業も。',
    cta: '客室を見る', badge: 'スマートホテル',
  },
  'stay-kantary-chiangmai': {
    productTitle: 'カンタリーヒルズ・チェンマイ',
    destination: 'ニマン、チェンマイ · タイ',
    desc: 'キッチネット付きサービスアパート。長期滞在向け、マヤモール徒歩圏。',
    cta: '客室を見る', badge: '長期滞在',
  },
  'act-tokyo-disney': {
    productTitle: '東京ディズニーランド・シー チケット',
    destination: '東京 · 日本',
    desc: 'モバイルQRで即入場の1日券。ワーケーションの週末を特別に。',
    cta: '商品を見る', badge: '人気No.1',
  },
  'act-osaka-usj': {
    productTitle: 'USJ入場券',
    destination: '大阪 · 日本',
    desc: '1日券＋エクスプレスパスのオプション。並ばない大阪の週末。',
    cta: '商品を見る', badge: 'エクスプレス',
  },
  'act-fukuoka-bustour': {
    productTitle: '福岡近郊バスツアー',
    destination: '福岡 · 日本',
    desc: '太宰府・湯布院・別府を1日で。博多駅発。',
    cta: '商品を見る', badge: 'ガイド付き',
  },
  'act-bali-ubud': {
    productTitle: 'バリ ウブド プライベートツアー',
    destination: 'バリ · インドネシア',
    desc: '寺院・ライステラスを半日でカスタム。自由なコースで。',
    cta: '商品を見る', badge: 'プライベート',
  },
  'act-danang-banahills': {
    productTitle: 'ダナン バナヒルズ ツアー',
    destination: 'ダナン · ベトナム',
    desc: 'ゴールデンブリッジ、入場券・昼食・送迎込み。専用車の日帰りツアー。',
    cta: '商品を見る', badge: 'オールインクルーシブ',
  },
  'act-klook-teamlab-tokyo': {
    productTitle: 'チームラボプラネッツ TOKYO チケット',
    destination: '東京 · 日本',
    desc: '豊洲の没入型デジタルアート。水の中を裸足で歩く展示 — 夜がおすすめ。',
    cta: '商品を見る', badge: '人気体験',
  },
  'act-klook-osaka-pass': {
    productTitle: '大阪周遊パス',
    destination: '大阪 · 日本',
    desc: '地下鉄・バス乗り放題＋40カ所以上の入場。大阪週末の必需品。',
    cta: 'パスを見る', badge: '交通＋入場',
  },
  'act-klook-taipei-tour': {
    productTitle: '野柳・九份・十分 日帰りツアー',
    destination: '台北 · 台湾',
    desc: '台北近郊の3大名所を1日で。十分のランタン上げ付き。',
    cta: 'ツアーを見る', badge: 'ガイド付き',
  },
  'act-klook-uss-singapore': {
    productTitle: 'ユニバーサル・スタジオ・シンガポール チケット',
    destination: 'シンガポール',
    desc: 'セントーサの7テーマゾーン。シンガポール週末の定番コース。',
    cta: 'チケットを見る', badge: '人気体験',
  },
  'act-klook-nusapenida-bali': {
    productTitle: 'ヌサペニダ島 日帰りツアー',
    destination: 'バリ · インドネシア',
    desc: 'ケリンキン断崖・ブロークンビーチ・クリスタルベイ。バリの定番離島。',
    cta: 'ツアーを見る', badge: 'ベストツアー',
  },
  'act-klook-elephant-chiangmai': {
    productTitle: 'チェンマイ エレファント・ジャングル・サンクチュアリ',
    destination: 'チェンマイ · タイ',
    desc: '乗らずに世話をする倫理的な象体験 — Klook動物福祉審査通過。',
    cta: '体験を見る', badge: '動物福祉認証',
  },
  'theme-golf-alpine-chiangmai': {
    productTitle: 'アルパインGCチェンマイ ティータイム', destination: 'チェンマイ · タイ',
    desc: 'チェンマイ屈指の名門アルパインGCを簡単予約。午前ラウンド、午後は仕事。',
    cta: 'ティータイムを見る', badge: 'ゴルフ',
  },
  'theme-golf-pattaya-cc': {
    productTitle: 'パタヤCC ティータイム予約', destination: 'パタヤ · タイ',
    desc: 'バンコク近郊のティータイム予約。バンコク滞在の週末ゴルフに。',
    cta: 'ティータイムを見る', badge: 'ゴルフ',
  },
  'theme-heal-oasis-chiangmai': {
    productTitle: 'オアシススパ・チェンマイ マッサージ', destination: 'チェンマイ · タイ',
    desc: 'チェンマイ代表の高級スパブランド。仕事後のタイ古式で回復 — KKday予約。',
    cta: 'スパを予約', badge: 'ヒーリング',
  },
  'theme-heal-forest-danang': {
    productTitle: 'ダナン フォレストスパ マッサージ', destination: 'ダナン · ベトナム',
    desc: '市内スパの予約（無料送迎オプション）。ノマドの夜の回復ルーティンに。',
    cta: 'スパを予約', badge: 'ヒーリング',
  },
  'theme-sports-seoul-baseball': {
    productTitle: 'ソウル野球観戦 — ローカルと観戦＋食事', destination: 'ソウル · 韓国',
    desc: '蚕室球場でガイドと直接観戦。韓国ワーケーションの夜イベント。',
    cta: 'チケットを見る', badge: '野球観戦',
  },
  'theme-sports-tottenham': {
    productTitle: 'トッテナム プレミアリーグ観戦チケット', destination: 'ロンドン · 英国',
    desc: 'スパーズ本拠地でのPL観戦。欧州ワーケーションのバケットリスト。',
    cta: 'チケットを見る', badge: 'サッカー観戦',
  },
  'theme-local-izakaya-kyoto': {
    productTitle: '京都 居酒屋プライベート半日ツアー', destination: '京都 · 日本',
    desc: '錦市場から路地裏の居酒屋まで、地元流に食べ歩き。',
    cta: 'ツアーを見る', badge: 'グルメ',
  },
  'theme-local-nishiki': {
    productTitle: '錦市場ウォーキングフードツアー（3時間）',
    destination: '京都 · 日本',
    desc: '「京の台所」錦市場をガイドと食べ歩く3時間のジョインツアー — Klook予約。',
    cta: 'ツアーを見る', badge: 'グルメ',
  },
  'theme-local-gion-food': {
    productTitle: '祇園フードツアー — 4店舗13品',
    destination: '京都 · 日本',
    desc: '祇園の4店舗を巡り13品を味わう夜のグルメツアー。仕事後のローカルな夜に。',
    cta: 'ツアーを見る', badge: 'グルメ',
  },
  'theme-sports-sumo-osaka': {
    productTitle: '大阪大相撲観覧（チケット込み）',
    destination: '大阪 · 日本',
    desc: '観覧席チケット＋ガイド付き半日ウォーク。日本でしかできない観戦体験。',
    cta: 'チケットを見る', badge: '観戦',
  },
  'esim-klook-japan': {
    productTitle: '日本eSIM（DOCOMO・Softbank）',
    destination: '日本',
    desc: 'QRで5分開通。現地キャリア回線の無制限・日別プラン。',
    cta: 'eSIMを見る', badge: '日本特化',
  },
  'esim-klook-asia': {
    productTitle: 'アジア30+カ国 eSIM',
    destination: 'アジア・マルチ国',
    desc: '日本・タイ・ベトナム・台湾をeSIM 1枚で。周遊ワーケーションに。',
    cta: 'eSIMを見る', badge: 'マルチ国',
  },
  'cruise-rci-singapore': {
    productTitle: 'ロイヤルカリビアン ナビゲーター · シンガポール4日',
    destination: 'シンガポール → ペナン',
    desc: 'シンガポール発、ペナン寄港の3泊。船内Wi-Fiで働けるクルーズワーケーション入門。',
    cta: '料金を見る', badge: 'トラッキング',
  },
  'cruise-msc-bellissima-busan': {
    productTitle: 'MSCベリッシマ · 釜山発着クルーズ',
    destination: '釜山 → 福岡 · 佐世保',
    desc: '釜山発・釜山着の4泊5日。飛行機なしで始めるクルーズワーケーション。',
    cta: '日程を見る', badge: '釜山発',
  },
  'cruise-panstar-osaka': {
    productTitle: 'パンスタークルーズ · 釜山-大阪',
    destination: '釜山 ↔ 大阪',
    desc: 'クルーズ＋大阪ホテル＋船内食のパッケージ。最も気軽な初クルーズ。',
    cta: '商品を見る', badge: 'お得',
  },
  'cruise-costa-serena-busan': {
    productTitle: 'コスタセレーナ · 釜山発 台湾·日本6日',
    destination: '釜山 → 長崎 · 基隆',
    desc: '8月末釜山発、長崎・基隆寄港の本格国際クルーズ。',
    cta: '日程を見る', badge: '8月出航',
  },
  'course-gpts-automation': {
    productTitle: 'GPTs業務自動化',
    destination: 'AI · 自動化',
    desc: '繰り返し業務をGPTsで自動化。ワーケーションの作業時間を取り戻す実践講座。',
    cta: '講座を見る', badge: '実務AI',
  },
  'course-chatgpt-work': {
    productTitle: 'ChatGPT実務活用',
    destination: 'AI · 生産性',
    desc: '仕事の速度を10倍にするChatGPT活用法。移動中の受講にも。',
    cta: '講座を見る', badge: 'ベスト',
  },
  'course-notion-master': {
    productTitle: 'Notion完全活用',
    destination: '生産性 · Notion',
    desc: '評価4.8、4万人が受講した無料講座。ワーケーション業務システムの出発点。',
    cta: '無料で受講', badge: '無料',
  },
  'course-instagram-marketing': {
    productTitle: '売上を伸ばすInstagramマーケ',
    destination: 'マーケ · SNS',
    desc: '一人ビジネスの売上を作るInstagram実践運用。現地コンテンツですぐ実習。',
    cta: '講座を見る', badge: 'マーケ',
  },
  'course-biz-english-email': {
    productTitle: '通訳者と書くビジネス英語メール',
    destination: '語学 · ビジネス',
    desc: '海外パートナーと働くワーケーターのための英文メール実践。',
    cta: '講座を見る', badge: 'ビジネス英語',
  },
  'stay-adina-sydney': {
    productTitle: 'アディナ・アパートメントホテル・シドニー・タウンホール',
    destination: 'シドニー · オーストラリア',
    desc: 'CBD中心のフルキッチン付きアパートホテル。タウンホール駅徒歩2分、室内プールも。',
    cta: '客室を見る', badge: 'フルキッチン',
  },
  'stay-nomadshub-cebu': {
    productTitle: 'ノマズハブ・コリビング・セブ',
    destination: 'セブ · フィリピン',
    desc: 'セブ市中心のコワーキング＋コリビング。ホットデスク込み、ノマドの拠点。',
    cta: '客室を見る', badge: 'コリビング',
  },
  'theme-golf-montgomerie': {
    productTitle: 'モンゴメリーリンクス ダナン ティータイム',
    destination: 'ダナン · ベトナム',
    desc: 'ベトナム屈指のリンクスコース。ワーケーション週末ゴルフの定番。',
    cta: 'ティータイム', badge: 'ゴルフ',
  },
  'theme-golf-hoiana': {
    productTitle: 'ホイアナ ショアーズGC ラウンド',
    destination: 'ホイアン · ベトナム',
    desc: '海沿い絶景のホイアナショアーズ。ゴルフ＋リゾートワーケーション。',
    cta: 'ラウンド予約', badge: 'ゴルフ',
  },
  'theme-heal-spa-ubud': {
    productTitle: 'ウブド バリニーズスパ',
    destination: 'ウブド · バリ',
    desc: 'ウブドのジャングルでバリ式スパ。仕事後の回復ルーティンに。',
    cta: 'スパ予約', badge: 'ウェルネス',
  },
  'theme-heal-yoga-bali': {
    productTitle: 'バリ サンライズヨガ',
    destination: 'バリ · インドネシア',
    desc: '日の出とともにヨガを。ノマドの朝ルーティンを現地で。',
    cta: 'クラスを見る', badge: 'ヨガ',
  },
  'theme-sports-tokyodome': {
    productTitle: '東京ドーム 巨人戦チケット',
    destination: '東京 · 日本',
    desc: '東京ドームでジャイアンツのホームゲーム。仕事後の野球観戦。',
    cta: 'チケットを見る', badge: '野球観戦',
  },
  'theme-local-kuromon': {
    productTitle: '大阪 黒門市場フードツアー',
    destination: '大阪 · 日本',
    desc: '大阪の台所・黒門市場を地元流に食べ歩き。昼休みの1時間ツアー。',
    cta: 'ツアーを見る', badge: 'グルメ',
  },
  'feat-tokyo-hotel': {
    productTitle: '東京の長期滞在ホテル',
    destination: '東京 · 日本',
    desc: 'アパートメント・サービスレジデンス・ビジネスホテル。ワーケーション向けに厳選。',
    cta: '東京の宿を検索',
    badge: '長期滞在',
  },
  'feat-osaka-hotel': {
    productTitle: '大阪のホテル・アパート',
    destination: '大阪 · 日本',
    desc: '宿・航空券・ツアーをひとつに。Trip.comで大阪の長期滞在ホテルを検索。',
    cta: '大阪の宿を検索',
    badge: '宿 · 航空',
  },
  'feat-fukuoka-hotel': {
    productTitle: '福岡ワーケーションの宿',
    destination: '福岡 · 日本',
    desc: '天神・博多のビジネスホテルとサービスアパート。韓国から最も近い海外拠点。',
    cta: '福岡の宿を検索',
    badge: '長期滞在',
  },
  'feat-bali-hotel': {
    productTitle: 'バリのヴィラ・リゾート',
    destination: 'バリ · インドネシア',
    desc: 'ウブド・クタ・スミニャックのヴィラやコリビング。長期滞在に最適。',
    cta: 'バリの宿を検索',
    badge: '長期滞在',
  },
  'feat-japan-activity': {
    productTitle: '日本の現地ツアー・体験',
    destination: '日本全域',
    desc: '東京・大阪・福岡の現地ツアー、交通パス、入場券をまとめて。',
    cta: '体験を見る',
    badge: '現地体験',
  },
  'feat-japan-esim': {
    productTitle: '日本eSIM 即時購入',
    destination: '日本',
    desc: '到着前にインストール。無制限・デイリープランを選択、200カ国対応。',
    cta: 'eSIMを購入',
    badge: 'eSIM',
  },
  'feat-vietnam-hotel': {
    productTitle: 'ホイアン・ダナンの宿',
    destination: 'ダナン · ベトナム',
    desc: 'ホイアン・ダナン・ハノイの長期滞在ホテル。快適でリーズナブルな拠点。',
    cta: 'ベトナムの宿を検索',
    badge: '長期滞在',
  },
  'feat-bali-activity': {
    productTitle: 'バリの現地ツアー・体験',
    destination: 'バリ · インドネシア',
    desc: 'ウブドのライステラス、サーフィン、寺院ツアー。バリだけの体験を。',
    cta: 'バリの体験を見る',
    badge: '現地体験',
  },
}

export function localizeAffiliateItem(item: AffiliateItem, lang: Lang): AffiliateItem {
  if (lang === 'KO') return item
  const overlay = (lang === 'EN' ? EN : JP)[item.id]
  return overlay ? { ...item, ...overlay } : item
}
