import type { Lang } from '@/lib/i18n/types'
import type { BrandModelId } from '@/lib/media/brandModels'
import { CARD_MEDIA_ASSETS } from '@/lib/media/cardMedia'
import { PRODUCT_EDITORIAL_MEDIA_ASSETS } from '@/lib/media/productEditorial'

export type MediaFocalPoint = { x: number; y: number }
export type MediaModelId = BrandModelId | 'WAK-MODEL-K'

export type MediaSafeFraming = {
  minHeadroomPercent?: number
  preserve?: Array<'head' | 'face' | 'hands' | 'bag' | 'device' | 'documents' | 'feet'>
}

export type MediaAsset = {
  id: string
  src: string
  alt: Record<Lang, string>
  sourceType: 'owned' | 'licensed' | 'generated' | 'partner'
  usage: 'hero' | 'editorial' | 'destination' | 'product' | 'story' | 'social'
  illustrative: boolean
  mediaType?: 'image' | 'video'
  width?: number
  height?: number
  modelId?: MediaModelId
  modelIds?: MediaModelId[]
  localeUsage?: Array<'ko' | 'en' | 'ja'>
  seasonalUsage?: Array<'spring' | 'summer' | 'late-summer' | 'autumn' | 'winter' | 'all-season'>
  season?: 'spring' | 'summer' | 'late-summer' | 'autumn' | 'winter' | 'all-season'
  climateMood?: string
  wardrobeFamily?: string
  wardrobeTags?: string[]
  hairDirection?: string
  activityTags?: string[]
  travelContext?: string
  styleDirection?: string
  seasonalFit?: string
  activityMood?: string
  destinationMood?: string
  realismLevel?: 'high_photoreal' | 'photoreal_editorial' | 'graphic_editorial'
  generationProvider?: 'openai_builtin_imagegen' | 'existing_asset' | 'partner' | 'licensed'
  rejectedReason?: string
  auditDisposition?: 'KEEP' | 'RECROP' | 'RESTYLE' | 'REGENERATE_REALISM' | 'REPLACE_MODEL' | 'REPLACE_WITH_PLACE' | 'REPLACE_WITH_DIAGRAM' | 'REMOVE' | 'REAL_PHOTO_REQUIRED'
  adjacentModelRestrictions?: string[]
  realismTarget?: 'high_photoreal_editorial' | 'documentary_reference' | 'graphic_editorial'
  realismMethod?: string
  photorealReferenceUsed?: boolean
  routeUsage?: string[]
  sectionUsage?: string[]
  generatedFromReferenceIds?: string[]
  referenceOnly?: boolean
  focalPoint?: MediaFocalPoint
  focalPoints?: {
    desktop?: MediaFocalPoint
    mobile?: MediaFocalPoint
  }
  framingMode?: 'cover' | 'full-subject-desktop'
  safeFraming?: MediaSafeFraming
  source?: string
  license?: string
  createdAt?: string
  verifiedAt?: string
  restriction?: Record<Lang, string>
}

export const MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 'home-workation-editorial-v1-legacy',
    src: '/campaign/home-workation-editorial-v1.webp',
    alt: {
      KO: '해안에서의 체류와 업무 전환을 표현한 Wakation 브랜드 장면',
      EN: 'A Wakation brand scene about moving between coastal time and work',
      JP: '海辺での滞在と仕事の切り替えを表現したWakationのブランドシーン',
    },
    sourceType: 'generated',
    usage: 'hero',
    illustrative: true,
    width: 1600,
    height: 900,
    localeUsage: ['ko', 'en', 'ja'],
    focalPoint: { x: 0.62, y: 0.5 },
    source: 'Legacy Wakation generated editorial asset; original production prompt not retained in this branch',
    license: 'Wakation-owned generated editorial asset',
    restriction: {
      KO: '실제 Hosted 참가자·숙소·확정 프로그램 현장으로 표현하지 않는다.',
      EN: 'Do not present as a real Hosted participant, stay or confirmed program location.',
      JP: '実在のHosted参加者・宿泊施設・確定済みプログラムの現場として表現しない。',
    },
  },
  {
    id: 'home-hero-model-a-coastal-work-desktop-v1',
    src: '/media/brand-models/home-hero-model-a-coastal-work-desktop-v1.webp',
    alt: {
      KO: '바다가 보이는 밝은 공간에서 노트북을 닫고 창밖을 보는 여행자',
      EN: 'A traveler closing a laptop and looking outside in a bright coastal setting',
      JP: '海の見える明るい空間でノートパソコンを閉じ、窓の外を見る旅行者',
    },
    sourceType: 'generated',
    usage: 'hero',
    illustrative: true,
    width: 1536,
    height: 1024,
    modelId: 'WAK-MODEL-A',
    localeUsage: ['ko', 'en', 'ja'],
    focalPoints: { desktop: { x: 0.7, y: 0.48 }, mobile: { x: 0.68, y: 0.47 } },
    source: 'OpenAI image generation using user-provided WAK-MODEL-A identity references',
    license: 'User-controlled generated brand editorial asset; commercial review completed for this use',
    createdAt: '2026-07-31',
    restriction: {
      KO: '특정 카페·호텔 또는 실제 Wakation 참가자 장면으로 단정하지 않는다.',
      EN: 'Do not identify this as a specific café, hotel or real Wakation participant scene.',
      JP: '特定のカフェ・ホテル、または実際のWakation参加者の場面として扱わない。',
    },
  },
  {
    id: 'home-hero-model-a-coastal-work-mobile-v1',
    src: '/media/brand-models/home-hero-model-a-coastal-work-mobile-v1.webp',
    alt: {
      KO: '바다가 보이는 밝은 공간에서 노트북을 정리하는 여행자',
      EN: 'A traveler packing up a laptop in a bright coastal setting',
      JP: '海の見える明るい空間でノートパソコンを片づける旅行者',
    },
    sourceType: 'generated',
    usage: 'hero',
    illustrative: true,
    width: 960,
    height: 1280,
    modelId: 'WAK-MODEL-A',
    localeUsage: ['ko', 'en', 'ja'],
    focalPoint: { x: 0.68, y: 0.47 },
    source: 'OpenAI image generation using user-provided WAK-MODEL-A identity references',
    license: 'User-controlled generated brand editorial asset; commercial review completed for this use',
    createdAt: '2026-07-31',
    restriction: {
      KO: '특정 카페·호텔 또는 실제 Wakation 참가자 장면으로 단정하지 않는다.',
      EN: 'Do not identify this as a specific café, hotel or real Wakation participant scene.',
      JP: '特定のカフェ・ホテル、または実際のWakation参加者の場面として扱わない。',
    },
  },
  {
    id: 'domestic-seoul-model-d-urban-work-v1',
    src: '/media/brand-models/domestic-seoul-model-d-urban-work-v1.webp',
    alt: {
      KO: '서울을 연상시키는 도시형 카페 공간에서 노트를 정리하는 여행자',
      EN: 'A traveler taking notes in a Seoul-inspired urban café setting',
      JP: 'ソウルをイメージした都会的なカフェ空間でノートを書く旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-D', localeUsage: ['ko', 'en', 'ja'],
    focalPoint: { x: 0.68, y: 0.48 },
    source: 'OpenAI image generation using user-provided WAK-MODEL-D identity reference',
    license: 'User-controlled generated brand editorial asset; commercial review completed for this use',
    createdAt: '2026-07-31',
    restriction: { KO: '실제 서울 매장이나 참가자 사진이 아니다.', EN: 'Not a real Seoul venue or participant photograph.', JP: '実在のソウルの店舗や参加者の写真ではない。' },
  },
  {
    id: 'experience-seoul-model-i-kpop-studio-v2',
    src: '/media/brand-models/experience-seoul-model-i-kpop-studio-v2.webp',
    alt: {
      KO: '서울을 연상시키는 밝은 연습실에서 성인 여행자와 강사가 춤 동작을 맞추는 편집 장면',
      EN: 'An editorial scene of an adult traveller learning dance movement with an instructor in a bright Seoul-inspired studio',
      JP: 'ソウルをイメージした明るいスタジオで、大人の旅行者が講師とダンスの動きを練習する編集イメージ',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1440, height: 1080, modelId: 'WAK-MODEL-I', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer', 'autumn'],
    routeUsage: [
      '/select/activity', '/en/select/activity', '/ja/select/activity',
      '/experiences/hongdae-kpop-walk-dance',
      '/en/experiences/hongdae-kpop-walk-dance',
      '/ja/experiences/hongdae-kpop-walk-dance',
      '/guide/seoul', '/en/guide/seoul', '/ja/guide/seoul',
      '/collections/seoul-3n4d', '/en/collections/seoul-3n4d', '/ja/collections/seoul-3n4d',
    ],
    sectionUsage: ['experience-editorial-seoul', 'activity-card'],
    generatedFromReferenceIds: ['select-model-i-travel-prep-v2'], focalPoint: { x: 0.69, y: 0.5 },
    source: 'OpenAI built-in image editing using the approved WAK-MODEL-I identity reference and the prior dance-studio composition',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 KKday 체험, 강사, 참가자, 연습실 또는 특정 서울 장소 사진으로 표현하지 않는다.',
      EN: 'Do not present as a photograph of the real KKday experience, instructor, participant, studio or a specific Seoul venue.',
      JP: '実際のKKday体験、講師、参加者、スタジオ、特定のソウルの場所の写真として表示しない。',
    },
  },
  {
    id: 'experience-tokyo-model-d-immersive-gallery-v2',
    src: '/media/brand-models/experience-tokyo-model-d-immersive-gallery-v2.webp',
    alt: {
      KO: '도쿄를 연상시키는 현대 미디어아트 공간에서 빛을 바라보는 여름 옷차림의 성인 여행자',
      EN: 'An adult traveller in summer clothes looking at light inside a Tokyo-inspired contemporary media-art space',
      JP: '東京をイメージした現代メディアアート空間で光を見つめる、夏服の大人の旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-D', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['summer', 'late-summer'],
    climateMood: 'luminous Tokyo summer evening indoors',
    wardrobeTags: ['sleeveless fine-knit', 'pleated midi skirt', 'flat travel sandals', 'crossbody bag'],
    activityTags: ['walking', 'exhibition visit', 'after-work city evening'],
    travelContext: 'after-work immersive-art visit during a short Tokyo stay',
    styleDirection: 'fashion-aware Tokyo summer editorial with movement',
    seasonalFit: 'breathable sleeveless knit, fluid skirt and open sandals for August',
    activityMood: 'curious, light and candid; walking rather than posing',
    realismTarget: 'high_photoreal_editorial',
    realismMethod: 'OpenAI built-in identity-preserve edit using production scene and approved WAK-MODEL-D reference',
    photorealReferenceUsed: true,
    routeUsage: [
      '/select/activity', '/en/select/activity', '/ja/select/activity',
      '/experiences/teamlab-planets-tokyo-evening',
      '/en/experiences/teamlab-planets-tokyo-evening',
      '/ja/experiences/teamlab-planets-tokyo-evening',
      '/guide/tokyo', '/en/guide/tokyo', '/ja/guide/tokyo',
      '/collections/tokyo-allinone', '/en/collections/tokyo-allinone', '/ja/collections/tokyo-allinone',
    ],
    sectionUsage: ['experience-editorial-tokyo', 'activity-card'],
    generatedFromReferenceIds: ['trip-match-model-d-itinerary-choice-v3'],
    focalPoint: { x: 0.7, y: 0.5 },
    framingMode: 'full-subject-desktop',
    safeFraming: {
      minHeadroomPercent: 4,
      preserve: ['head', 'face', 'hands', 'bag', 'feet'],
    },
    source: 'OpenAI built-in identity-preserve image editing using the approved WAK-MODEL-D reference; generic immersive-art gallery composition',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 teamLab 작품·전시장·방문객 또는 Klook 상품 사진으로 표현하지 않는다.',
      EN: 'Do not present as a photograph of a real teamLab artwork, venue, visitor or Klook product.',
      JP: '実在のteamLab作品・会場・来場者・Klook商品の写真として表示しない。',
    },
  },
  {
    id: 'domestic-busan-model-c-coastal-transition-v1',
    src: '/media/brand-models/domestic-busan-model-c-coastal-transition-v1.webp',
    alt: {
      KO: '부산을 연상시키는 해안 공간에서 가방을 들고 산책을 시작하는 여행자',
      EN: 'A traveler beginning a walk in a Busan-inspired coastal setting',
      JP: '釜山をイメージした海辺の空間で散歩を始める旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-C', localeUsage: ['ko', 'en', 'ja'],
    focalPoint: { x: 0.58, y: 0.48 },
    source: 'OpenAI image generation using user-provided WAK-MODEL-C identity reference',
    license: 'User-controlled generated brand editorial asset; commercial review completed for this use',
    createdAt: '2026-07-31',
    restriction: { KO: '실제 부산 카페·해변 또는 참가자 사진이 아니다.', EN: 'Not a real Busan café, beach or participant photograph.', JP: '実在の釜山のカフェ・海辺、または参加者の写真ではない。' },
  },
  {
    id: 'domestic-jeju-model-a-slow-stay-v1',
    src: '/media/brand-models/domestic-jeju-model-a-slow-stay-v1.webp',
    alt: {
      KO: '제주를 연상시키는 돌담과 억새 풍경 앞에서 노트를 펼친 여행자',
      EN: 'A traveler with a notebook beside stone walls and grass in a Jeju-inspired setting',
      JP: '済州をイメージした石垣とススキの風景でノートを開く旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-A', localeUsage: ['ko', 'en', 'ja'],
    focalPoint: { x: 0.72, y: 0.5 },
    source: 'OpenAI image generation using user-provided WAK-MODEL-A identity references',
    license: 'User-controlled generated brand editorial asset; commercial review completed for this use',
    createdAt: '2026-07-31',
    restriction: { KO: '실제 제주 숙소·프로그램 또는 참가자 사진이 아니다.', EN: 'Not a real Jeju stay, program or participant photograph.', JP: '実在の済州の宿・プログラム、または参加者の写真ではない。' },
  },
  {
    id: 'trip-match-model-d-city-departure-v1',
    src: '/media/brand-models/trip-match-model-d-city-departure-v1.webp',
    alt: {
      KO: '도시 이동을 앞두고 라운지에서 노트북을 닫는 여행자',
      EN: 'A traveler closing a laptop in a city departure lounge',
      JP: '街への出発前にラウンジでノートパソコンを閉じる旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-D', localeUsage: ['ko', 'en', 'ja'],
    focalPoint: { x: 0.72, y: 0.48 },
    source: 'OpenAI image generation using user-provided WAK-MODEL-D identity reference',
    license: 'User-controlled generated brand editorial asset; commercial review completed for this use',
    createdAt: '2026-07-31',
    restriction: { KO: '실제 역·교통사 또는 참가자 사진이 아니다.', EN: 'Not a real station, transport provider or participant photograph.', JP: '実在の駅・交通事業者、または参加者の写真ではない。' },
  },
  {
    id: 'home-hero-model-a-coastal-work-desktop-v2',
    src: '/media/brand-models/home-hero-model-a-coastal-work-desktop-v2.webp',
    alt: {
      KO: '해안 작업 공간에서 노트북을 닫고 다음 이동을 준비하는 여행자',
      EN: 'A traveler closing a laptop and preparing to leave an unnamed coastal workspace',
      JP: '海辺のワークスペースでノートパソコンを閉じ、次の移動を準備する旅人',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-A', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['home-hero'],
    generatedFromReferenceIds: ['wak-model-a-coastal-calm-identity-anchor'],
    focalPoints: { desktop: { x: 0.73, y: 0.48 }, mobile: { x: 0.7, y: 0.47 } },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided v2.2 WAK-MODEL-A identity anchor',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-01', verifiedAt: '2026-08-01',
    restriction: { KO: '특정 숙소·카페나 실제 Wakation 참가자 장면으로 단정하지 않는다.', EN: 'Do not identify this as a specific stay, café or real Wakation participant.', JP: '特定の宿・カフェ、または実際のWakation参加者として扱わない。' },
  },
  {
    id: 'home-hero-model-a-coastal-work-mobile-v2',
    src: '/media/brand-models/home-hero-model-a-coastal-work-mobile-v2.webp',
    alt: {
      KO: '해안 작업 공간에서 노트북과 여행 가방을 챙기는 여행자',
      EN: 'A traveler gathering a laptop and weekender in an unnamed coastal workspace',
      JP: '海辺のワークスペースでノートパソコンと旅行バッグをまとめる旅人',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelId: 'WAK-MODEL-A', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['home-hero-mobile'],
    generatedFromReferenceIds: ['wak-model-a-coastal-calm-identity-anchor'], focalPoint: { x: 0.7, y: 0.43 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided v2.2 WAK-MODEL-A identity anchor',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-01', verifiedAt: '2026-08-01',
    restriction: { KO: '특정 숙소·카페나 실제 Wakation 참가자 장면으로 단정하지 않는다.', EN: 'Do not identify this as a specific stay, café or real Wakation participant.', JP: '特定の宿・カフェ、または実際のWakation参加者として扱わない。' },
  },
  {
    id: 'home-hero-model-a-coastal-departure-desktop-v3',
    src: '/media/brand-models/home-hero-model-a-coastal-departure-desktop-v3.webp',
    alt: {
      KO: '늦여름 해안 작업 공간에서 노트북을 닫고 여행 가방을 드는 성인 여행자',
      EN: 'An adult traveler closing a laptop and lifting a weekender in an unnamed late-summer coastal workspace',
      JP: '晩夏の海辺のワークスペースでノートPCを閉じ、旅行バッグを持つ大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 960, modelId: 'WAK-MODEL-A', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'bright coastal humidity softened by an open sea breeze',
    wardrobeFamily: 'coastal-smart-casual',
    wardrobeTags: ['pale-blue linen short-sleeve overshirt', 'ivory cotton shell', 'cream straight trousers', 'low-profile loafers'],
    hairDirection: 'loose natural layers with subtle sea-breeze flyaways',
    activityTags: ['closing laptop', 'lifting canvas weekender', 'leaving after a short work block'],
    travelContext: 'late-summer work-and-travel departure',
    styleDirection: 'environment-led premium travel editorial with a generous copy-safe left field',
    seasonalFit: 'late-summer coastal daylight', activityMood: 'calm transition from work to travel',
    destinationMood: 'unnamed East Asian coastal town', realismLevel: 'high_photoreal',
    realismTarget: 'high_photoreal_editorial', realismMethod: 'identity-anchored built-in generation with anatomy, fabric and copy-safe framing review',
    photorealReferenceUsed: true, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    adjacentModelRestrictions: ['Do not place WAK-MODEL-A on the next major home card', 'Keep the following major surface place-led'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['home-hero'],
    generatedFromReferenceIds: ['wak-model-a-coastal-calm-identity-anchor', 'home-hero-model-a-coastal-work-desktop-v2'],
    focalPoint: { x: 0.7, y: 0.45 },
    safeFraming: { minHeadroomPercent: 6, preserve: ['head', 'face', 'hands', 'bag', 'device', 'feet'] },
    source: 'OpenAI built-in image generation using the user-provided v2.2 WAK-MODEL-A identity anchor as an internal reference',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 숙소·카페·참가자·프로그램 현장 사진으로 표현하지 않는다.', EN: 'Do not present as a real stay, café, participant or operating program.', JP: '実在の宿・カフェ・参加者・運営中のプログラムとして扱わない。' },
  },
  {
    id: 'home-hero-model-a-coastal-departure-mobile-v3',
    src: '/media/brand-models/home-hero-model-a-coastal-departure-mobile-v3.webp',
    alt: {
      KO: '늦여름 해안 작업 공간을 나서며 노트북과 여행 가방을 든 성인 여행자',
      EN: 'An adult traveler leaving an unnamed late-summer coastal workspace with a laptop and weekender',
      JP: '晩夏の海辺のワークスペースを出るため、ノートPCと旅行バッグを持つ大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1080, height: 1440, modelId: 'WAK-MODEL-A', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'bright coastal humidity softened by an open sea breeze',
    wardrobeFamily: 'coastal-smart-casual',
    wardrobeTags: ['pale-blue linen short-sleeve overshirt', 'ivory cotton shell', 'cream straight trousers', 'low-profile loafers'],
    hairDirection: 'loose natural layers with subtle sea-breeze flyaways',
    activityTags: ['carrying laptop', 'lifting canvas weekender', 'leaving after a short work block'],
    travelContext: 'late-summer work-and-travel departure',
    styleDirection: 'mobile art direction with headroom, complete hands and a clear left copy field',
    seasonalFit: 'late-summer coastal daylight', activityMood: 'calm transition from work to travel',
    destinationMood: 'unnamed East Asian coastal town', realismLevel: 'high_photoreal',
    realismTarget: 'high_photoreal_editorial', realismMethod: 'mobile-specific identity-anchored generation with anatomy and crop review',
    photorealReferenceUsed: true, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    adjacentModelRestrictions: ['Do not place WAK-MODEL-A on the next major home card', 'Keep the following major surface place-led'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['home-hero-mobile'],
    generatedFromReferenceIds: ['wak-model-a-coastal-calm-identity-anchor', 'home-hero-model-a-coastal-departure-desktop-v3'],
    focalPoint: { x: 0.62, y: 0.42 },
    safeFraming: { minHeadroomPercent: 8, preserve: ['head', 'face', 'hands', 'bag', 'device', 'feet'] },
    source: 'OpenAI built-in image generation using the user-provided v2.2 WAK-MODEL-A identity anchor as an internal reference',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 숙소·카페·참가자·프로그램 현장 사진으로 표현하지 않는다.', EN: 'Do not present as a real stay, café, participant or operating program.', JP: '実在の宿・カフェ・参加者・運営中のプログラムとして扱わない。' },
  },
  {
    id: 'late-summer-model-f-market-v1',
    src: '/media/seasonal/late-summer-model-f-market-v1.webp',
    alt: {
      KO: '늦여름 골든아워의 조용한 골목을 위켄더와 노트를 들고 걷는 성인 여행자',
      EN: 'An adult traveller walking through a quiet local lane at late-summer golden hour',
      JP: '晩夏のゴールデンアワーに静かな街路を歩く大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true, mediaType: 'image',
    width: 1536, height: 864, modelId: 'WAK-MODEL-F', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer', 'autumn'], routeUsage: ['/', '/en', '/ja'], sectionUsage: ['home-seasonal-hero-2026-08'],
    generatedFromReferenceIds: ['campaign-model-f-japan-choice-desktop-v1'], focalPoint: { x: 0.68, y: 0.48 },
    source: 'OpenAI built-in image generation using the approved WAK-MODEL-F production reference',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: {
      KO: '실제 고객, 참가자, 특정 일본 장소 또는 제휴 체험 현장으로 표시하지 않습니다.',
      EN: 'Do not present as a real customer, participant, specific Japanese location or partner experience.',
      JP: '実在の顧客・参加者・特定の日本の場所・提携体験として表示しないでください。',
    },
  },
  {
    id: 'home-seasonal-film-2026-08-desktop-v1',
    src: '/media/seasonal/home-seasonal-film-2026-08-desktop-v1.mp4',
    alt: {
      KO: '해안에서 출발을 준비하고 일본의 저녁 골목과 제주 바다로 이어지는 7초 무음 편집 영상',
      EN: 'Seven-second silent editorial film moving from a coastal departure to a Japan evening lane and the Jeju sea',
      JP: '海辺の出発準備から日本の夕暮れの路地、済州の海へつなぐ7秒の無音エディトリアル映像',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true, mediaType: 'video',
    width: 1920, height: 900, modelIds: ['WAK-MODEL-A', 'WAK-MODEL-F'], localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer', 'autumn'], routeUsage: ['/', '/en', '/ja'], sectionUsage: ['home-seasonal-hero-2026-08'],
    generatedFromReferenceIds: ['home-hero-model-a-coastal-departure-desktop-v3', 'campaign-model-f-japan-choice-desktop-v2', 'destination-jeju-editorial-v1'],
    focalPoint: { x: 0.66, y: 0.18 },
    source: 'Wakation Remotion composition derived from approved generated visual assets',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 고객, 참가자, 장소, 숙소, 상품 또는 프로그램 영상으로 표시하지 않습니다.',
      EN: 'Do not present as footage of real customers, participants, venues, stays, products or programs.',
      JP: '実在の顧客・参加者・施設・宿泊先・商品・プログラムの映像として表示しないでください。',
    },
  },
  {
    id: 'home-seasonal-film-2026-08-mobile-v1',
    src: '/media/seasonal/home-seasonal-film-2026-08-mobile-v1.mp4',
    alt: {
      KO: '해안에서 출발을 준비하고 일본의 저녁 골목과 제주 바다로 이어지는 세로형 7초 무음 편집 영상',
      EN: 'Portrait seven-second silent editorial film moving from a coastal departure to a Japan evening lane and the Jeju sea',
      JP: '海辺の出発準備から日本の夕暮れの路地、済州の海へつなぐ縦型7秒の無音エディトリアル映像',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true, mediaType: 'video',
    width: 1080, height: 1920, modelIds: ['WAK-MODEL-A', 'WAK-MODEL-F'], localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer', 'autumn'], routeUsage: ['/', '/en', '/ja'], sectionUsage: ['home-seasonal-hero-2026-08'],
    generatedFromReferenceIds: ['home-hero-model-a-coastal-departure-mobile-v3', 'campaign-model-f-japan-choice-mobile-v2', 'destination-jeju-editorial-v1'],
    focalPoint: { x: 0.6, y: 0.16 },
    source: 'Wakation Remotion composition derived from approved generated visual assets',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 고객, 참가자, 장소, 숙소, 상품 또는 프로그램 영상으로 표시하지 않습니다.',
      EN: 'Do not present as footage of real customers, participants, venues, stays, products or programs.',
      JP: '実在の顧客・参加者・施設・宿泊先・商品・プログラムの映像として表示しないでください。',
    },
  },
  {
    id: 'domestic-seoul-model-j-city-noir-v3',
    src: '/media/brand-models/domestic-seoul-model-j-city-noir-v3.webp',
    alt: {
      KO: '서울을 연상시키는 저녁 전시 골목을 여행 가방과 함께 걷는 여행자',
      EN: 'A traveler walking through an evening gallery lane inspired by Seoul',
      JP: 'ソウルをイメージした夕方のギャラリー通りを旅行バッグと歩く旅人',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-J', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['domestic-onboarding-seoul'],
    generatedFromReferenceIds: ['domestic-seoul-model-j-city-noir-v2'], focalPoint: { x: 0.72, y: 0.48 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-J production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 서울 매장·전시·참가자 사진이 아니다.', EN: 'Not a photograph of a real Seoul venue, exhibition or participant.', JP: '実在のソウルの店舗・展示・参加者の写真ではない。' },
  },
  {
    id: 'domestic-busan-model-e-coastal-city-v2',
    src: '/media/brand-models/domestic-busan-model-e-coastal-city-v2.webp',
    alt: {
      KO: '부산을 연상시키는 바다와 도시 사이 산책로를 걷는 여행자',
      EN: 'A traveler walking where an unnamed Busan-inspired city meets the sea',
      JP: '釜山をイメージした海と街のあいだの遊歩道を歩く旅人',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-E', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: [
      '/', '/en', '/ja',
      '/select/activity', '/en/select/activity', '/ja/select/activity',
      '/experiences/busan-coastal-highlights-day-tour',
      '/en/experiences/busan-coastal-highlights-day-tour',
      '/ja/experiences/busan-coastal-highlights-day-tour',
      '/guide/busan', '/en/guide/busan', '/ja/guide/busan',
      '/collections/busan-weekend', '/en/collections/busan-weekend', '/ja/collections/busan-weekend',
    ],
    sectionUsage: ['domestic-onboarding-busan', 'experience-editorial-busan'],
    generatedFromReferenceIds: ['wak-model-e-city-chic-identity-anchor'], focalPoint: { x: 0.34, y: 0.48 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided v2.2 WAK-MODEL-E identity anchor',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-01', verifiedAt: '2026-08-01',
    restriction: { KO: '실제 부산 해변·매장·참가자 사진이 아니다.', EN: 'Not a photograph of a real Busan beach, venue or participant.', JP: '実在の釜山の海辺・店舗・参加者の写真ではない。' },
  },
  {
    id: 'domestic-jeju-model-g-slow-stay-v2',
    src: '/media/brand-models/domestic-jeju-model-g-slow-stay-v2.webp',
    alt: {
      KO: '제주를 연상시키는 돌담과 억새 길에서 여행 일정을 적는 여행자',
      EN: 'A traveler writing beside a stone wall and silver grass in a Jeju-inspired landscape',
      JP: '済州をイメージした石垣とススキの道で旅の予定を書く旅人',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-G', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['domestic-onboarding-jeju'],
    generatedFromReferenceIds: ['wak-model-g-clean-romantic-identity-anchor'], focalPoint: { x: 0.72, y: 0.48 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided v2.2 WAK-MODEL-G identity anchor',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-01', verifiedAt: '2026-08-01',
    restriction: { KO: '실제 제주 숙소·프로그램·참가자 사진이 아니다.', EN: 'Not a photograph of a real Jeju stay, program or participant.', JP: '実在の済州の宿・プログラム・参加者の写真ではない。' },
  },
  {
    id: 'domestic-busan-model-h-haeundae-v4',
    src: '/media/brand-models/domestic-busan-model-h-haeundae-v4.webp',
    alt: {
      KO: '부산 해운대와 마린시티 해안 산책로를 걷는 여행자',
      EN: 'A traveler walking along the Haeundae waterfront with Busan Marine City in view',
      JP: '釜山・海雲台の海辺を、マリンシティを望みながら歩く旅人',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-H', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['domestic-onboarding-busan'],
    generatedFromReferenceIds: ['domestic-busan-model-h-haeundae-v3'], focalPoint: { x: 0.31, y: 0.48 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-H Busan production asset',
    license: 'User-controlled generated Wakation editorial asset; destination reference used under the Unsplash License', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 참가자나 특정 워케이션 현장 사진이 아니다.', EN: 'Not a photograph of a real participant or Wakation program.', JP: '実在の参加者やワーケーション実施風景の写真ではない。' },
  },
  {
    id: 'domestic-jeju-model-k-coastal-stay-v4',
    src: '/media/brand-models/domestic-jeju-model-k-coastal-stay-v4.webp',
    alt: {
      KO: '산방산과 제주 해안을 배경으로 여행 노트를 들고 걷는 여행자',
      EN: 'A traveler walking with a notebook above the Jeju coast and Sanbangsan',
      JP: '山房山と済州の海を背景にノートを手に歩く旅人',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1200, height: 900, modelId: 'WAK-MODEL-K', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/', '/en', '/ja'], sectionUsage: ['domestic-onboarding-jeju'],
    generatedFromReferenceIds: ['destination-jeju-editorial-v1', 'programs-model-k-stay-planning-desktop-v1'], focalPoint: { x: 0.7, y: 0.48 },
    source: 'OpenAI built-in image generation compositing a licensed Jeju destination reference with the approved WAK-MODEL-K reference',
    license: 'User-controlled generated Wakation editorial asset; destination reference used under the Unsplash License', createdAt: '2026-08-09', verifiedAt: '2026-08-09',
    restriction: { KO: '실제 참가자나 특정 워케이션 현장 사진이 아니다.', EN: 'Not a photograph of a real participant or Wakation program.', JP: '実在の参加者やワーケーション実施風景の写真ではない。' },
  },
  {
    id: 'trip-match-model-d-itinerary-choice-v3',
    src: '/media/brand-models/trip-match-model-d-itinerary-choice-v3.webp',
    alt: {
      KO: '출발 라운지에서 두 여행 일정과 노트북을 정리하는 여행자',
      EN: 'A traveler choosing between two itineraries in an unnamed departure lounge',
      JP: '出発ラウンジで2つの旅程とノートパソコンを整理する旅人',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-D', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/trip-match', '/ja/trip-match'], sectionUsage: ['trip-match-intro'],
    generatedFromReferenceIds: ['trip-match-model-d-itinerary-choice-v2'], focalPoint: { x: 0.73, y: 0.48 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-D production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 역·교통사·참가자 사진이 아니다.', EN: 'Not a photograph of a real station, transport provider or participant.', JP: '実在の駅・交通事業者・参加者の写真ではない。' },
  },
  {
    id: 'hosted-models-h-i-coastal-planning-v3',
    src: '/media/brand-models/hosted-models-h-i-coastal-planning-v3.webp',
    alt: {
      KO: '해안 공동 작업 공간에서 함께 체류 일정을 살펴보는 두 여행자',
      EN: 'Two travelers reviewing a shared stay plan in an unnamed coastal workspace',
      JP: '海辺の共同ワークスペースで滞在プランを一緒に確認する2人の旅人',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1440, height: 900, modelIds: ['WAK-MODEL-H', 'WAK-MODEL-I'], localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/hosted', '/en/hosted', '/ja/hosted'], sectionUsage: ['hosted-hero'],
    generatedFromReferenceIds: ['hosted-models-h-i-coastal-planning-v2'],
    focalPoints: { desktop: { x: 0.66, y: 0.46 }, mobile: { x: 0.58, y: 0.42 } },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-H and WAK-MODEL-I production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 Hosted 참가자·숙소·확정 프로그램 현장으로 표현하지 않는다.', EN: 'Do not present as real Hosted participants, a stay or a confirmed program location.', JP: '実在のHosted参加者・宿泊施設・確定済みプログラムの現場として表現しない。' },
  },
  {
    id: 'hosted-models-h-i-coastal-planning-mobile-v3',
    src: '/media/brand-models/hosted-models-h-i-coastal-planning-mobile-v3.webp',
    alt: {
      KO: '해안 작업 공간에서 지도와 노트를 함께 살펴보는 두 여행자',
      EN: 'Two travelers reviewing a map and notebook together in an unnamed coastal workspace',
      JP: '海辺のワークスペースで地図とノートを一緒に確認する2人の旅人',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelIds: ['WAK-MODEL-H', 'WAK-MODEL-I'], localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/hosted', '/en/hosted', '/ja/hosted'], sectionUsage: ['hosted-hero-mobile'],
    generatedFromReferenceIds: ['hosted-models-h-i-coastal-planning-mobile-v2'], focalPoint: { x: 0.5, y: 0.34 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-H and WAK-MODEL-I production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 Hosted 참가자·숙소·확정 프로그램 현장으로 표현하지 않는다.', EN: 'Do not present as real Hosted participants, a stay or a confirmed program location.', JP: '実在のHosted参加者・宿泊施設・確定済みプログラムの現場として表現しない。' },
  },
  {
    id: 'select-model-i-travel-prep-v3',
    src: '/media/brand-models/select-model-i-travel-prep-v3.webp',
    alt: {
      KO: '이동 전 라운지에서 일정표와 휴대전화를 확인하는 여행자',
      EN: 'A traveler checking an itinerary and phone in an unnamed intercity travel lounge',
      JP: '移動前のラウンジで旅程とスマートフォンを確認する旅人',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true,
    width: 1440, height: 810, modelId: 'WAK-MODEL-I', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/select', '/en/select', '/ja/select'], sectionUsage: ['select-hero-editorial'],
    generatedFromReferenceIds: ['select-model-i-travel-prep-v2'], focalPoint: { x: 0.72, y: 0.45 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-I production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 교통사·예약 고객·제휴 상품 사진이 아니다.', EN: 'Not a photograph of a real transport provider, booking customer or partner product.', JP: '実在の交通事業者・予約客・提携商品の写真ではない。' },
  },
  {
    id: 'learn-model-k-creative-focus-desktop-v1',
    src: '/media/brand-models/learn-model-k-creative-focus-desktop-v1.webp',
    alt: {
      KO: '조용한 디자인 라이브러리에서 여행 사진과 학습 노트를 정리하는 성인 여행자',
      EN: 'An adult traveler organizing trip photos and learning notes in an unnamed design library',
      JP: '静かなデザインライブラリーで旅の写真と学習ノートを整理する大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-K', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/learn'], sectionUsage: ['learn-hero'],
    generatedFromReferenceIds: ['wak-model-k-creative-navigator-identity-reference-v1'], focalPoint: { x: 0.72, y: 0.56 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided Model 10 identity reference',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: { KO: '실제 수강생·강사·교육장·강의 상품 사진으로 표현하지 않는다.', EN: 'Do not present as a real learner, teacher, venue or course product.', JP: '実在の受講者・講師・会場・講座商品として扱わない。' },
  },
  {
    id: 'learn-model-k-creative-focus-mobile-v1',
    src: '/media/brand-models/learn-model-k-creative-focus-mobile-v1.webp',
    alt: {
      KO: '디자인 라이브러리에서 여행 노트를 정리하는 성인 여행자',
      EN: 'An adult traveler organizing notes in an unnamed design library',
      JP: 'デザインライブラリーで旅のノートを整理する大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelId: 'WAK-MODEL-K', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/learn'], sectionUsage: ['learn-hero-mobile'],
    generatedFromReferenceIds: ['wak-model-k-creative-navigator-identity-reference-v1'], focalPoint: { x: 0.62, y: 0.57 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided Model 10 identity reference',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: { KO: '실제 수강생·강사·교육장·강의 상품 사진으로 표현하지 않는다.', EN: 'Do not present as a real learner, teacher, venue or course product.', JP: '実在の受講者・講師・会場・講座商品として扱わない。' },
  },
  {
    id: 'programs-model-k-stay-planning-desktop-v1',
    src: '/media/brand-models/programs-model-k-stay-planning-desktop-v1.webp',
    alt: {
      KO: '해안 공동 작업 공간에서 지도와 일정표로 체류 계획을 세우는 성인 여행자',
      EN: 'An adult traveler planning a stay with a map and calendar in an unnamed coastal workspace',
      JP: '海辺の共同ワークスペースで地図と予定表を使い滞在計画を立てる大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1440, height: 900, modelId: 'WAK-MODEL-K', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/programs', '/en/programs', '/ja/programs'], sectionUsage: ['programs-hero'],
    generatedFromReferenceIds: ['wak-model-k-creative-navigator-identity-reference-v1'], focalPoint: { x: 0.73, y: 0.52 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided Model 10 identity reference',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: { KO: '실제 Wakation 참가자·숙소·확정 프로그램 현장으로 표현하지 않는다.', EN: 'Do not present as a real Wakation participant, stay or confirmed program location.', JP: '実際のWakation参加者・宿泊施設・確定済みプログラムの現場として扱わない。' },
  },
  {
    id: 'programs-model-k-stay-planning-mobile-v1',
    src: '/media/brand-models/programs-model-k-stay-planning-mobile-v1.webp',
    alt: {
      KO: '해안 작업 공간에서 체류 일정과 여행 가방을 정리하는 성인 여행자',
      EN: 'An adult traveler arranging a stay plan and weekender in a coastal workspace',
      JP: '海辺のワークスペースで滞在予定と旅行バッグを整える大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelId: 'WAK-MODEL-K', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/programs', '/en/programs', '/ja/programs'], sectionUsage: ['programs-hero-mobile'],
    generatedFromReferenceIds: ['wak-model-k-creative-navigator-identity-reference-v1'], focalPoint: { x: 0.62, y: 0.54 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided Model 10 identity reference',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: { KO: '실제 Wakation 참가자·숙소·확정 프로그램 현장으로 표현하지 않는다.', EN: 'Do not present as a real Wakation participant, stay or confirmed program location.', JP: '実際のWakation参加者・宿泊施設・確定済みプログラムの現場として扱わない。' },
  },
  {
    id: 'growth-model-b-urban-learning-desktop-v2',
    src: '/media/brand-models/growth-model-b-urban-learning-desktop-v2.webp',
    alt: {
      KO: '도시 카페 라운지에서 여행 지도와 학습 노트를 정리하는 성인 여행자',
      EN: 'An adult traveler organizing a map and learning notes in an unnamed city café lounge',
      JP: '街のカフェラウンジで旅の地図と学びのノートを整理する大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-B', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/growth'], sectionUsage: ['growth-hero'],
    generatedFromReferenceIds: ['growth-model-b-urban-learning-desktop-v1'], focalPoint: { x: 0.72, y: 0.5 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-B production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 수강생·캠프 참가자·교육장·운영 프로그램의 현장으로 표현하지 않는다.', EN: 'Do not present as a real learner, camp participant, venue or operating program.', JP: '実在の受講者・キャンプ参加者・会場・運営中プログラムの現場として扱わない。' },
  },
  {
    id: 'growth-model-b-urban-learning-mobile-v2',
    src: '/media/brand-models/growth-model-b-urban-learning-mobile-v2.webp',
    alt: {
      KO: '도시 카페에서 지도와 노트를 정리하는 성인 여행자',
      EN: 'An adult traveler organizing a map and notes in a city café',
      JP: '街のカフェで地図とノートを整理する大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelId: 'WAK-MODEL-B', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/growth'], sectionUsage: ['growth-hero-mobile'],
    generatedFromReferenceIds: ['growth-model-b-urban-learning-desktop-v2'], focalPoint: { x: 0.65, y: 0.56 },
    source: 'Responsive crop derived from the approved late-summer WAK-MODEL-B desktop production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 수강생·캠프 참가자·교육장·운영 프로그램의 현장으로 표현하지 않는다.', EN: 'Do not present as a real learner, camp participant, venue or operating program.', JP: '実在の受講者・キャンプ参加者・会場・運営中プログラムの現場として扱わない。' },
  },
  {
    id: 'business-model-c-team-planning-desktop-v1',
    src: '/media/brand-models/business-model-c-team-planning-desktop-v1.webp',
    alt: {
      KO: '도시 라운지에서 빈 기획 자료를 검토하는 성인 여행자의 기업 워케이션 장면',
      EN: 'An adult traveler reviewing a blank planning folio in an unnamed city lounge',
      JP: '街のラウンジで無記名の企画資料を確認する大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-C', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/business'], sectionUsage: ['business-hero'],
    generatedFromReferenceIds: ['wak-model-c-quiet-premium-identity-anchor'], focalPoint: { x: 0.72, y: 0.5 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided v2.2 WAK-MODEL-C identity anchor',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: { KO: '실제 고객·직원·컨설턴트·팀 프로그램·사업장 사진으로 표현하지 않는다.', EN: 'Do not present as a real client, employee, consultant, team program or business venue.', JP: '実在の顧客・従業員・コンサルタント・チームプログラム・事業所の写真として扱わない。' },
  },
  {
    id: 'business-model-c-team-planning-mobile-v1',
    src: '/media/brand-models/business-model-c-team-planning-mobile-v1.webp',
    alt: {
      KO: '도시 라운지에서 빈 기획 자료를 살펴보는 성인 여행자',
      EN: 'An adult traveler reviewing a blank planning folio in a city lounge',
      JP: '街のラウンジで無記名の企画資料を見る大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelId: 'WAK-MODEL-C', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/business'], sectionUsage: ['business-hero-mobile'],
    generatedFromReferenceIds: ['wak-model-c-quiet-premium-identity-anchor'], focalPoint: { x: 0.65, y: 0.55 },
    source: 'OpenAI image generation in built-in imagegen mode using the user-provided v2.2 WAK-MODEL-C identity anchor',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: { KO: '실제 고객·직원·컨설턴트·팀 프로그램·사업장 사진으로 표현하지 않는다.', EN: 'Do not present as a real client, employee, consultant, team program or business venue.', JP: '実在の顧客・従業員・コンサルタント・チームプログラム・事業所の写真として扱わない。' },
  },
  {
    id: 'business-models-c-h-k-late-summer-team-desktop-v2',
    src: '/media/brand-models/business-models-c-h-k-late-summer-team-desktop-v2.webp',
    alt: {
      KO: '늦여름의 시원한 해안 업무 라운지에서 일정표와 노트북을 펼쳐 놓고 워케이션을 기획하는 성인 팀',
      EN: 'An adult team planning a workation with an itinerary and laptop in a cool late-summer coastal work lounge',
      JP: '晩夏の涼しい海辺のワークラウンジで、旅程表とノートパソコンを広げてワーケーションを計画する大人のチーム',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelIds: ['WAK-MODEL-C', 'WAK-MODEL-H', 'WAK-MODEL-K'], localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/business'], sectionUsage: ['business-hero'],
    generatedFromReferenceIds: ['wak-model-c-quiet-premium-identity-anchor', 'wak-model-h-soft-daylight-identity-anchor-v2-2', 'wak-model-k-creative-navigator-identity-reference-v1'], focalPoint: { x: 0.72, y: 0.25 },
    source: 'OpenAI built-in image generation using the user-controlled Wakation model roster references',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 고객·직원·참가자·팀 프로그램·사업장의 현장 사진으로 표현하지 않는다.', EN: 'Do not present as a real client, employee, participant, team program or business venue.', JP: '実際の顧客・社員・参加者・チームプログラム・事業所の現場写真として表示しない。' },
  },
  {
    id: 'business-models-c-h-k-late-summer-team-mobile-v2',
    src: '/media/brand-models/business-models-c-h-k-late-summer-team-mobile-v2.webp',
    alt: {
      KO: '늦여름의 시원한 해안 업무 라운지에서 일정표를 함께 살펴보며 워케이션을 기획하는 성인 팀',
      EN: 'An adult team reviewing an itinerary together in a cool late-summer coastal work lounge',
      JP: '晩夏の涼しい海辺のワークラウンジで、旅程表を一緒に確認しながらワーケーションを計画する大人のチーム',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelIds: ['WAK-MODEL-C', 'WAK-MODEL-H', 'WAK-MODEL-K'], localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/business'], sectionUsage: ['business-hero-mobile'],
    generatedFromReferenceIds: ['business-models-c-h-k-late-summer-team-desktop-v2', 'hosted-models-h-i-coastal-planning-mobile-v2'], focalPoint: { x: 0.65, y: 0.5 },
    source: 'OpenAI built-in image generation using the user-controlled Wakation model roster references',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 고객·직원·참가자·팀 프로그램·사업장의 현장 사진으로 표현하지 않는다.', EN: 'Do not present as a real client, employee, participant, team program or business venue.', JP: '実際の顧客・社員・参加者・チームプログラム・事業所の現場写真として表示しない。' },
  },
  {
    id: 'campaign-model-f-japan-choice-desktop-v2',
    src: '/media/brand-models/campaign-model-f-japan-choice-desktop-v2.webp',
    alt: {
      KO: '이름 없는 일본풍 강변 거리에서 여행 지도를 살펴보는 성인 여행자',
      EN: 'An adult traveler checking a map beside an unnamed Japan-inspired riverside street',
      JP: '特定の場所ではない日本らしい川沿いの街で地図を見る大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 1536, height: 1024, modelId: 'WAK-MODEL-F', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/campaign/japan-short-stay'], sectionUsage: ['campaign-japan-short-stay-hero'],
    generatedFromReferenceIds: ['campaign-model-f-japan-choice-desktop-v1'], focalPoint: { x: 0.73, y: 0.52 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-F production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 관광객·고객·가이드·투어·특정 도시나 랜드마크의 현장 사진으로 표현하지 않는다.', EN: 'Do not present as a real tourist, customer, guide, tour, city or landmark photograph.', JP: '実在の旅行者・顧客・ガイド・ツアー・特定都市やランドマークの写真として扱わない。' },
  },
  {
    id: 'campaign-model-f-japan-choice-mobile-v2',
    src: '/media/brand-models/campaign-model-f-japan-choice-mobile-v2.webp',
    alt: {
      KO: '일본풍 강변 거리에서 지도를 살펴보는 성인 여행자',
      EN: 'An adult traveler checking a map on a Japan-inspired riverside street',
      JP: '日本らしい川沿いの街で地図を見る大人の旅行者',
    },
    sourceType: 'generated', usage: 'hero', illustrative: true,
    width: 960, height: 1280, modelId: 'WAK-MODEL-F', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/campaign/japan-short-stay'], sectionUsage: ['campaign-japan-short-stay-hero-mobile'],
    generatedFromReferenceIds: ['campaign-model-f-japan-choice-desktop-v2'], focalPoint: { x: 0.63, y: 0.59 },
    source: 'Responsive crop derived from the approved late-summer WAK-MODEL-F desktop production asset',
    license: 'User-controlled generated brand editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: { KO: '실제 관광객·고객·가이드·투어·특정 도시나 랜드마크의 현장 사진으로 표현하지 않는다.', EN: 'Do not present as a real tourist, customer, guide, tour, city or landmark photograph.', JP: '実在の旅行者・顧客・ガイド・ツアー・特定都市やランドマークの写真として扱わない。' },
  },
  {
    id: 'activity-seoul-baseball-editorial-v2',
    src: '/covers/activity-seoul-baseball-editorial-v2.webp',
    alt: {
      KO: '인물과 구단 표식 없이 조명이 켜진 야간 야구장',
      EN: 'An illuminated empty baseball stadium without people or team marks',
      JP: '人物や球団の表示がない、照明の灯る無人の野球場',
    },
    sourceType: 'generated',
    usage: 'editorial',
    illustrative: true,
    focalPoint: { x: 0.58, y: 0.56 },
    source: 'OpenAI image generation; Wakation editorial direction',
    license: 'Wakation-owned generated editorial asset',
    createdAt: '2026-07-31',
  },
  {
    id: 'trip-set-fukuoka-model-g-cafe-v2',
    src: '/campaign/trip-sets/fukuoka-3n4d-editorial-model-g-v2.webp',
    alt: {
      KO: '햇살이 드는 카페 창가에서 두 손으로 찻잔을 들고 쉬는 성인 여행자',
      EN: 'An adult traveler holding a cup with both hands beside a sunlit cafe window',
      JP: '陽射しの入るカフェの窓辺で、カップを両手に持ってひと休みする大人の旅行者',
    },
    sourceType: 'generated',
    usage: 'editorial',
    illustrative: true,
    width: 1536,
    height: 1024,
    modelId: 'WAK-MODEL-G',
    localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'],
    routeUsage: ['/', '/en', '/ja', '/collections/fukuoka-3n4d', '/en/collections/fukuoka-3n4d', '/ja/collections/fukuoka-3n4d', '/campaign/japan-short-stay'],
    sectionUsage: ['home-mood', 'home-duration', 'trip-set-hero', 'campaign-choice', 'navigation-campaign'],
    generatedFromReferenceIds: ['wak-model-g-clean-romantic-identity-anchor'],
    focalPoints: { desktop: { x: 0.48, y: 0.48 }, mobile: { x: 0.48, y: 0.48 } },
    source: 'OpenAI built-in image generation using the approved WAK-MODEL-G identity reference',
    license: 'User-controlled generated brand editorial asset',
    createdAt: '2026-08-10',
    verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 고객·참가자·숙소·체험 현장 사진으로 표현하지 않는다.',
      EN: 'Do not present as a real customer, participant, stay or experience photograph.',
      JP: '実在の顧客・参加者・宿泊施設・体験現場の写真として表現しない。',
    },
  },
  {
    id: 'itoshima-coast-editorial-model-g-v2',
    src: '/campaign/itoshima-coast-editorial-model-g-v2.webp',
    alt: {
      KO: '바다를 바라보며 카메라를 든 여행자의 이토시마 분위기 장면',
      EN: 'A traveler with a camera overlooking a coast inspired by Itoshima',
      JP: '海を眺めながらカメラを持つ旅人を描いた糸島らしい旅の場面',
    },
    sourceType: 'generated',
    usage: 'editorial',
    illustrative: true,
    width: 1536,
    height: 1024,
    modelId: 'WAK-MODEL-G',
    localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'],
    routeUsage: ['/experiences/itoshima-photo-bus-tour', '/en/experiences/itoshima-photo-bus-tour', '/ja/experiences/itoshima-photo-bus-tour', '/select/activity'],
    sectionUsage: ['experience-editorial-hero', 'activity-card'],
    generatedFromReferenceIds: ['wak-model-g-clean-romantic-identity-anchor', 'trip-set-fukuoka-model-g-cafe-v2'],
    focalPoint: { x: 0.68, y: 0.5 },
    source: 'OpenAI built-in image generation using the approved WAK-MODEL-G identity reference',
    license: 'User-controlled generated brand editorial asset',
    createdAt: '2026-08-10',
    verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 체험 참가자·가이드·운영 차량·코스 현장 사진으로 표현하지 않는다.',
      EN: 'Do not present as a real participant, guide, operator vehicle or tour-course photograph.',
      JP: '実在の体験参加者・ガイド・運営車両・ツアーコースの写真として表現しない。',
    },
  },
  {
    id: 'programs-editorial-coastal-work-v1',
    src: '/campaign/programs-editorial-coastal-work-v1.webp',
    alt: {
      KO: '바다를 바라보며 다음 일정을 정리하는 여행자',
      EN: 'A traveler planning the next day by the sea',
      JP: '海を眺めながら翌日の予定を整える旅人',
    },
    sourceType: 'generated',
    usage: 'hero',
    illustrative: true,
    focalPoint: { x: 0.62, y: 0.48 },
    source: 'OpenAI image generation; Wakation art direction prompt archived in docs/ui-polish-audit-2026-07-30.md',
    license: 'Wakation-owned generated editorial asset',
    createdAt: '2026-07-30',
  },
  {
    id: 'trip-set-tokyo-workation-editorial-v2',
    src: '/media/trip-sets/tokyo-workation-editorial-v2.webp',
    alt: {
      KO: '도쿄의 조용한 거리에서 노트북을 들고 이동하는 여행자',
      EN: 'A traveler carrying a laptop through a quiet Tokyo neighborhood',
      JP: '東京の静かな街でノートパソコンを持って移動する旅行者',
    },
    sourceType: 'generated',
    usage: 'editorial',
    illustrative: true,
    mediaType: 'image',
    width: 1536,
    height: 1024,
    localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'],
    routeUsage: ['/', '/en', '/ja', '/collections/tokyo-allinone', '/en/collections/tokyo-allinone', '/ja/collections/tokyo-allinone'],
    sectionUsage: ['home-trip-sets', 'trip-set-hero'],
    focalPoint: { x: 0.62, y: 0.12 },
    source: 'OpenAI image generation; Wakation editorial direction',
    license: 'Wakation-owned generated editorial asset',
    createdAt: '2026-08-09',
  },
  {
    id: 'destination-tokyo-editorial-v1',
    src: '/media/destinations/tokyo-editorial-v1.webp',
    alt: { KO: '비 내린 도쿄 도심의 네온 거리', EN: 'A neon-lit Tokyo street after rain', JP: '雨上がりの東京、ネオンが映る街並み' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.5, y: 0.52 },
    source: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf',
    license: 'Unsplash License',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-osaka-editorial-v1',
    src: '/media/destinations/osaka-editorial-v1.webp',
    alt: { KO: '쓰텐카쿠가 보이는 오사카 신세카이 거리', EN: 'Shinsekai street in Osaka with Tsutenkaku tower', JP: '通天閣を望む大阪・新世界の街並み' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.5, y: 0.44 },
    source: 'https://unsplash.com/photos/uBfK5i6j1B8',
    license: 'Unsplash License — photo by Nomadic Julien',
    createdAt: '2026-07-30',
  },
  {
    id: 'osaka-morning-food-lane-v1',
    src: '/media/destinations/osaka-morning-food-lane-v1.webp',
    alt: {
      KO: '늦여름 아침 장사를 준비하는 일본 도심의 작은 시장 골목',
      EN: 'A small Japanese city market lane preparing to open on a late-summer morning',
      JP: '晩夏の朝、開店準備が進む日本の街中の小さな市場路地',
    },
    sourceType: 'generated', usage: 'destination', illustrative: true, mediaType: 'image',
    width: 1536, height: 1024, localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'humid late-summer Osaka-inspired market morning with soft arcade light',
    activityTags: ['morning food lane', 'market walk', 'short city stay'],
    activityMood: 'quiet neighborhood discovery before the workday',
    destinationMood: 'Osaka-inspired compact food and shopping arcade',
    travelContext: 'guide lookbook; a generic place-led editorial scene with no venue claim',
    styleDirection: 'natural 35mm place-led travel editorial with realistic market textures',
    realismLevel: 'high_photoreal', realismTarget: 'high_photoreal_editorial',
    realismMethod: 'New place-led photoreal generation without a model identity reference',
    photorealReferenceUsed: false, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    routeUsage: ['/guide/osaka', '/en/guide/osaka', '/ja/guide/osaka'],
    sectionUsage: ['guide-lookbook-morning-food-lane'],
    focalPoint: { x: 0.5, y: 0.52 },
    source: 'OpenAI built-in ImageGen; Wakation editorial direction',
    license: 'Wakation-owned generated editorial asset',
    createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 오사카 시장·매장·영업 상태 또는 특정 장소 사진으로 표시하지 않는다.',
      EN: 'Do not present as a photograph of a specific Osaka market, shop, operating status or venue.',
      JP: '実在の大阪の市場・店舗・営業状況、または特定の場所の写真として表示しない。',
    },
  },
  {
    id: 'osaka-model-j-after-work-gallery-v1',
    src: '/media/brand-models/osaka-model-j-after-work-gallery-v1.webp',
    alt: {
      KO: '늦여름 저녁 전시 공간을 나와 도시 지도를 살피며 걷는 여행자',
      EN: 'A traveler walking after an exhibition while checking a city map on a late-summer evening',
      JP: '晩夏の夕方、展示を見た後に街の地図を確認しながら歩く旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true, mediaType: 'image',
    width: 1536, height: 1024, modelId: 'WAK-MODEL-J', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'humid late-summer Japanese city blue hour with warm gallery light',
    wardrobeFamily: 'breathable modest urban evening',
    wardrobeTags: ['ivory short-sleeve blouse', 'charcoal ankle-length skirt', 'flat leather sandals'],
    hairDirection: 'sleek straight black hair with full head preserved',
    activityTags: ['after-work exhibition', 'city walk', 'map reading'],
    activityMood: 'composed evening transition after focused work',
    destinationMood: 'Osaka-inspired exhibition and city passage',
    travelContext: 'guide lookbook; general editorial scene, not a real venue or participant',
    styleDirection: 'natural blue-hour 35mm travel editorial with real skin and fabric texture',
    realismLevel: 'high_photoreal', realismTarget: 'high_photoreal_editorial',
    realismMethod: 'Identity-preserve generation from the official WAK-MODEL-J v2.2 anchor',
    photorealReferenceUsed: true, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    routeUsage: ['/guide/osaka', '/en/guide/osaka', '/ja/guide/osaka'],
    sectionUsage: ['guide-lookbook-after-work-exhibition'],
    generatedFromReferenceIds: ['wak-model-j-city-noir-identity-anchor-v2-2'],
    focalPoint: { x: 0.72, y: 0.48 },
    safeFraming: { minHeadroomPercent: 12, preserve: ['head', 'face', 'hands', 'documents', 'bag', 'feet'] },
    source: 'OpenAI built-in ImageGen using the user-approved WAK-MODEL-J v2.2 identity anchor',
    license: 'User-controlled generated brand editorial asset',
    createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 오사카 전시장·프로그램·참가자 또는 고객 사진이 아니다.',
      EN: 'Not a photograph of a real Osaka venue, program, participant or customer.',
      JP: '実在の大阪の会場・プログラム・参加者、または顧客の写真ではない。',
    },
  },
  {
    id: 'fukuoka-model-h-cafe-work-v1',
    src: '/media/brand-models/fukuoka-model-h-cafe-work-v1.webp',
    alt: {
      KO: '여름날 일본 도심 카페에서 노트북과 종이 일정을 함께 살피는 여행자',
      EN: 'A traveler reviewing a paper itinerary beside a laptop in a Japanese city café in summer',
      JP: '夏の日本の街中のカフェで、ノートパソコンと紙の予定表を確認する旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true, mediaType: 'image',
    width: 1536, height: 1024, modelId: 'WAK-MODEL-H', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'warm humid Japanese city morning with soft indoor daylight',
    wardrobeFamily: 'breathable modest city casual',
    wardrobeTags: ['sage short-sleeve linen blouse', 'ivory wide-leg trousers'],
    hairDirection: 'long soft waves with airy curtain bangs, full head preserved',
    activityTags: ['cafe work', 'itinerary review', 'short city stay'],
    activityMood: 'quiet morning planning before exploring',
    destinationMood: 'Fukuoka-inspired compact urban stay',
    travelContext: 'guide lookbook; general editorial scene, not a real venue or participant',
    styleDirection: 'natural 35mm travel editorial with real skin and fabric texture',
    realismLevel: 'high_photoreal', realismTarget: 'high_photoreal_editorial',
    realismMethod: 'Identity-preserve generation from the official WAK-MODEL-H v2.2 anchor',
    photorealReferenceUsed: true, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    routeUsage: ['/guide/fukuoka', '/en/guide/fukuoka', '/ja/guide/fukuoka'],
    sectionUsage: ['guide-lookbook-morning-work'],
    generatedFromReferenceIds: ['wak-model-h-soft-daylight-identity-anchor-v2-2'],
    focalPoint: { x: 0.72, y: 0.44 },
    safeFraming: { minHeadroomPercent: 8, preserve: ['head', 'face', 'hands', 'device', 'documents'] },
    source: 'OpenAI built-in ImageGen using the user-approved WAK-MODEL-H v2.2 identity anchor',
    license: 'User-controlled generated brand editorial asset',
    createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 후쿠오카 카페·숙소·프로그램 또는 참가자 사진이 아니다.',
      EN: 'Not a photograph of a real Fukuoka café, stay, program or participant.',
      JP: '実在の福岡のカフェ・宿・プログラム、または参加者の写真ではない。',
    },
  },
  {
    id: 'fukuoka-after-work-riverside-v1',
    src: '/media/destinations/fukuoka-after-work-riverside-v1.webp',
    alt: {
      KO: '여름 저녁 강변 산책로와 따뜻한 불빛의 작은 음식점이 이어지는 일본 도시 풍경',
      EN: 'A Japanese city riverside walk lined with small warmly lit eateries on a summer evening',
      JP: '夏の夜、川沿いの散歩道に温かな灯りの小さな飲食店が並ぶ日本の街並み',
    },
    sourceType: 'generated', usage: 'destination', illustrative: true, mediaType: 'image',
    width: 1536, height: 1024, localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'humid late-summer blue hour with warm ambient light',
    activityTags: ['after-work walk', 'riverside', 'evening lanes'],
    activityMood: 'calm evening transition after work',
    destinationMood: 'Fukuoka-inspired riverside food-stall atmosphere',
    travelContext: 'guide lookbook; a generic place-led editorial scene with no venue claim',
    styleDirection: 'documentary-inspired place-led travel photography',
    realismLevel: 'high_photoreal', realismTarget: 'high_photoreal_editorial',
    realismMethod: 'New place-led photoreal generation without a model identity reference',
    photorealReferenceUsed: false, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    routeUsage: ['/guide/fukuoka', '/en/guide/fukuoka', '/ja/guide/fukuoka'],
    sectionUsage: ['guide-lookbook-after-work'],
    focalPoint: { x: 0.5, y: 0.54 },
    source: 'OpenAI built-in ImageGen; Wakation editorial direction',
    license: 'Wakation-owned generated editorial asset',
    createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 후쿠오카 포장마차·식당·영업 상태 또는 특정 장소 사진으로 표시하지 않는다.',
      EN: 'Do not present as a photograph of a specific Fukuoka stall, restaurant, operating status or venue.',
      JP: '実在の福岡の屋台・飲食店・営業状況、または特定の場所の写真として表示しない。',
    },
  },
  {
    id: 'destination-fukuoka-editorial-v1',
    src: '/media/destinations/fukuoka-editorial-v1.webp',
    alt: { KO: '호수와 도심이 이어지는 후쿠오카의 한낮 풍경', EN: 'A lakeside view framed by Fukuoka city', JP: '湖と街が穏やかにつながる福岡の風景' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.5, y: 0.66 },
    source: 'https://unsplash.com/photos/OxkZ2A9KoT0',
    license: 'Unsplash License — photo by Aibolat Askhar',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-bali-editorial-v1',
    src: '/media/destinations/bali-editorial-v1.webp',
    alt: { KO: '물가에 자리한 발리의 전통 사원', EN: 'A traditional Balinese temple beside the water', JP: '水辺にたたずむバリの伝統寺院' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.5, y: 0.46 },
    source: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4',
    license: 'Unsplash License',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-danang-editorial-v1',
    src: '/media/destinations/danang-editorial-v1.webp',
    alt: { KO: '산 위를 가로지르는 다낭 골든브리지', EN: 'The Golden Bridge crossing the mountains near Da Nang', JP: 'ダナン近郊の山上に架かるゴールデンブリッジ' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.52, y: 0.5 },
    source: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b',
    license: 'Unsplash License',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-chiangmai-editorial-v1',
    src: '/media/destinations/chiangmai-editorial-v1.webp',
    alt: { KO: '초록 정원에 둘러싸인 치앙마이의 사원', EN: 'A Chiang Mai temple surrounded by a green courtyard', JP: '緑豊かな庭に囲まれたチェンマイの寺院' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.59, y: 0.5 },
    source: 'https://unsplash.com/photos/F07KhNovxRk',
    license: 'Unsplash License — photo by Peter Borter',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-cebu-editorial-v1',
    src: '/media/destinations/cebu-editorial-v1.webp',
    alt: { KO: '불빛이 켜진 세부 시티의 야경', EN: 'The illuminated skyline of Cebu City at night', JP: '明かりが灯るセブシティの夜景' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.53, y: 0.48 },
    source: 'https://unsplash.com/photos/ply-6rPZKSA',
    license: 'Unsplash License — photo by Zany Jadraque',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-sydney-editorial-v1',
    src: '/media/destinations/sydney-editorial-v1.webp',
    alt: { KO: '오페라하우스와 도심이 펼쳐진 시드니 항구', EN: 'Sydney Harbour with the Opera House and city skyline', JP: 'オペラハウスと街並みを望むシドニー湾' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.43, y: 0.5 },
    source: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9',
    license: 'Unsplash License',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-jeju-editorial-v1',
    src: '/media/destinations/jeju-editorial-v1.webp',
    alt: { KO: '제주 바다 건너 산방산과 한라산이 이어지는 풍경', EN: 'Jeju coast with Sanbangsan and Hallasan beyond the sea', JP: '海の向こうに山房山と漢拏山を望む済州の風景' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.5, y: 0.52 },
    source: 'https://unsplash.com/photos/EQ-QSQp283M',
    license: 'Unsplash License — photo by Lux Park',
    createdAt: '2026-07-30',
  },
  {
    id: 'destination-seoul-editorial-v1',
    src: '/media/destinations/seoul-editorial-v1.webp',
    alt: { KO: '불빛과 한글 간판이 이어진 서울의 저녁 골목', EN: 'A Seoul evening street lined with lights and Hangul signs', JP: '灯りとハングルの看板が連なるソウルの夕暮れの路地' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.5, y: 0.54 },
    source: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451',
    license: 'Unsplash License',
    createdAt: '2026-07-30',
  },
  {
    id: 'seoul-model-b-after-work-design-lane-v1',
    src: '/media/brand-models/seoul-model-b-after-work-design-lane-v1.webp',
    alt: {
      KO: '늦여름 비가 그친 디자인 골목을 노트북 슬리브와 가방을 들고 걷는 성인 여행자',
      EN: 'An adult traveler carrying a laptop sleeve and bag through a design lane after late-summer rain',
      JP: '晩夏の雨上がり、ノートパソコンケースとバッグを持ってデザイン街を歩く成人旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true, mediaType: 'image',
    width: 1536, height: 1024, modelId: 'WAK-MODEL-B', localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'fresh humid Seoul-inspired afternoon after late-summer rain',
    wardrobeFamily: 'breathable urban after-work casual',
    wardrobeTags: ['pale-blue short-sleeve cotton shirt', 'cream lightweight trousers', 'city sneakers'],
    hairDirection: 'natural long dark hair with full head preserved',
    activityTags: ['after-work walk', 'design district', 'laptop sleeve'],
    activityMood: 'light transition from focused work to neighborhood discovery',
    destinationMood: 'Seoul-inspired converted-brick design lane',
    travelContext: 'guide lookbook; general editorial scene, not a real venue or participant',
    styleDirection: 'natural 35mm travel editorial with realistic skin, fabric and wet-street texture',
    realismLevel: 'high_photoreal', realismTarget: 'high_photoreal_editorial',
    realismMethod: 'Identity-preserve generation from an approved WAK-MODEL-B production derivative',
    photorealReferenceUsed: true, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    routeUsage: ['/guide/seoul', '/en/guide/seoul', '/ja/guide/seoul'],
    sectionUsage: ['guide-lookbook-after-work-design-lane'],
    generatedFromReferenceIds: ['growth-model-b-urban-learning-desktop-v2'],
    focalPoint: { x: 0.68, y: 0.5 },
    safeFraming: { minHeadroomPercent: 12, preserve: ['head', 'face', 'hands', 'device', 'bag', 'feet'] },
    source: 'OpenAI built-in ImageGen using an approved WAK-MODEL-B production derivative as identity reference',
    license: 'User-controlled generated brand editorial asset',
    createdAt: '2026-08-11', verifiedAt: '2026-08-11',
    restriction: {
      KO: '실제 서울 매장·프로그램·참가자 또는 고객 사진이 아니다.',
      EN: 'Not a photograph of a real Seoul venue, program, participant or customer.',
      JP: '実在のソウルの店舗・プログラム・参加者、または顧客の写真ではない。',
    },
  },
  {
    id: 'seoul-evening-neighborhood-lane-v1',
    src: '/media/destinations/seoul-evening-neighborhood-lane-v1.webp',
    alt: {
      KO: '늦여름 비가 그친 뒤 카페 불빛과 나무가 이어지는 저층 도시 골목',
      EN: 'A low-rise city lane with trees and warm café lights after late-summer rain',
      JP: '晩夏の雨上がり、木々とカフェの灯りが続く低層の街の路地',
    },
    sourceType: 'generated', usage: 'destination', illustrative: true, mediaType: 'image',
    width: 1536, height: 1024, localeUsage: ['ko', 'en', 'ja'],
    seasonalUsage: ['late-summer'], season: 'late-summer',
    climateMood: 'late-summer Seoul-inspired blue hour after rain',
    activityTags: ['evening neighborhood walk', 'small cafés', 'after-work reset'],
    activityMood: 'unhurried neighborhood discovery after focused work',
    destinationMood: 'Seoul-inspired low-rise café and residential lane',
    travelContext: 'guide lookbook; a generic place-led editorial scene with no venue claim',
    styleDirection: 'natural 35mm place-led travel editorial with crisp wet-street detail',
    realismLevel: 'high_photoreal', realismTarget: 'high_photoreal_editorial',
    realismMethod: 'New place-led photoreal generation without a model identity reference',
    photorealReferenceUsed: false, generationProvider: 'openai_builtin_imagegen', auditDisposition: 'KEEP',
    routeUsage: ['/guide/seoul', '/en/guide/seoul', '/ja/guide/seoul'],
    sectionUsage: ['guide-lookbook-blue-hour-local-lane'],
    focalPoint: { x: 0.5, y: 0.5 },
    source: 'OpenAI built-in ImageGen; Wakation editorial direction',
    license: 'Wakation-owned generated editorial asset',
    createdAt: '2026-08-11', verifiedAt: '2026-08-11',
    restriction: {
      KO: '실제 서울 골목·카페·매장 또는 특정 장소 사진으로 표시하지 않는다.',
      EN: 'Do not present as a photograph of a specific Seoul lane, café, shop or venue.',
      JP: '実在のソウルの路地・カフェ・店舗、または特定の場所の写真として表示しない。',
    },
  },
  {
    id: 'destination-busan-editorial-v1',
    src: '/media/destinations/busan-editorial-v1.webp',
    alt: { KO: '해운대 해변과 마린시티가 함께 보이는 부산 풍경', EN: 'Busan view across Haeundae Beach and Marine City', JP: '海雲台ビーチとマリンシティを望む釜山の風景' },
    sourceType: 'licensed',
    usage: 'destination',
    illustrative: false,
    focalPoint: { x: 0.47, y: 0.5 },
    source: 'https://images.unsplash.com/photo-1638591751482-1a7d27fcea15',
    license: 'Unsplash License',
    createdAt: '2026-07-30',
  },
  {
    id: 'monthly-2026-08-model-e-city-arrival-v2',
    src: '/media/brand-models/monthly-2026-08-model-e-city-arrival-v2.webp',
    alt: {
      KO: '이름 없는 해안 도시 터미널에서 여행 동선을 살펴보는 성인 여행자',
      EN: 'An adult traveller reviewing her route at an unnamed coastal-city terminal',
      JP: '場所を特定しない海辺の街のターミナルで旅の動線を確認する成人旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true, mediaType: 'image',
    width: 1200, height: 1500, modelId: 'WAK-MODEL-E', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/about'], sectionUsage: ['monthly-model-editorial-2026-08'],
    generatedFromReferenceIds: ['wak-model-e-city-chic-identity-anchor'], focalPoint: { x: 0.54, y: 0.45 },
    source: 'OpenAI built-in image generation using the user-provided v2.2 WAK-MODEL-E identity anchor',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: {
      KO: '실제 여행자, 고객, 터미널, 교통사 또는 프로그램 현장으로 표시하지 않습니다.',
      EN: 'Do not present as a real traveller, customer, terminal, transport provider or program scene.',
      JP: '実在の旅行者、顧客、ターミナル、交通事業者、プログラム会場として表示しません。',
    },
  },
  {
    id: 'monthly-2026-08-model-h-coastal-reset-v1',
    src: '/media/brand-models/monthly-2026-08-model-h-coastal-reset-v1.webp',
    alt: {
      KO: '이름 없는 해안 카페에서 노트북과 노트를 정리하는 성인 여행자',
      EN: 'An adult traveller packing her notebook at an unnamed coastal café',
      JP: '場所を特定しない海辺のカフェでノートを片づける成人旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true, mediaType: 'image',
    width: 1200, height: 1500, modelId: 'WAK-MODEL-H', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/about'], sectionUsage: ['monthly-model-editorial-2026-08'],
    generatedFromReferenceIds: ['wak-model-h-soft-daylight-identity-anchor-v2-2'], focalPoint: { x: 0.55, y: 0.42 },
    source: 'OpenAI built-in image generation using the user-provided v2.2 WAK-MODEL-H identity anchor',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: {
      KO: '실제 여행자, 고객, 카페, 숙소 또는 Hosted 프로그램 현장으로 표시하지 않습니다.',
      EN: 'Do not present as a real traveller, customer, café, stay or Hosted program scene.',
      JP: '実在の旅行者、顧客、カフェ、宿泊施設、Hostedプログラム会場として表示しません。',
    },
  },
  {
    id: 'monthly-2026-08-model-j-blue-hour-v2',
    src: '/media/brand-models/monthly-2026-08-model-j-blue-hour-v2.webp',
    alt: {
      KO: '이름 없는 도시의 강변에서 업무 후 시간을 확인하는 성인 여행자',
      EN: 'An adult traveller checking the time beside an unnamed city river',
      JP: '場所を特定しない街の川辺で仕事後の時間を確認する成人旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true, mediaType: 'image',
    width: 1200, height: 1500, modelId: 'WAK-MODEL-J', localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/about'], sectionUsage: ['monthly-model-editorial-2026-08'],
    generatedFromReferenceIds: ['wak-model-j-city-noir-identity-anchor-v2-2'], focalPoint: { x: 0.43, y: 0.42 },
    source: 'OpenAI built-in image generation using the user-provided v2.2 WAK-MODEL-J identity anchor',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: {
      KO: '실제 여행자, 고객, 도시, 시설 또는 프로그램 현장으로 표시하지 않습니다.',
      EN: 'Do not present as a real traveller, customer, city, venue or program scene.',
      JP: '実在の旅行者、顧客、都市、施設、プログラム会場として表示しません。',
    },
  },
  {
    id: 'monthly-2026-08-model-g-coastal-book-cafe-v2',
    src: '/media/brand-models/monthly-2026-08-model-g-coastal-book-cafe-v2.webp',
    alt: {
      KO: '이름 없는 해안 북카페를 나서며 노트를 든 성인 여행자',
      EN: 'An adult traveller leaving an unnamed coastal book café with a notebook',
      JP: '場所を特定しない海辺のブックカフェをノートを手に出る成人旅行者',
    },
    sourceType: 'generated', usage: 'editorial', illustrative: true, mediaType: 'image',
    width: 1200, height: 1500, modelId: 'WAK-MODEL-G', localeUsage: ['ko', 'en', 'ja'], seasonalUsage: ['late-summer'],
    routeUsage: ['/about'], sectionUsage: ['monthly-model-editorial-2026-08'],
    generatedFromReferenceIds: ['monthly-2026-08-model-g-coastal-book-cafe-v1'], focalPoint: { x: 0.62, y: 0.44 },
    source: 'OpenAI built-in identity-preserving wardrobe edit of the approved WAK-MODEL-G production asset',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-10', verifiedAt: '2026-08-10',
    restriction: {
      KO: '실제 여행자, 고객, 카페, 숙소 또는 프로그램 현장으로 표시하지 않습니다.',
      EN: 'Do not present as a real traveller, customer, café, stay or program scene.',
      JP: '実在の旅行者、顧客、カフェ、宿泊施設、プログラム会場として表示しません。',
    },
  },
  {
    id: 'monthly-model-edit-2026-08-v2',
    src: '/media/brand-models/monthly-model-edit-2026-08-v2.mp4',
    alt: {
      KO: '도시 도착, 해안의 리셋, 블루아워 이동을 담은 15초 무음 월간 편집 영상',
      EN: 'A 15-second silent monthly editorial film about city arrival, a coastal reset and blue-hour movement',
      JP: '街への到着、海辺でのリセット、ブルーアワーの移動を描く15秒の無音マンスリー編集映像',
    },
    sourceType: 'generated', usage: 'social', illustrative: true, mediaType: 'video',
    width: 1080, height: 1920, modelIds: ['WAK-MODEL-E', 'WAK-MODEL-H', 'WAK-MODEL-J'], localeUsage: ['ko', 'en', 'ja'],
    routeUsage: ['/about'], sectionUsage: ['monthly-model-editorial-2026-08'],
    generatedFromReferenceIds: ['monthly-2026-08-model-e-city-arrival-v2', 'monthly-2026-08-model-h-coastal-reset-v1', 'monthly-2026-08-model-j-blue-hour-v2'],
    focalPoint: { x: 0.5, y: 0.5 },
    source: 'Wakation Remotion composition derived from three approved generated visual assets',
    license: 'User-controlled generated Wakation editorial asset', createdAt: '2026-08-08', verifiedAt: '2026-08-08',
    restriction: {
      KO: '실제 고객, 참가자, 장소 또는 프로그램 영상으로 표시하지 않습니다.',
      EN: 'Do not present as footage of real customers, participants, venues or programs.',
      JP: '実在の顧客、参加者、施設、プログラムの映像として表示しません。',
    },
  },
  {
    id: 'destination-gangneung-anmok-licensed-v1',
    src: '/media/destinations/gangneung-anmok-licensed-v1.webp',
    alt: {
      KO: '강릉 안목해변의 모래사장과 안전초소',
      EN: 'Anmok Beach and its lifeguard tower in Gangneung',
      JP: '江陵・安木海岸の砂浜と監視塔',
    },
    sourceType: 'licensed', usage: 'destination', illustrative: false, mediaType: 'image',
    width: 1280, height: 853, localeUsage: ['ko', 'en', 'ja'], focalPoint: { x: 0.64, y: 0.56 },
    source: 'https://commons.wikimedia.org/wiki/File:Anmok_Beach_20220430_010.jpg',
    license: 'CC BY-SA 4.0 — Mobius6; resized and converted to WebP', createdAt: '2026-08-09', verifiedAt: '2026-08-09',
  },
  {
    id: 'destination-yangyang-naksan-licensed-v1',
    src: '/media/destinations/yangyang-naksan-licensed-v1.webp',
    alt: {
      KO: '파도가 밀려오는 양양 낙산해수욕장',
      EN: 'Waves at Naksan Beach in Yangyang',
      JP: '波が寄せる襄陽・洛山海水浴場',
    },
    sourceType: 'licensed', usage: 'destination', illustrative: false, mediaType: 'image',
    width: 1280, height: 853, localeUsage: ['ko', 'en', 'ja'], focalPoint: { x: 0.56, y: 0.52 },
    source: 'https://commons.wikimedia.org/wiki/File:낙산해수욕장.jpg',
    license: 'CC BY-SA 3.0 — 칼빈500; resized and converted to WebP', createdAt: '2026-08-09', verifiedAt: '2026-08-09',
  },
  {
    id: 'destination-jeongseon-atrain-licensed-v1',
    src: '/media/destinations/jeongseon-atrain-licensed-v1.webp',
    alt: {
      KO: '정선역 승강장의 정선아리랑열차 A-train',
      EN: 'The Jeongseon Arirang A-train at Jeongseon Station',
      JP: '旌善駅に停車するアリラン列車A-train',
    },
    sourceType: 'licensed', usage: 'destination', illustrative: false, mediaType: 'image',
    width: 1024, height: 613, localeUsage: ['ko', 'en', 'ja'], focalPoint: { x: 0.56, y: 0.5 },
    source: 'https://commons.wikimedia.org/wiki/File:A-Train_(Korail),_Jeongseon_Arirang_Train,_2015.jpg',
    license: 'CC BY-SA 2.0 — Korea.net / Jeon Han; converted to WebP', createdAt: '2026-08-09', verifiedAt: '2026-08-09',
  },
  ...CARD_MEDIA_ASSETS,
  ...PRODUCT_EDITORIAL_MEDIA_ASSETS,
]

export function getMediaAsset(id: string): MediaAsset | undefined {
  return MEDIA_ASSETS.find((asset) => asset.id === id)
}

export function getMediaAssetBySrc(src: string): MediaAsset | undefined {
  return MEDIA_ASSETS.find((asset) => asset.src === src)
}
