import type { MediaAsset } from '@/lib/media/assets'

const EDITORIAL_RESTRICTION = {
  KO: '실제 제휴 숙소·객실·프로그램 현장 사진으로 표현하지 않는다.',
  EN: 'Do not present as an exact partner stay, room or program location.',
  JP: '実在の提携宿泊施設・客室・プログラム会場の写真として表示しない。',
}

export const PRODUCT_EDITORIAL_MEDIA_ASSETS: MediaAsset[] = [
  {
    id: 'accommodation-urban-studio-editorial-v1',
    src: '/media/product-editorial/accommodation-urban-studio-editorial-v1.webp',
    alt: { KO: '업무용 책상과 침대가 함께 있는 도시형 스튜디오 편집 이미지', EN: 'Editorial urban studio with a work desk and bed', JP: 'ワークデスクとベッドを備えた都市型スタジオのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.52, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'tropical-coliving-editorial-v1',
    src: '/media/product-editorial/tropical-coliving-editorial-v1.webp',
    alt: { KO: '열대 식물과 공용 업무 테이블이 있는 코리빙 공간 편집 이미지', EN: 'Editorial tropical coliving courtyard with a shared work table', JP: '南国の植物と共用ワークテーブルがあるコリビングのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.5, y: 0.52 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'social-stay-lounge-editorial-v1',
    src: '/media/product-editorial/social-stay-lounge-editorial-v1.webp',
    alt: { KO: '공용 테이블과 조용한 업무 코너가 있는 소셜 스테이 라운지 편집 이미지', EN: 'Editorial social-stay lounge with communal tables and a quiet work nook', JP: '共用テーブルと静かなワークコーナーがあるソーシャルステイのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.56, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'coastal-apartment-editorial-v1',
    src: '/media/product-editorial/coastal-apartment-editorial-v1.webp',
    alt: { KO: '바다를 향한 업무 책상이 있는 해안형 아파트 편집 이미지', EN: 'Editorial coastal apartment with a desk facing the sea', JP: '海を望むワークデスクのある海辺のアパートメントのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.5, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'serviced-apartment-editorial-v1',
    src: '/media/product-editorial/serviced-apartment-editorial-v1.webp',
    alt: { KO: '간이 주방과 업무 테이블이 있는 장기체류형 아파트 편집 이미지', EN: 'Editorial serviced apartment with a kitchenette and work table', JP: '簡易キッチンとワークテーブルを備えた長期滞在型アパートのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.5, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'design-hotel-lobby-editorial-v1',
    src: '/media/product-editorial/design-hotel-lobby-editorial-v1.webp',
    alt: { KO: '조용한 업무 코너가 있는 디자인 호텔 로비 편집 이미지', EN: 'Editorial design-hotel lobby with a quiet work corner', JP: '静かなワークコーナーを備えたデザインホテルロビーのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.5, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'japanese-apartment-editorial-v1',
    src: '/media/product-editorial/japanese-apartment-editorial-v1.webp',
    alt: { KO: '낮은 침대와 업무 테이블이 있는 일본식 도시 아파트 편집 이미지', EN: 'Editorial Japanese-inspired city apartment with a work table', JP: 'ローベッドとワークテーブルを備えた和モダンな都市型アパートのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.53, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'city-highrise-apartment-editorial-v1',
    src: '/media/product-editorial/city-highrise-apartment-editorial-v1.webp',
    alt: { KO: '도시 전망과 업무 책상이 있는 고층 서비스드 아파트 편집 이미지', EN: 'Editorial high-rise serviced apartment with a city-view desk', JP: 'シティビューのデスクを備えた高層サービスアパートのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.55, y: 0.48 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'coastal-residence-editorial-v1',
    src: '/media/product-editorial/coastal-residence-editorial-v1.webp',
    alt: { KO: '바다 전망 발코니와 업무 테이블이 있는 장기체류형 레지던스 편집 이미지', EN: 'Editorial long-stay coastal residence with a balcony and work table', JP: '海を望むバルコニーとワークテーブルがある長期滞在型レジデンスのイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.5, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'tropical-boutique-room-editorial-v1',
    src: '/media/product-editorial/tropical-boutique-room-editorial-v1.webp',
    alt: { KO: '열대 정원 테라스와 업무 책상이 있는 부티크 장기체류 객실 편집 이미지', EN: 'Editorial tropical boutique long-stay room with a terrace work desk', JP: '熱帯のテラスとワークデスクを備えたブティック長期滞在客室のイメージ写真' },
    sourceType: 'generated', usage: 'product', illustrative: true, width: 1200, height: 900,
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/select/hotel'], sectionUsage: ['product-card'],
    focalPoint: { x: 0.55, y: 0.5 }, source: 'OpenAI built-in image generation; prompt archived in docs/product-program-media-truth-2026-08.md',
    license: 'Wakation-owned generated editorial asset', createdAt: '2026-08-02', verifiedAt: '2026-08-02', restriction: EDITORIAL_RESTRICTION,
  },
  {
    id: 'program-jeonju-hanok-licensed-v1',
    src: '/media/product-editorial/program-jeonju-hanok-licensed-v1.webp',
    alt: { KO: '전주 한옥마을의 골목과 한옥 지붕', EN: 'A lane and traditional roofs in Jeonju Hanok Village', JP: '全州韓屋村の路地と韓屋の屋根' },
    sourceType: 'licensed', usage: 'editorial', illustrative: false, width: 1200, height: 900,
    // 2026-08-03 가이드 12번째 도시 전주 신설 — 가이드 히어로·목적지 카드에 재사용
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/programs/domestic', '/guide/jeonju', '/select/hotel'], sectionUsage: ['program-card', 'guide-hero', 'destination-card'],
    focalPoint: { x: 0.5, y: 0.5 }, source: 'https://commons.wikimedia.org/wiki/File:20240727_Jeonju_Hanok_Village_001.jpg',
    license: 'CC BY 4.0 — Jjw; resized and converted to WebP', verifiedAt: '2026-08-02',
  },
  {
    id: 'program-yeosu-harbor-licensed-v1',
    src: '/media/product-editorial/program-yeosu-harbor-licensed-v1.webp',
    alt: { KO: '여수 앞바다와 항구 전경', EN: 'The coast and harbor of Yeosu', JP: '麗水の海岸と港の風景' },
    sourceType: 'licensed', usage: 'editorial', illustrative: false, width: 1200, height: 675,
    // 2026-08-03 가이드 13번째 도시 여수 신설 — 가이드 히어로·목적지 카드에 재사용
    localeUsage: ['ko', 'en', 'ja'], routeUsage: ['/programs/domestic', '/guide/yeosu', '/select/hotel'], sectionUsage: ['program-card', 'guide-hero', 'destination-card'],
    focalPoint: { x: 0.5, y: 0.5 }, source: 'https://commons.wikimedia.org/wiki/File:Korea-Yeosu-Harbor-01.jpg',
    license: 'CC BY 2.0 — LWY; resized and converted to WebP', verifiedAt: '2026-08-02',
  },
]
